// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Corporate Event Planners & Experiential/Brand Activation Agencies
// Partnership targets for HH&T — these companies run events needing cocktail bars
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const CORPORATE_EXPERIENTIAL_LEADS = [
  // ═══════════════════════════════════════════════════════
  // CORPORATE EVENT PLANNERS
  // ═══════════════════════════════════════════════════════
  { venue_name: "MGN Events", location: "Windsor, Berkshire", city: "Windsor", county: "Berkshire", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 25, website: "mgnevents.co.uk", trigger_event: "Award-winning — conferences, experiential campaigns, gala dinners, product launches, corporate Christmas parties", contact_email: "info@mgnevents.co.uk", phone: "01753 858611" },
  { venue_name: "Ex Events", location: "London", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 0, website: "exevents.co.uk", trigger_event: "30+ years delivering corporate summer/Christmas parties, conferences, and celebrations for startups to international corporations", contact_email: "info@exevents.co.uk", phone: "020 7183 5808" },
  { venue_name: "Purple Patch Group", location: "London", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 0, website: "purplepatchgroup.co.uk", trigger_event: "Leading UK events agency — clients include Arla, NHS Trusts, Sainsbury's, Reckitt. Conferences, awards ceremonies, corporate entertainment", contact_email: "hello@purplepatchgroup.co.uk", phone: "020 7935 0088" },
  { venue_name: "KDM Events", location: "London & Staffordshire", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 0, website: "kdmevents.co.uk", trigger_event: "Over 1,000 events per year. 30+ years. Best Event Provider 2025. Team away days, awards dinners, conferences, Christmas parties", contact_email: "events@kdmevents.co.uk", phone: "01onal 543 8888" },
  { venue_name: "Snapdragon Parties", location: "London", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 300, distance_from_london_miles: 0, website: "snapdragonparties.com", trigger_event: "Listed in Spear's 500 three consecutive years. Luxury product launches, client entertainment, corporate Christmas parties, gala dinners", contact_email: "hello@snapdragonparties.com", phone: "020 3141 8720" },
  { venue_name: "Banana Split", location: "London", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 1000, distance_from_london_miles: 0, website: "banana-split.com", trigger_event: "50 years in luxury event production. Formula E hospitality, The OWO launch with Andrea Bocelli, charity events raising £1.6m+", contact_email: "hello@banana-split.com", phone: "020 8200 1234" },
  { venue_name: "Penguins Events", location: "London & Worcestershire", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 0, website: "penguins.co.uk", trigger_event: "30+ years. Conferences, sales kick-offs, gala dinners, awards ceremonies, incentive travel. Two offices covering London and Midlands", contact_email: "enquiries@penguins.co.uk", phone: "01753 833811" },
  { venue_name: "Julia Charles Event Management", location: "Milton Keynes, Buckinghamshire", city: "Milton Keynes", county: "Buckinghamshire", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 50, website: "juliacharleseventmanagement.co.uk", trigger_event: "20 years of corporate events — Netflix, Amazon, MINI, The Telegraph. B2B events, conferences, brand activations", contact_email: "info@juliacharleseventmanagement.co.uk", phone: "01onal 374 1660" },
  { venue_name: "Banks Sadler (BCD M&E)", location: "London & York", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 1000, distance_from_london_miles: 0, website: "banks-sadler.com", trigger_event: "4th largest UK event agency. 250+ staff, 13,500+ venue bookings/year, 570+ events in 66 countries. Tech, automotive, finance, pharmaceutical clients", contact_email: "enquiries@banks-sadler.com", phone: "020 7534 0800" },
  { venue_name: "Smyle Creative", location: "Hailsham, East Sussex", city: "Hailsham", county: "East Sussex", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 60, website: "smyle.co.uk", trigger_event: "Record-breaking UK Agency of the Year. 300+ employees. In-person brand activations, conferences, awards, experiential events", contact_email: "hello@smyle.co.uk", phone: "01323 442244" },
  { venue_name: "Purple Lamb Events", location: "Littleport, Cambridgeshire", city: "Littleport", county: "Cambridgeshire", category: "Corporate Event Planner", capacity: 300, distance_from_london_miles: 75, website: "purplelambevents.co.uk", trigger_event: "Boutique agency — Audi UK, Panasonic, Nissan, Jaguar, Cisco, Fujitsu. Automotive launches, corporate conferences, incentive programmes", contact_email: "info@purplelambevents.co.uk", phone: "01353 863200" },
  { venue_name: "Mirage Parties", location: "Guildford, Surrey", city: "Guildford", county: "Surrey", category: "Corporate Event Planner", capacity: 400, distance_from_london_miles: 30, website: "mirageparties.co.uk", trigger_event: "30+ years as Surrey's leading luxury event planners. Corporate Christmas parties, brand festivals, product launches", contact_email: "info@mirageparties.co.uk", phone: "01483 304540" },
  { venue_name: "Liquid Media", location: "Swindon, Wiltshire", city: "Swindon", county: "Wiltshire", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 80, website: "liquidmedia.co.uk", trigger_event: "Live event production — conferences, gala dinners, product launches, award ceremonies, roadshows across UK & Europe", contact_email: "info@liquidmedia.co.uk", phone: "01793 327200" },
  { venue_name: "In Any Event", location: "Bristol, Somerset", city: "Bristol", county: "Somerset", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 120, website: "inanyevent-uk.com", trigger_event: "Est. 1990. 30+ years corporate events from Bristol — conferences, incentive travel, exhibitions, corporate hospitality across UK & Europe", contact_email: "events@inanyevent-uk.com", phone: "01172 303434" },
  { venue_name: "Eventologists", location: "Leicester", city: "Leicester", county: "Leicestershire", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 100, website: "eventologists.co.uk", trigger_event: "40 years collective experience. Galas, awards ceremonies, corporate Christmas parties, full event production across the UK", contact_email: "hello@eventologists.co.uk", phone: "0116 243 1192" },
  { venue_name: "Top Banana", location: "London", city: "London", county: "Greater London", category: "Corporate Event Planner", capacity: 500, distance_from_london_miles: 0, website: "top-b.com", trigger_event: "Live, virtual, hybrid events. Themed events, immersive brand activations, conferences, gala dinners. Works globally", contact_email: "hello@top-b.com", phone: "020 7580 3905" },

  // ═══════════════════════════════════════════════════════
  // EXPERIENTIAL & BRAND ACTIVATION AGENCIES
  // ═══════════════════════════════════════════════════════
  { venue_name: "Amplify", location: "London (global)", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "weareamplify.com", trigger_event: "Campaign's Brand Experience Agency of the Decade. Google, Netflix, Spotify, PlayStation, Airbnb, Adidas, Porsche, Burberry", contact_email: "hello@weareamplify.com", phone: "020 7378 0800" },
  { venue_name: "RPM", location: "Shepherd's Bush, London", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "rpmltd.com", trigger_event: "Employee-owned, 30+ years, 10,000+ projects. Diageo, Mondelez, Ferrero, Kellogg's, Sky, Disney, Heineken, Cadbury", contact_email: "hello@rpmltd.com", phone: "020 8749 7080" },
  { venue_name: "TRO", location: "London (Omnicom Group)", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "tro.com", trigger_event: "Global agency — BMW, MINI, Just Eat, British Airways, Google, Under Armour. Olympic Games, UEFA Champions League, Goodwood activations", contact_email: "info@tro.com", phone: "020 8996 5700" },
  { venue_name: "Bearded Kitten", location: "London (acquired by Havas Play)", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "beardedkitten.com", trigger_event: "Immersive experience design — Netflix, Unilever, L'Oreal, Red Bull, Pokemon, Disney, Pernod Ricard. Own fabrication studio", contact_email: "hello@beardedkitten.com", phone: "020 7017 8760" },
  { venue_name: "Sense", location: "Oxford Street, London", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "sensemktg.com", trigger_event: "20+ years independent. TikTok, The Economist, Revolut, eBay, Molson Coors, Coca-Cola, Marriott International", contact_email: "info@sensemktg.com", phone: "020 7017 2000" },
  { venue_name: "Hyperactive", location: "Farringdon, London", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "wearehyperactive.com", trigger_event: "Gen Z/Millennial focus — Beats by Dre, Eurostar, Tag Heuer, Carlsberg, Xbox, Porsche, Virgin Atlantic, Chelsea FC", contact_email: "hello@wearehyperactive.com", phone: "020 3286 3410" },
  { venue_name: "Create London", location: "London", city: "London", county: "Greater London", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 0, website: "createlondon.co.uk", trigger_event: "Experiential tours, pop-ups, immersive experiences — Adidas, Spotify, Samsung, Bacardi, Marc Jacobs, Tiffany & Co., Amazon", contact_email: "info@createlondon.co.uk", phone: "020 7240 1142" },
  { venue_name: "Relish Agency", location: "Marlow, Buckinghamshire", city: "Marlow", county: "Buckinghamshire", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 33, website: "relishagency.com", trigger_event: "Live brand activations, pop-ups, sampling — Diageo, McVitie's. Strong in drinks, beauty, wellness sectors. Uses VR/AR", contact_email: "hello@relishagency.com", phone: "01628 482260" },
  { venue_name: "Sketch Events", location: "Hove, East Sussex", city: "Hove", county: "East Sussex", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 55, website: "sketchevents.co.uk", trigger_event: "PR stunts, brand activations — Netflix, Corona, The Shard, Disney, e.l.f. Cosmetics, Heinz, Paddy Power, Sky Arts", contact_email: "hello@sketchevents.co.uk", phone: "01273 747500" },
  { venue_name: "Scene2", location: "Essex (near M25)", city: "Brentwood", county: "Essex", category: "Experiential Agency", capacity: 300, distance_from_london_miles: 25, website: "scene2.co.uk", trigger_event: "17,000 sq ft workshop — Netflix, Coca-Cola, Absolut, John Lewis, EE, Samsung, Budweiser. IPM Service Agency of the Year", contact_email: "info@scene2.co.uk", phone: "01onal 775 6644" },
];
