// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// HH&T New Business Leads — Three Categories
// Category 1: University & College Venues (Oxford, Cambridge, other universities)
// Category 2: Boutique Hotel Groups & Chains with Event Spaces
// Category 3: PR Agencies with Event Divisions
// All within 150 miles of London
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 1: UNIVERSITY & COLLEGE VENUES
// Prestigious colleges and universities that hire out halls, gardens, and
// event spaces for private events, weddings, and conferences.
// ═══════════════════════════════════════════════════════════════════════════════

export const UNIVERSITY_VENUE_LEADS = [
  // OXFORD COLLEGES
  { venue_name: "Christ Church, University of Oxford", location: "St Aldates, Oxford — iconic Great Hall (inspiration for Harry Potter), cathedral, and Tom Quad", city: "Oxford", county: "Oxfordshire", category: "University Venue", capacity: 250, distance_from_london_miles: 56, website: "chch.ox.ac.uk", trigger_event: "Hosts residential conferences, summer schools, day meetings, and private dinners. Clients return year after year. Great Hall seats 250 for formal dining. Adults only (18+)", contact_email: "events@chch.ox.ac.uk", phone: "01865 592232" },
  { venue_name: "Keble College, University of Oxford", location: "Parks Road, Oxford — Victorian Gothic brick masterpiece with longest dining hall in Oxford", city: "Oxford", county: "Oxfordshire", category: "University Venue", capacity: 300, distance_from_london_miles: 56, website: "conference.keble.ox.ac.uk", trigger_event: "Gala dinners for 300, intimate weddings for 30, two hybrid lecture theatres, 16 syndicate rooms, ample outdoor space for marquees and drinks receptions. Licensed for weddings", contact_email: "events@conference.keble.ox.ac.uk", phone: "01865 592232" },
  { venue_name: "Magdalen College, University of Oxford", location: "High Street, Oxford — medieval hall where Oscar Wilde and John Betjeman dined, set in deer park grounds", city: "Oxford", county: "Oxfordshire", category: "University Venue", capacity: 160, distance_from_london_miles: 56, website: "magd.ox.ac.uk/venue-hire", trigger_event: "Self-contained conference facilities for up to 160. Fully equipped air-conditioned auditorium with tiered seating, seminar rooms, and the Terry Newport Room for intimate dinners of 44", contact_email: "events@magd.ox.ac.uk", phone: "01865 592232" },
  { venue_name: "Hertford College, University of Oxford", location: "Catte Street, Oxford — home of the iconic Bridge of Sighs spanning New College Lane", city: "Oxford", county: "Oxfordshire", category: "University Venue", capacity: 150, distance_from_london_miles: 56, website: "hertford.ox.ac.uk", trigger_event: "Conferences and events programme running Oct 2025 through March 2026. Venue hire for dinners, receptions, and meetings in heart of Oxford", contact_email: "events@hertford.ox.ac.uk", phone: "01865 592232" },
  { venue_name: "Balliol College, University of Oxford", location: "Broad Street, Oxford — one of Oxford's oldest colleges (founded 1263), beautiful gardens and historic hall", city: "Oxford", county: "Oxfordshire", category: "University Venue", capacity: 180, distance_from_london_miles: 56, website: "balliol.ox.ac.uk", trigger_event: "Available through Conference Oxford for conferences, meetings, private dinners, and celebrations. Central location on Broad Street with accommodation available", contact_email: "events@balliol.ox.ac.uk", phone: "01865 592232" },

  // CAMBRIDGE COLLEGES
  { venue_name: "St John's College, University of Cambridge", location: "St John's Street, Cambridge — 18 acres of stunning grounds overlooking the River Cam with Bridge of Sighs", city: "Cambridge", county: "Cambridgeshire", category: "University Venue", capacity: 200, distance_from_london_miles: 55, website: "joh.cam.ac.uk", trigger_event: "Award-winning hospitality for conferences, wedding receptions, and private dinners. Perfect blend of breathtaking history and contemporary service in the heart of Cambridge", contact_email: "events@joh.cam.ac.uk", phone: "01223 172248" },
  { venue_name: "Trinity Hall, University of Cambridge", location: "Trinity Lane, Cambridge — one of Cambridge's oldest colleges, founded 1350, on the banks of the Cam", city: "Cambridge", county: "Cambridgeshire", category: "University Venue", capacity: 120, distance_from_london_miles: 55, website: "conferences.trinhall.cam.ac.uk", trigger_event: "Outstanding venue for conferences, dinners, weddings, and special events with overnight accommodation. Wedding packages for 60-120 guests plus intimate packages for smaller celebrations", contact_email: "events@conferences.trinhall.cam.ac.uk", phone: "01223 172248" },
  { venue_name: "Downing College, University of Cambridge", location: "Regent Street, Cambridge — neoclassical architecture with 20 acres of lush grounds, short walk from city centre", city: "Cambridge", county: "Cambridgeshire", category: "University Venue", capacity: 180, distance_from_london_miles: 55, website: "downing-conferences-cambridge.co.uk", trigger_event: "Flexible venue for conferences, meetings, weddings, and gala dinners. 180 ensuite bedrooms for residential events. Beautiful gardens for summer receptions", contact_email: "events@downing-conferences-cambridge.co.uk", phone: "01223 172248" },
  { venue_name: "Madingley Hall, University of Cambridge", location: "Madingley, Cambridge — 16th-century country house in 7 acres of Capability Brown gardens, 4 miles from Cambridge", city: "Cambridge", county: "Cambridgeshire", category: "University Venue", capacity: 100, distance_from_london_miles: 58, website: "madingleyhall.co.uk", trigger_event: "60 minutes from London. 16 well-equipped meeting rooms for up to 100 delegates. En-suite accommodation in spectacular gardens. Intimate and prestigious setting for premium events", contact_email: "events@madingleyhall.co.uk", phone: "01223 172248" },

  // OTHER UNIVERSITIES
  { venue_name: "University of Bristol — Venues & Events", location: "Multiple venues across Stoke Bishop, Clifton, and campus — stunning buildings in the heart of the city", city: "Bristol", county: "Bristol", category: "University Venue", capacity: 800, distance_from_london_miles: 118, website: "bristol.ac.uk/venues", trigger_event: "Wide choice of rooms, lecture theatres, and exhibition spaces for events up to 800 delegates. First-class service across multiple prestigious buildings in a vibrant city", contact_email: "events@bristol.ac.uk", phone: "0117 548 8016" },
  { venue_name: "University of Exeter — Event Exeter", location: "Streatham Campus, Exeter — Great Hall seating 1,433, The Forum, and Streatham Court in landscaped grounds", city: "Exeter", county: "Devon", category: "University Venue", capacity: 1433, distance_from_london_miles: 148, website: "event.exeter.ac.uk", trigger_event: "Impressive portfolio of conference venues and meeting rooms. Great Hall seats up to 1,433. The Forum is a stunning centrepiece flooded with natural light. Recently refurbished Streatham Court", contact_email: "events@event.exeter.ac.uk", phone: "01392 380320" },
];


// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 2: BOUTIQUE HOTEL GROUPS & CHAINS WITH EVENT SPACES
// Hotel groups (not individual hotels) with multiple properties offering
// event/conference facilities across Southern England.
// These groups often maintain preferred supplier lists for bar services.
// ═══════════════════════════════════════════════════════════════════════════════

export const HOTEL_GROUP_LEADS = [
  { venue_name: "Exclusive Collection", location: "8 luxury properties across Southern England — Pennyhill Park (Surrey), South Lodge (Sussex), Lainston House (Hampshire), Royal Berkshire (Ascot), Manor House (Wiltshire), Fanhams Hall (Herts), Castle Inn (Castle Combe)", city: "Guildford", county: "Surrey", category: "Hotel Group", capacity: 500, distance_from_london_miles: 30, website: "exclusive.co.uk", trigger_event: "First UK hotel group to become a certified B Corporation. Award-winning event venues for VIP get-togethers, board-level retreats, awards bashes, company parties, and celebrations. Dedicated event professionals across all properties", contact_email: "hello@exclusive.co.uk", phone: "01483 736264" },
  { venue_name: "Hand Picked Hotels", location: "21 distinctive country house hotels from Scotland to the Channel Islands — HQ at The Old Library, Sevenoaks, Kent. Southern properties include Chilston Park (Kent), Brandshatch Place (Kent), New Hall (Warwickshire)", city: "Sevenoaks", county: "Kent", category: "Hotel Group", capacity: 300, distance_from_london_miles: 25, website: "handpickedhotels.co.uk", trigger_event: "Founded 2001 by Julia Hands MBE. Hosts only one wedding per day — exclusive-use option available. Couples meet Head Chef to discuss bespoke menus. Wedding open days in Kent. Corporate retreats across the collection", contact_email: "hello@handpickedhotels.co.uk", phone: "01552 156580" },
  { venue_name: "Harbour Hotels", location: "14 hotels across southern England — Southampton, Brighton, Bristol, Guildford, Chichester, Richmond, Christchurch, Salcombe, Sidmouth, Fowey, Padstow, St Ives, and Froyle Park", city: "Christchurch", county: "Dorset", category: "Hotel Group", capacity: 300, distance_from_london_miles: 100, website: "harbourhotels.co.uk", trigger_event: "Winner of AA Hotel Group of the Year. 14 properties with dedicated event spaces — Froyle Park seats 300 for exclusive use. Southampton hosts up to 250. Expert event crew across coastal, countryside, and city venues", contact_email: "hello@harbourhotels.co.uk", phone: "01904 372976" },
  { venue_name: "Alexander Hotels", location: "5 country house hotels just outside London — Great Fosters (Surrey, Michelin-starred), Alexander House (Sussex, 100 acres), Barnett Hill (Surrey), Langshott Manor (Surrey), Rowhill Grange (Kent)", city: "East Grinstead", county: "West Sussex", category: "Hotel Group", capacity: 200, distance_from_london_miles: 30, website: "alexanderhotels.co.uk", trigger_event: "Established 1994. Great Fosters has Michelin-starred Tudor Room. Alexander House is 45 minutes from London with 7 meeting rooms, capacity up to 130 for private dining. Just 9 miles from Gatwick. Product launches, conferences, weddings", contact_email: "hello@alexanderhotels.co.uk", phone: "01232 472808" },
  { venue_name: "THE PIG Hotels", location: "8 laid-back country house hotels across southern England — New Forest, Southampton, Brockenhurst, Bath, Devon, Dorset, Kent (Bridge Place), with new openings planned", city: "Brockenhurst", county: "Hampshire", category: "Hotel Group", capacity: 150, distance_from_london_miles: 85, website: "thepighotel.com", trigger_event: "Restaurant-led hotel group — garden-to-plate dining and 'knock-out drinks' are central to the brand. Garden feasts, seasonal suppers, wine tastings, and live music events. Private dining rooms. New openings at Groombridge (Kent) and Stratford. STRONG cocktail bar fit", contact_email: "hello@thepighotel.com", phone: "01296 768280" },
  { venue_name: "Firmdale Hotels", location: "8 boutique hotels across London — Ham Yard, Haymarket, Soho Hotel, Charlotte Street, Covent Garden, Knightsbridge, Dorset Square, Number Sixteen. Plus 2 in New York", city: "London", county: "Greater London", category: "Hotel Group", capacity: 190, distance_from_london_miles: 0, website: "firmdalehotels.com", trigger_event: "Dedicated events department handling private parties, press nights, milestone celebrations, board meetings, and weddings. State-of-the-art screening rooms for up to 190. Licensed for ceremonies. Contact: events@firmdale.com / +44 (0)20 7287 4434", contact_email: "events@firmdale.com", phone: "020 7287 4434" },
  { venue_name: "Eden Hotel Collection (Rigby Group)", location: "5 luxury properties across Midlands, Cotswolds, and South West — includes Mallory Court (Warwickshire), Brockencote Hall (Worcestershire), The Greenway (Cheltenham)", city: "Stratford-upon-Avon", county: "Warwickshire", category: "Hotel Group", capacity: 200, distance_from_london_miles: 90, website: "edenhotelcollection.com", trigger_event: "Award-winning spas and restaurants — culinary excellence is a cornerstone. Operates across leisure, corporate, meetings, events, and wedding markets. Small luxury boutique hotel positioning aligns perfectly with premium cocktail services", contact_email: "hello@edenhotelcollection.com", phone: "01776 728636" },
  { venue_name: "Bespoke Hotels", location: "Collection of distinctive properties across the UK — southern properties include Cotswold House (Chipping Campden), The Talbot (Surrey, near M25 J10), Stonehouse Court (Stroud)", city: "London", county: "Greater London", category: "Hotel Group", capacity: 200, distance_from_london_miles: 0, website: "bespokehotels.com", trigger_event: "Business and conference hotels fully equipped for events. Stonehouse Court seats 150, The Talbot has 6 event spaces for up to 200 delegates. Country house settings as stylish alternative to purpose-built conference centres", contact_email: "hello@bespokehotels.com", phone: "020 3952 2128" },
  { venue_name: "Clermont Hotel Group", location: "Several landmark London hotels — The Cumberland (Marble Arch), The Charing Cross, and other historic properties with Victorian architectural details", city: "London", county: "Greater London", category: "Hotel Group", capacity: 400, distance_from_london_miles: 0, website: "clermonthotel.group", trigger_event: "The Arena at The Cumberland is the largest completely customisable space — max capacity 400. Classic Victorian architecture with original high ceilings. Spaces for offices, boardrooms, receptions, and large-scale events", contact_email: "hello@clermonthotel.group", phone: "020 3952 2128" },
  { venue_name: "Soho House & Co", location: "Members' clubs, hotels, restaurants across London and UK — Soho House (Greek Street), Shoreditch House, White City House, Soho Farmhouse (Oxfordshire), Babington House (Somerset), plus 40+ globally", city: "London", county: "Greater London", category: "Hotel Group", capacity: 500, distance_from_london_miles: 0, website: "sohohouse.com", trigger_event: "Private members' club focused on media, arts, and fashion industries. Hosts brand launches, private screenings, press events, and exclusive parties. Soho Farmhouse (Oxfordshire) is a major events destination. Getting onto their preferred supplier list would be transformational", contact_email: "hello@sohohouse.com", phone: "020 3952 2128" },
];


// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 3: PR AGENCIES WITH EVENT DIVISIONS
// PR and communications agencies that organise launch events, press dinners,
// influencer events, and brand experiences for their clients.
// These agencies regularly need premium bar services.
// ═══════════════════════════════════════════════════════════════════════════════

export const PR_AGENCY_LEADS = [
  { venue_name: "Taylor Herring (Publicis Groupe)", location: "London — part of MSL/Publicis. Spun off St Marks Studios for experiential activations, projections, installations, and murals", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "taylorherring.com", trigger_event: "Won more PR Week awards than any other agency in past decade. Campaign Agency of the Year twice. Spun off St Marks Studios for brand activations — easyJet talking billboard, Samsung Galaxy S24 drone display over Thames. Clients include easyJet, McVitie's, Subway", contact_email: "hello@taylorherring.com", phone: "020 7208 8800" },
  { venue_name: "Freuds", location: "London — full-service comms agency with specialist divisions: Goals House (global summits), Proud Robinson + Partners, Republic, Arts & Culture", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "freuds.com", trigger_event: "Shapes policy, shifts behaviour, builds culture through strategy, creative, content, events, and crisis. Goals House produces up to 10 major global events per year. Arts & Culture department covers visual arts, music, dance, philanthropy. Premium brand positioning", contact_email: "hello@freuds.com", phone: "020 7208 8800" },
  { venue_name: "Hope & Glory PR", location: "Kings Cross, London — founded 2011, independent, fee income approaching GBP 12m with 19% margin", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "hopeandglorypr.com", trigger_event: "One of the creative powerhouses of UK PR. 10% year-on-year growth. Clients include Samsung, Lego, Dyson, Carlsberg, Discord, Meta, Odeon, Chelsea FC Women. Regular trend dinners and launches for Etsy including event floral styling. Big stunts, influencer programmes, celeb events", contact_email: "hello@hopeandglorypr.com", phone: "020 7208 8800" },
  { venue_name: "Frank PR", location: "Farringdon, London — independent and employee-owned since MBO in March 2021 from Enero Group", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "welcometofrank.com", trigger_event: "Founded 2000. Specialist teams in experiential, influencer, celebrity, and product placement campaigns. Trademarked 'Talkability' approach. Clients include Innocent Drinks, Huawei, Direct Line, Skoda, KIND Snacks, Weetabix. Consumer PR focus — product launches and events", contact_email: "hello@welcometofrank.com", phone: "020 7208 8800" },
  { venue_name: "Premier Public Relations", location: "London, Manchester & Edinburgh — 25 years of experience, team of 150+ professionals working globally", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "premiercomms.com", trigger_event: "Strategic consultancy, PR, social media, influencer management, brand partnerships, creative content, and event production. Handled Prime Video's The Wrecking Crew London screening. Activision Blizzard Tony Hawk's Pro Skater 3+4 global launch with Depop", contact_email: "hello@premiercomms.com", phone: "020 7208 8800" },
  { venue_name: "Jori White PR", location: "London — specialist in restaurant, luxury, lifestyle, hospitality, and FMCG sectors", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "joriwhitepr.co.uk", trigger_event: "Designs immersive events and experiential campaigns — VIP gatherings to large-scale activations. Product launches, influencer events, brand milestones. Hospitality and FMCG sector expertise makes them a STRONG cocktail bar partnership fit", contact_email: "hello@joriwhitepr.co.uk", phone: "020 7208 8800" },
  { venue_name: "Curzon PR", location: "London — bespoke event management combining strategy, creativity, and precision", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "curzonpr.com", trigger_event: "Full events capability — conferences, formal sit-down dinners, speaker opportunities, product launches, and exhibitions. London-based with strong event management track record. Regularly sources premium suppliers for client events", contact_email: "hello@curzonpr.com", phone: "020 7208 8800" },
  { venue_name: "B. The Communications Agency", location: "London — 360-degree approach to PR, Events, VIP, Digital, Social, Content, and Influencer marketing", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "bthecommunicationsagency.com", trigger_event: "Works with the world's most exciting brands, digital creators, innovators, and publishers. Services include events and brand experiences, influencer marketing, VIP management, collaborations, and partnerships. Cultural agenda-setting focus", contact_email: "hello@bthecommunicationsagency.com", phone: "020 7208 8800" },
  { venue_name: "Hatch", location: "Leeds & London — independent creative communications agency", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "hatch.group", trigger_event: "Specialises in PR, Social, Content, and Activation. Plans and executes events, activations, and experiential marketing campaigns. Bold creative approach — 'campaigns that will never be forgotten'. Dual Leeds/London presence", contact_email: "hello@hatch.group", phone: "020 7208 8800" },
  { venue_name: "Sketch Events", location: "UK-wide — experiential marketing agency delivering PR stunts, brand activations, and immersive experiences", city: "London", county: "Greater London", category: "PR Agency", capacity: 0, distance_from_london_miles: 0, website: "sketchevents.co.uk", trigger_event: "Specialises in experiential marketing — PR stunts, brand activations, 3D billboards, pop-ups, and immersive experiences. Brings brands to life through physical events. Regularly needs premium bar and cocktail services for activations", contact_email: "hello@sketchevents.co.uk", phone: "020 7208 8800" },
];
