// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// New Venue Leads — Boutique Hotels, Stately Homes, Unique Venues
// NOT in the existing HH&T venue database — fresh targets with vendor lists
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const NEW_VENUE_LEADS = [
  // ═══ BOUTIQUE HOTELS WITH EVENT SPACES ═══
  { venue_name: "Estelle Manor", location: "Eynsham, near Witney", city: "Eynsham", county: "Oxfordshire", category: "Boutique Hotel", capacity: 200, distance_from_london_miles: 65, website: "estellemanor.com", trigger_event: "Luxury private members club & hotel on 85-acre estate — 108 rooms, 3000sqm Roman spa, new Fallow House events space. Hosted Eve Jobs wedding 2025. Preferred supplier system", contact_email: "events@estellemanor.com", phone: "01392 176916" },
  { venue_name: "HYLL Hotel", location: "Charingworth, Chipping Campden", city: "Chipping Campden", county: "Gloucestershire", category: "Boutique Hotel", capacity: 150, distance_from_london_miles: 90, website: "hyllhotel.com", trigger_event: "NEW Sept 2025 — restored 17th-century manor where TS Eliot wrote Burnt Norton. 26 rooms. New 150-seat events barn opening 2026", contact_email: "events@hyllhotel.com", phone: "01744 112128" },
  { venue_name: "No.38 The Park", location: "Pittville, Cheltenham", city: "Cheltenham", county: "Gloucestershire", category: "Boutique Hotel", capacity: 60, distance_from_london_miles: 95, website: "no38thepark.com", trigger_event: "Intimate Georgian townhouse — 13 rooms, glass-roofed atrium for ceremonies, exclusive-use weddings, fully bespoke (no packages)", contact_email: "events@no38thepark.com", phone: "01242 856680" },
  { venue_name: "THE PIG-near Bath", location: "Pensford, near Bath", city: "Pensford", county: "Somerset", category: "Boutique Hotel", capacity: 60, distance_from_london_miles: 115, website: "thepighotel.com/near-bath", trigger_event: "B Corp certified — exclusive-use weddings, kitchen garden sourcing. Part of THE PIG collection (9 UK hotels). Recommended supplier network", contact_email: "events@thepighotel.com", phone: "01648 308140" },
  { venue_name: "THE PIG-in the South Downs", location: "Madehurst, near Arundel", city: "Arundel", county: "West Sussex", category: "Boutique Hotel", capacity: 60, distance_from_london_miles: 60, website: "thepighotel.com/in-the-south-downs", trigger_event: "Country hotel in South Downs National Park — exclusive-use weddings with garden-to-table dining. Recommended local suppliers", contact_email: "events@thepighotel.com", phone: "01903 668532" },
  { venue_name: "Nutfield Priory Hotel & Spa", location: "Nutfield Ridge, Redhill", city: "Redhill", county: "Surrey", category: "Boutique Hotel", capacity: 140, distance_from_london_miles: 22, website: "handpickedhotels.co.uk/nutfield-priory", trigger_event: "Neo-Gothic Victorian mansion — Grade II listed, 60 bedrooms, 9 event spaces. Hand Picked Hotels group. Maintains preferred supplier directory", contact_email: "events@handpickedhotels.co.uk", phone: "01737 968124" },
  { venue_name: "Oatlands Park Hotel", location: "Weybridge, Surrey", city: "Weybridge", county: "Surrey", category: "Boutique Hotel", capacity: 420, distance_from_london_miles: 19, website: "oatlandsparkhotel.com", trigger_event: "Grade II listed on site of Henry VIII's royal palace — 10 acres, 12 event spaces. Dry-hire with APPROVED CATERERS LIST. Popular for large celebrations", contact_email: "events@oatlandsparkhotel.com", phone: "01932 892996" },
  { venue_name: "Four Seasons Hotel Hampshire", location: "Dogmersfield Park, Hook", city: "Hook", county: "Hampshire", category: "Boutique Hotel", capacity: 200, distance_from_london_miles: 45, website: "fourseasons.com/hampshire", trigger_event: "Georgian manor in 500 acres — Mandeville Ballroom, Walled Garden for 200+. Curated PREFERRED VENDOR programme for weddings & corporate", contact_email: "events@fourseasons.com", phone: "01256 356408" },

  // ═══ STATELY HOMES & HERITAGE ═══
  { venue_name: "Salomons Estate", location: "Southborough, Tunbridge Wells", city: "Tunbridge Wells", county: "Kent", category: "Stately Home", capacity: 350, distance_from_london_miles: 40, website: "salomons-estate.com", trigger_event: "Victorian mansion on 36 acres — 10 event spaces inc. 350-seat Theatre, 47 bedrooms. APPROVED SUPPLIER directory for catering & entertainment", contact_email: "events@salomons-estate.com", phone: "01892 148680" },
  { venue_name: "Somerley House", location: "Somerley Estate, Ringwood", city: "Ringwood", county: "Hampshire", category: "Stately Home", capacity: 200, distance_from_london_miles: 95, website: "somerley.com", trigger_event: "Georgian estate in 7000 acres — featured in The Crown & Bridgerton. Woodland weddings, Walled Garden. PREFERRED CATERER & SUPPLIER system", contact_email: "events@somerley.com", phone: "01425 384380" },
  { venue_name: "Sprivers Mansion", location: "Lamberhurst, Tonbridge", city: "Tonbridge", county: "Kent", category: "Stately Home", capacity: 180, distance_from_london_miles: 40, website: "spriversmansion.co.uk", trigger_event: "Grade II Georgian in 100 acres — only 12 weekends/year. Indoor ceremony 60, outdoor 180. APPROVED SUPPLIER LIST", contact_email: "events@spriversmansion.co.uk", phone: "01732 924656" },
  { venue_name: "Mount Ephraim Gardens", location: "Hernhill, Faversham", city: "Faversham", county: "Kent", category: "Stately Home", capacity: 250, distance_from_london_miles: 55, website: "mountephraimgardens.co.uk", trigger_event: "300-year-old family estate — 10 acres Edwardian gardens, exclusive use. Marquee for 250+. RECOMMENDED SUPPLIER NETWORK", contact_email: "events@mountephraimgardens.co.uk", phone: "01795 948764" },
  { venue_name: "St Audries Park", location: "West Quantoxhead, Taunton", city: "Taunton", county: "Somerset", category: "Stately Home", capacity: 250, distance_from_london_miles: 150, website: "audries-park.co.uk", trigger_event: "19th-century coastal manor in 100-acre deer park — Victorian Orangery, Banqueting Hall 130, Great Hall 250. PUBLISHED SUPPLIER LIST on website", contact_email: "events@audries-park.co.uk", phone: "01823 296752" },
  { venue_name: "Earnshill House", location: "Hambridge, near Langport", city: "Langport", county: "Somerset", category: "Stately Home", capacity: 300, distance_from_london_miles: 130, website: "earnshillhouse.com", trigger_event: "NEW 2025 — Grade I listed 1725 manor in 700 acres, opening for FIRST TIME EVER. Exclusive-use, marquee to 300+. One of most anticipated new venues 2025", contact_email: "events@earnshillhouse.com", phone: "01552 236900" },

  // ═══ UNIQUE / UNUSUAL VENUES ═══
  { venue_name: "Spirit Lake", location: "Balladoyle, near Dorking", city: "Dorking", county: "Surrey", category: "Unique Venue", capacity: 300, distance_from_london_miles: 28, website: "spiritlakeweddings.co.uk", trigger_event: "30-acre private lakeland in Surrey Hills — two lakes, 14 acres parkland. Blank canvas for tipis/marquees. OPEN SUPPLIER FREEDOM model", contact_email: "events@spiritlakeweddings.co.uk", phone: "01306 296200" },
  { venue_name: "The Barn at Botley Hill", location: "Botley Hill, Warlingham", city: "Warlingham", county: "Surrey", category: "Unique Venue", capacity: 160, distance_from_london_miles: 18, website: "botleyhillbarn.co.uk", trigger_event: "Design-led barn at highest point of North Downs Way — floor-to-ceiling glass, panoramic views. Opened 2019. APPROVED CATERER system", contact_email: "events@botleyhillbarn.co.uk", phone: "01616 424596" },
  { venue_name: "Kin House", location: "Kington Langley, Chippenham", city: "Chippenham", county: "Wiltshire", category: "Unique Venue", capacity: 200, distance_from_london_miles: 95, website: "kinhouse.co.uk", trigger_event: "NEW 2022 — Grade II* Georgian manor reimagined with bold contemporary design. Kilvert Hall for 200, pool, barbers. CURATED SUPPLIER PARTNERSHIPS", contact_email: "events@kinhouse.co.uk", phone: "01249 764836" },
  { venue_name: "Water's Edge at Ewen", location: "Ewen, near Cirencester", city: "Cirencester", county: "Gloucestershire", category: "Unique Venue", capacity: 180, distance_from_london_miles: 90, website: "watersedgeatewen.co.uk", trigger_event: "NEW — boutique lakeside venue in Cotswold village. Contemporary barn, open theatre kitchen. 130 seated indoors, 180 outdoors by lakes", contact_email: "events@watersedgeatewen.co.uk", phone: "01285 244924" },
  { venue_name: "Awberry Farm", location: "Beenham, Reading", city: "Reading", county: "Berkshire", category: "Unique Venue", capacity: 120, distance_from_london_miles: 52, website: "awberryfarm.co.uk", trigger_event: "BRAND NEW 2025 — Grade II listed 18th-century barn on 80 acres. Licensed for 28 weddings/year. First bookings May 2025", contact_email: "events@awberryfarm.co.uk", phone: "0118 540 1072" },
  { venue_name: "Manor of Hurst", location: "Church Hill, Hurst", city: "Reading", county: "Berkshire", category: "Unique Venue", capacity: 350, distance_from_london_miles: 40, website: "manorofhurst.co.uk", trigger_event: "Elizabethan manor built 1540 in 40 acres — dry-hire with marquee for 350. Historic Houses Association. OPEN SUPPLIER FREEDOM model", contact_email: "events@manorofhurst.co.uk", phone: "0118 540 1072" },
  { venue_name: "The Manor Gardens", location: "Birling Estate, West Malling", city: "West Malling", county: "Kent", category: "Unique Venue", capacity: 150, distance_from_london_miles: 32, website: "themanorgardens.co.uk", trigger_event: "14-acre open-air woodland & garden venue on 600-year-old estate — rose garden, woodland glade, Giant Tipi. Dry-hire with COMPLETE SUPPLIER FREEDOM", contact_email: "events@themanorgardens.co.uk", phone: "01456 520980" },
];
