// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Sports Venues, Charity Event Organisers, Entertainment & Team Building Leads
// Partnership targets for HH&T premium mobile cocktail bar services
// All within 150 miles of London — Southern England, Home Counties, Midlands fringe
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const SPORT_CHARITY_ENTERTAINMENT_LEADS = [

  // ═══════════════════════════════════════════════════════
  // CATEGORY 1: RACECOURSES & SPORTS VENUES (12)
  // Racecourses, cricket grounds, rugby clubs, polo clubs
  // These venues host corporate hospitality, summer parties,
  // and social events requiring premium bar services
  // ═══════════════════════════════════════════════════════

  // --- RACECOURSES ---
  { venue_name: "Sandown Park Racecourse", location: "Portsmouth Road, Esher, Surrey", city: "Esher", county: "Surrey", category: "Racecourse", capacity: 20000, distance_from_london_miles: 15, website: "thejockeyclub.co.uk/sandown", trigger_event: "Premier Surrey racecourse — Gold Cup in April, Eclipse Festival in July. Private boxes, Equus restaurant, corporate suites. Just 25 mins from Waterloo. Also hosts conferences and non-race-day events", contact_email: "", phone: "" },
  { venue_name: "Epsom Downs Racecourse", location: "Epsom Downs, Surrey", city: "Epsom", county: "Surrey", category: "Racecourse", capacity: 50000, distance_from_london_miles: 15, website: "thejockeyclub.co.uk/epsom", trigger_event: "Home of the Derby — the world's greatest flat race. Derby Day and Ladies' Day draw massive corporate hospitality crowds. Private boxes, fine dining, and marquee hospitality in June", contact_email: "", phone: "" },
  { venue_name: "Ascot Racecourse", location: "High Street, Ascot, Berkshire", city: "Ascot", county: "Berkshire", category: "Racecourse", capacity: 70000, distance_from_london_miles: 25, website: "ascot.com", trigger_event: "Royal Ascot in June is the pinnacle of British horse racing hospitality — five days of premium corporate entertaining, private boxes, fine dining. Also hosts Champions Day in October", contact_email: "", phone: "" },
  { venue_name: "Lingfield Park Racecourse", location: "Racecourse Road, Lingfield, Surrey", city: "Lingfield", county: "Surrey", category: "Racecourse", capacity: 5000, distance_from_london_miles: 28, website: "lingfieldpark.co.uk", trigger_event: "One of Europe's busiest racecourses — 90+ meetings per year across Flat, National Hunt and All-Weather. Grandstand suites for 8-120 guests, Ladies Day in May, Ladies Night in July", contact_email: "", phone: "" },
  { venue_name: "Fontwell Park Racecourse", location: "Arundel, West Sussex", city: "Arundel", county: "West Sussex", category: "Racecourse", capacity: 5000, distance_from_london_miles: 55, website: "fontwellpark.co.uk", trigger_event: "National Hunt course with 12 private boxes (12-20 guests each), Corner Suite for 24-100, and marquee hospitality. Friendly atmosphere for corporate days and private celebrations", contact_email: "", phone: "" },
  { venue_name: "Brighton Racecourse", location: "Freshfield Road, Brighton", city: "Brighton", county: "East Sussex", category: "Racecourse", capacity: 5000, distance_from_london_miles: 53, website: "brighton-racecourse.co.uk", trigger_event: "Stunning clifftop course — summer flat racing from May to October. Stylish marquee hospitality and restaurant dining with panoramic sea views. Corporate and private hire available", contact_email: "", phone: "" },

  // --- CRICKET GROUNDS ---
  { venue_name: "The Kia Oval", location: "Kennington, London", city: "London", county: "Greater London", category: "Cricket Ground", capacity: 25500, distance_from_london_miles: 2, website: "kiaoval.com", trigger_event: "Surrey CCC home — hosts Ashes Tests, ODIs and The Hundred. Premium hospitality suites, The Green Room, and private boxes. Also a major non-cricket event venue for conferences and corporate dinners year-round", contact_email: "", phone: "" },
  { venue_name: "Utilita Bowl (Rose Bowl)", location: "Botley Road, West End, Hampshire", city: "Southampton", county: "Hampshire", category: "Cricket Ground", capacity: 25000, distance_from_london_miles: 75, website: "utilitabowl.com", trigger_event: "Hampshire CCC home — international cricket, Vitality Blast, concerts. Beefy's by Lord Botham hospitality, private boxes, and shared suites. Full 2026 season April-September. Also hosts non-cricket events and conferences", contact_email: "", phone: "" },

  // --- POLO CLUBS ---
  { venue_name: "Guards Polo Club", location: "Smith's Lawn, Windsor Great Park", city: "Windsor", county: "Berkshire", category: "Polo Club", capacity: 5000, distance_from_london_miles: 22, website: "guardspoloclub.com", trigger_event: "World-class polo with Searcys hospitality by Richard Corrigan. Royal Box packages, Members Clubhouse, and ticketed events. Cartier Queen's Cup and Gold Cup. Peak season May-July — ideal for premium cocktail reception services", contact_email: "", phone: "" },
  { venue_name: "Cowdray Park Polo Club", location: "Cowdray Park, Midhurst, West Sussex", city: "Midhurst", county: "West Sussex", category: "Polo Club", capacity: 3000, distance_from_london_miles: 50, website: "cowdraypolo.co.uk", trigger_event: "Home of British Polo — Gold Cup is the premier European polo tournament. Private pagodas, exclusive enclosures, and luxury hospitality at semi-finals and final. Summer season draws ultra-premium corporate crowd", contact_email: "", phone: "" },
  { venue_name: "Hurtwood Park Polo Club", location: "Ewhurst, Cranleigh, Surrey", city: "Cranleigh", county: "Surrey", category: "Polo Club", capacity: 2000, distance_from_london_miles: 35, website: "hurtwoodparkpolo.co.uk", trigger_event: "Only UK polo club offering year-round social and leisure facilities. 180 acres of Surrey countryside — polo, events, weddings, and corporate hospitality. Easy reach from London", contact_email: "", phone: "" },

  // --- RUGBY ---
  { venue_name: "Northampton Saints (Franklin's Gardens)", location: "Weedon Road, Northampton", city: "Northampton", county: "Northamptonshire", category: "Rugby Club", capacity: 15000, distance_from_london_miles: 65, website: "northamptonsaints.co.uk", trigger_event: "Premiership rugby — premium hospitality with locally sourced three-course meals, player Q&As, and exclusive Tunnel Club. Matchday packages and non-matchday venue hire for corporate events and celebrations", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // CATEGORY 2: CHARITY EVENT ORGANISERS (10)
  // Established charities and event companies organising
  // annual galas, fundraising dinners, balls, and auctions
  // Premium events that feature cocktail receptions
  // ═══════════════════════════════════════════════════════

  { venue_name: "Skyline Events", location: "London-based, operates UK-wide", city: "London", county: "Greater London", category: "Charity Events", capacity: 1000, distance_from_london_miles: 0, website: "skylineevents.co.uk", trigger_event: "UK's leading charity fundraising event specialist — 26 years experience, worked with 3,000+ charities, raised over £115 million. Organises gala dinners, balls, and auctions that regularly feature cocktail receptions", contact_email: "", phone: "" },
  { venue_name: "Chance Organisation", location: "Chelsea, Mayfair, Kensington", city: "London", county: "Greater London", category: "Charity Events", capacity: 500, distance_from_london_miles: 0, website: "chanceorganisation.co.uk", trigger_event: "Premium charity event planners in Chelsea/Mayfair — supports Battersea Dogs, Help for Heroes, Addenbrooke's. Plans gala dinners and concerts with celebrity entertainment. Strong contacts for premium venues and catering", contact_email: "", phone: "" },
  { venue_name: "Saving Grace Events", location: "London and South East", city: "London", county: "Greater London", category: "Charity Events", capacity: 500, distance_from_london_miles: 0, website: "savinggraceevents.co.uk", trigger_event: "Specialist charity event management — nearly a decade of gala dinners, family fun days, and bespoke fundraisers. Strategic partners who align events with charitable missions. Cocktail receptions a core element", contact_email: "", phone: "" },
  { venue_name: "Julia Charles Event Management", location: "London-based, operates nationally", city: "London", county: "Greater London", category: "Charity Events", capacity: 500, distance_from_london_miles: 0, website: "juliacharleseventmanagement.co.uk", trigger_event: "Bespoke charity gala specialists — full event production from concept to completion. Venue finding, supplier sourcing, entertainment, auctions. Works with major London venues including The Savoy and Grosvenor House", contact_email: "", phone: "" },
  { venue_name: "ConnectIn Events", location: "London and UK-wide", city: "London", county: "Greater London", category: "Charity Events", capacity: 800, distance_from_london_miles: 0, website: "connectinevents.co.uk", trigger_event: "Established charity events company — expert at engaging guests and driving donations. Manages full event lifecycle from budget planning to on-the-night coordination. Cocktail receptions and premium bar services integral to their events", contact_email: "", phone: "" },
  { venue_name: "Peri Peri Events", location: "London, operates UK and internationally", city: "London", county: "Greater London", category: "Charity Events", capacity: 1000, distance_from_london_miles: 0, website: "periperi.co.uk", trigger_event: "High-end charity ball production for world-leading charities. Expert in silent auctions, celebrity auctioneers, and branded fundraising elements. Experienced working with tight budgets and sponsor management", contact_email: "", phone: "" },
  { venue_name: "Chain of Hope", location: "London", city: "London", county: "Greater London", category: "Charity Events", capacity: 600, distance_from_london_miles: 0, website: "chainofhope.org", trigger_event: "Annual Gala Ball attracts 500-600 guests including royalty and celebrities. One of London's most prestigious charity balls with premium sponsorship packages. Cocktail reception is a core feature of the evening", contact_email: "", phone: "" },
  { venue_name: "NSPCC Special Events", location: "London and nationwide", city: "London", county: "Greater London", category: "Charity Events", capacity: 500, distance_from_london_miles: 0, website: "nspcc.org.uk", trigger_event: "Major national charity hosting gala dinners, wine challenges, and special fundraising events. Incorporates raffles, silent auctions, and sponsorship opportunities. Premium cocktail receptions at landmark London venues", contact_email: "", phone: "" },
  { venue_name: "Cancer Research UK Events", location: "London and nationwide", city: "London", county: "Greater London", category: "Charity Events", capacity: 1000, distance_from_london_miles: 0, website: "cancerresearchuk.org", trigger_event: "Emeralds & Ivy Ball has raised over £12.8m since 2006. Carol Concert raised £6m+. Major charity balls and gala dinners at premium London venues requiring full bar and cocktail services", contact_email: "", phone: "" },
  { venue_name: "Chill Out! Event Management", location: "London and South East", city: "London", county: "Greater London", category: "Charity Events", capacity: 500, distance_from_london_miles: 0, website: "chill-out.co.uk", trigger_event: "20+ years as full-service live events agency — specialist in themed charity balls and parties. Integrates auctions, online donations, and raffle tickets into events. Long-running partnerships including Battersea Collars & Coats Ball", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // CATEGORY 3: ENTERTAINMENT & TALENT AGENCIES +
  // TEAM BUILDING COMPANIES (10)
  // Companies booking entertainment for events that could
  // cross-refer cocktail bar services, plus team building
  // companies organising corporate socials with drinks
  // ═══════════════════════════════════════════════════════

  // --- ENTERTAINMENT AGENCIES ---
  { venue_name: "Contraband Entertainment", location: "London-based, operates UK and internationally", city: "London", county: "Greater London", category: "Entertainment Agency", capacity: 0, distance_from_london_miles: 0, website: "contrabandevents.com", trigger_event: "Major entertainment and talent booking agency — corporate entertainment and private events in London, UK & internationally. Books bands, DJs, performers for events that regularly need premium bar services. Cross-referral partner opportunity", contact_email: "", phone: "" },
  { venue_name: "Alive Network", location: "UK-wide, HQ in Warwickshire", city: "Warwick", county: "Warwickshire", category: "Entertainment Agency", capacity: 0, distance_from_london_miles: 90, website: "alivenetwork.com", trigger_event: "UK's biggest live entertainment agency — 27 years, 189,000+ events booked, 10,000 events per year. Supplies bands, DJs, entertainers for weddings, corporate events, and parties. Huge cross-referral potential for cocktail bar add-on", contact_email: "", phone: "" },
  { venue_name: "Champions Music & Entertainment", location: "Nationwide, London coverage", city: "London", county: "Greater London", category: "Entertainment Agency", capacity: 0, distance_from_london_miles: 0, website: "musicandbands.co.uk", trigger_event: "Multi-award-winning agency — Booking Agency of the Year 2025. Sunday Times Fast Track 100. Books acts for corporate events, private parties, weddings, festivals. Natural partner for premium cocktail bar cross-referrals", contact_email: "", phone: "" },
  { venue_name: "Function Central", location: "Nationwide including South East", city: "London", county: "Greater London", category: "Entertainment Agency", capacity: 0, distance_from_london_miles: 0, website: "functioncentral.co.uk", trigger_event: "Leading live band and entertainment booking agency — exclusive function bands, musicians, and DJs for weddings, parties, and corporate events across England and Wales. Strong South East and Midlands presence", contact_email: "", phone: "" },
  { venue_name: "Bands For Hire", location: "UK-wide, London-based", city: "London", county: "Greater London", category: "Entertainment Agency", capacity: 0, distance_from_london_miles: 0, website: "bandsforhire.net", trigger_event: "One-stop entertainment agency — party bands, jazz bands, wedding bands, string quartets, DJs. Hand-picked corporate event specialists with extensive experience. Complementary service to mobile cocktail bars", contact_email: "", phone: "" },

  // --- TEAM BUILDING COMPANIES ---
  { venue_name: "Team Tactics", location: "London and UK-wide", city: "London", county: "Greater London", category: "Team Building", capacity: 500, distance_from_london_miles: 0, website: "teamtactics.co.uk", trigger_event: "30+ years creating corporate team building events — their Mobile Cocktail Masterclass led by Master Mixologist is a flagship product. Direct competitor but also referral partner for larger events needing full bar services", contact_email: "", phone: "" },
  { venue_name: "The Team Building Company", location: "Nationwide, operates at venues of choice", city: "London", county: "Greater London", category: "Team Building", capacity: 1000, distance_from_london_miles: 0, website: "teambuilding.co.uk", trigger_event: "Offers cocktail making, casino nights, and creative events for all team sizes. Nation-wide company operating at client-chosen venues. Partnership opportunity — they need bar services for their cocktail events", contact_email: "", phone: "" },
  { venue_name: "Eventurous", location: "London and nationwide", city: "London", county: "Greater London", category: "Team Building", capacity: 1000, distance_from_london_miles: 0, website: "eventurous.co.uk", trigger_event: "Packaged and bespoke corporate team building for groups of 10-1000+. Offers virtual cocktail making among many activities. Partnership opportunity to supply professional bar services for their cocktail-themed events", contact_email: "", phone: "" },
  { venue_name: "GOTO Events", location: "UK-wide delivery", city: "London", county: "Greater London", category: "Team Building", capacity: 500, distance_from_london_miles: 0, website: "gotoevents.co.uk", trigger_event: "Corporate team building specialists — their cocktail challenge is a core product where teams mix and pour competitively. Delivered anywhere in the UK for conference delegates and corporate groups. Natural fit for HH&T bar services", contact_email: "", phone: "" },
  { venue_name: "The Events Company", location: "London and nationwide", city: "London", county: "Greater London", category: "Team Building", capacity: 500, distance_from_london_miles: 0, website: "theeventscompany.co.uk", trigger_event: "Wide range of corporate team building activities including cocktail making, wine tasting, escape rooms. London-focused with national reach. Needs professional bar and cocktail services for their drinks-related events", contact_email: "", phone: "" },
];
