// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Theatres, Retail Destinations, Property Developers & Awards Production Leads
// Four new categories of potential HH&T partnership leads — all within 150mi of London
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 1: THEATRES & PERFORMING ARTS VENUES WITH CORPORATE HIRE (12)
// Regional theatres, concert halls & performing arts venues that hire spaces
// for corporate events, private parties, gala dinners & award ceremonies.
// ═══════════════════════════════════════════════════════════════════════════════

export const THEATRE_CORPORATE_HIRE_LEADS = [
  { venue_name: "Brighton Dome", location: "Church Street, Brighton", city: "Brighton", county: "East Sussex", category: "Theatre & Performing Arts", capacity: 1700, distance_from_london_miles: 53, website: "brightondome.org", trigger_event: "Five unique venues on the Royal Pavilion Estate — Concert Hall (1,700), Corn Exchange (800 reception), Studio Theatre (230), Founders Room (80). Hosts conferences, gala dinners, awards ceremonies & receptions. Major conference destination with full catering & AV", contact_email: "", phone: "" },
  { venue_name: "Mayflower Theatre", location: "Commercial Road, Southampton", city: "Southampton", county: "Hampshire", category: "Theatre & Performing Arts", capacity: 2300, distance_from_london_miles: 79, website: "mayflower.org.uk", trigger_event: "Grade II listed, largest theatre on the South Coast — 2,300-seat auditorium (hire from £7,500), Studio 1 (449 seats), Bar & Cafe (200 reception), Circle Suite (50). Corporate hospitality, private hire, awards ceremonies. In-house events team", contact_email: "", phone: "" },
  { venue_name: "Milton Keynes Theatre", location: "Marlborough Gate, Central MK", city: "Milton Keynes", county: "Buckinghamshire", category: "Theatre & Performing Arts", capacity: 1400, distance_from_london_miles: 50, website: "atgtickets.com/venues/milton-keynes-theatre", trigger_event: "1,400-seat flexible auditorium (ceiling raises 900-1,400), large open foyer for exhibitions, Garden Room, Hennessy Room, Logistics Bar. 11 dressing rooms for breakouts. In-house corporate events team of 25 staff. Corporate membership from £2,500+VAT/yr", contact_email: "", phone: "" },
  { venue_name: "G Live", location: "London Road, Guildford", city: "Guildford", county: "Surrey", category: "Theatre & Performing Arts", capacity: 1031, distance_from_london_miles: 30, website: "trafalgartickets.com/g-live-guildford", trigger_event: "Guildford's premier entertainment & conference venue — Main Hall (1,031 theatre / 420 dinner dance / 800 reception), Bellerby Studio (120 standing), Glass Room with panoramic balcony views. Operated by Trafalgar Entertainment. 30 mins from London Waterloo", contact_email: "", phone: "" },
  { venue_name: "Theatre Royal Brighton", location: "New Road, Brighton", city: "Brighton", county: "East Sussex", category: "Theatre & Performing Arts", capacity: 966, distance_from_london_miles: 53, website: "theatreroyalbrighton.com", trigger_event: "Grade II* listed, one of UK's oldest working theatres (218+ years). 966-seat Regency auditorium across four levels. Charming rooms throughout available for conferences, meetings, corporate hospitality. ATG/Trafalgar venue with Parlour cafe & multi-level bars", contact_email: "", phone: "" },
  { venue_name: "The Marlowe Theatre", location: "The Friars, Canterbury", city: "Canterbury", county: "Kent", category: "Theatre & Performing Arts", capacity: 1200, distance_from_london_miles: 62, website: "marlowetheatre.com", trigger_event: "Kent's major large-scale theatre — 1,200-seat auditorium with balconies & flytower, plus The Studio (150 seats) available for hire. Three-level foyer with hospitality outlets. Hosts RSC, National Theatre, Glyndebourne. Historic cathedral city location", contact_email: "", phone: "" },
  { venue_name: "Norwich Theatre Royal", location: "Theatre Street, Norwich", city: "Norwich", county: "Norfolk", category: "Theatre & Performing Arts", capacity: 1300, distance_from_london_miles: 115, website: "norwichtheatre.org", trigger_event: "Grand 1,300-seat venue, one of UK's oldest theatres (founded 1758). Refurbished front-of-house with range of private event spaces. Corporate events, backstage tours, private hire. Contact: corporate@norwichtheatre.org / 01603 598556", contact_email: "corporate@norwichtheatre.org", phone: "01603 598556" },
  { venue_name: "Oxford Playhouse", location: "Beaumont Street, Oxford", city: "Oxford", county: "Oxfordshire", category: "Theatre & Performing Arts", capacity: 630, distance_from_london_miles: 56, website: "oxfordplayhouse.com", trigger_event: "630-seat Main Stage Auditorium over two levels (recently refurbished), W Lucy Members Room (Georgian drawing room for board meetings), Top Room (50 theatre-style with AV). Full in-house catering. Heart of Oxford location. Spaces hire 9am-10pm", contact_email: "", phone: "" },
  { venue_name: "Wycombe Swan Theatre", location: "St Mary Street, High Wycombe", city: "High Wycombe", county: "Buckinghamshire", category: "Theatre & Performing Arts", capacity: 1070, distance_from_london_miles: 29, website: "trafalgartickets.com/wycombe-swan-theatre", trigger_event: "Main auditorium (1,070), Old Town Hall (600 — 120-year history), Oak Room (120 — oak panelling & stained glass). Conferences, awards ceremonies, dinner dances. Day Delegate Package £32pp. In-house technicians & licensed bars. 3 mins from train station", contact_email: "", phone: "" },
  { venue_name: "Royal & Derngate", location: "Guildhall Road, Northampton", city: "Northampton", county: "Northamptonshire", category: "Theatre & Performing Arts", capacity: 1500, distance_from_london_miles: 67, website: "royalandderngate.co.uk", trigger_event: "Three venues in one — Derngate (1,198 seats / 1,500 in-the-round), Royal (450 seats), Underground. Multi-purpose: concerts, gala dinners, product launches, awards ceremonies. Green Room (30 seated / 40 standing) for corporate use with AV", contact_email: "", phone: "" },
  { venue_name: "Cliffs Pavilion", location: "Station Road, Westcliff-on-Sea", city: "Southend-on-Sea", county: "Essex", category: "Theatre & Performing Arts", capacity: 1630, distance_from_london_miles: 40, website: "trafalgartickets.com/cliffs-pavilion-southend", trigger_event: "Largest purpose-built arts venue in Essex — auditorium (1,630 conference / 600 gala dinner), Maritime Room (300 with patio overlooking estuary), Admirals Room for intimate events. In-house chefs with locally sourced menus. Sales team: 01702 344553", contact_email: "", phone: "01702 344553" },
  { venue_name: "The Hawth", location: "Hawth Avenue, Crawley", city: "Crawley", county: "West Sussex", category: "Theatre & Performing Arts", capacity: 855, distance_from_london_miles: 28, website: "parkwoodtheatres.co.uk/the-hawth", trigger_event: "Theatre (855 seats), Studio (146), function room (100), 7 meeting rooms on 38-acre wooded site. Conferences, product launches, exhibitions, corporate events. Free parking for 250 cars. 4 miles from Gatwick Airport. Contact: 01293 859945", contact_email: "louise.street@parkwoodtheatres.co.uk", phone: "01293 859945" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 2: SHOPPING CENTRES & RETAIL DESTINATIONS WITH EVENT SPACES (10)
// Large shopping centres, outlet villages & retail destinations that host
// product launches, seasonal markets, VIP evenings & brand activations.
// ═══════════════════════════════════════════════════════════════════════════════

export const SHOPPING_CENTRE_EVENT_LEADS = [
  { venue_name: "Bluewater", location: "Greenhithe, Dartford", city: "Greenhithe", county: "Kent", category: "Shopping Centre & Retail", capacity: 5000, distance_from_london_miles: 19, website: "bluewater.co.uk", trigger_event: "UK top 3 retail destination on 240 acres — 330 brands, 50 eateries. 327k weekly footfall, 86% ABC1. Landsec Platform+ (plug-and-play white box), Spotlight (flexible activations to full takeovers). Product launches, VIP shopping events, seasonal markets. Owned by Landsec", contact_email: "", phone: "" },
  { venue_name: "Lakeside Shopping Centre", location: "West Thurrock, Grays", city: "Thurrock", county: "Essex", category: "Shopping Centre & Retail", capacity: 5000, distance_from_london_miles: 20, website: "lakeside-shopping.com", trigger_event: "500k weekly footfall, 250+ stores, £100m+ invested by brand partners in 3 years. The Quay Event Space from £2,000/day — experiential marketing, brand activations, pop-ups. Major seasonal campaigns (Easter, Halloween, Christmas). 25+ brands committed for 2026", contact_email: "", phone: "" },
  { venue_name: "The Oracle", location: "Broad Street, Reading", city: "Reading", county: "Berkshire", category: "Shopping Centre & Retail", capacity: 3000, distance_from_london_miles: 36, website: "theoracle.com", trigger_event: "16 million annual visitors, 82% ABC1, 80+ stores plus riverside dining. Three brand activation spaces (inside & riverside). Owned by Hammerson. Regular pop-ups, fashion events, tech promotions. Contact: brandpartnerships@hammerson.com or specialityleasing@hammerson.com", contact_email: "brandpartnerships@hammerson.com", phone: "" },
  { venue_name: "Meadowhall Centre", location: "Meadowhall Way, Sheffield", city: "Sheffield", county: "South Yorkshire", category: "Shopping Centre & Retail", capacity: 5000, distance_from_london_miles: 145, website: "meadowhall.co.uk", trigger_event: "Yorkshire's largest shopping centre, 11th largest UK — 460k weekly footfall, £127 avg spend, 290 stores. Ground floor Park Lane zone for premium brand activations. Owned by British Land. £47m brand investment 2024-25. Contact: Nicola Thompson, Commercialisation Manager", contact_email: "", phone: "" },
  { venue_name: "McArthurGlen Ashford Designer Outlet", location: "Kimberley Way, Ashford", city: "Ashford", county: "Kent", category: "Shopping Centre & Retail", capacity: 2000, distance_from_london_miles: 56, website: "mcarthurglen.com/en/outlets/uk/designer-outlet-ashford", trigger_event: "90+ designer brands at up to 60% off. £90m extension in 2019 added 50 new stores, dedicated events space, food piazza. Europe's largest living green wall. Richard Rogers-designed architecture. Free parking after 5pm. 5-min walk from Ashford International station", contact_email: "", phone: "" },
  { venue_name: "Gunwharf Quays", location: "Portsmouth Harbour", city: "Portsmouth", county: "Hampshire", category: "Shopping Centre & Retail", capacity: 3000, distance_from_london_miles: 74, website: "gunwharf-quays.com", trigger_event: "Waterfront outlet destination — 143k visitors/week, £65 avg spend. Landsec Spotlight flexible activation spaces. Multi-million pound investment underway. Venue hire within Quays (Alchemist 300 capacity, Aspex gallery, Old Customs House). Dog-friendly, harbour views", contact_email: "", phone: "" },
  { venue_name: "Braintree Village", location: "Chapel Hill, Braintree", city: "Braintree", county: "Essex", category: "Shopping Centre & Retail", capacity: 1500, distance_from_london_miles: 47, website: "braintree-village.com", trigger_event: "Premium outlet village — 80+ aspirational brands (Armani, Ralph Lauren, BOSS, Kate Spade). Landsec Spotlight activation spaces, mid-mall kiosks. Annual events: Christmas ice rink, open-air cinema, VIP weekends, flash sales. Free parking 1,660 spaces. Direct train from Liverpool Street", contact_email: "leasing@landsec.com", phone: "" },
  { venue_name: "Whiteley Shopping Centre", location: "Whiteley Way, Fareham", city: "Fareham", county: "Hampshire", category: "Shopping Centre & Retail", capacity: 1500, distance_from_london_miles: 72, website: "whiteleyshopping.co.uk", trigger_event: "Open-air shopping centre between Portsmouth & Southampton — 70+ stores, restaurants, 9-screen cinema. Hosts artisan markets, farmers markets, seasonal events. 1,300+ parking spaces (4hrs free). Off Junction 9 M27. Growing events programme", contact_email: "", phone: "" },
  { venue_name: "Bicester Village", location: "50 Pingle Drive, Bicester", city: "Bicester", county: "Oxfordshire", category: "Shopping Centre & Retail", capacity: 2000, distance_from_london_miles: 52, website: "bicestervillage.com", trigger_event: "World-famous luxury outlet — 160+ boutiques (Gucci, Prada, Dior, Burberry). 7 million visitors/year, high-net-worth international clientele. VIP shopping experiences, seasonal events, brand launch pop-ups. Part of The Bicester Collection (Value Retail). Direct rail from London Marylebone", contact_email: "", phone: "" },
  { venue_name: "Westgate Oxford", location: "Queen Street, Oxford", city: "Oxford", county: "Oxfordshire", category: "Shopping Centre & Retail", capacity: 2000, distance_from_london_miles: 56, website: "westgateoxford.co.uk", trigger_event: "Opened 2017, £440m development — 100+ stores, 25+ restaurants, rooftop terrace with panoramic views. Landsec-owned. Event spaces for brand activations, pop-ups, seasonal campaigns. Student & tourist footfall from one of world's most famous university cities", contact_email: "", phone: "" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 3: PROPERTY DEVELOPERS & SHOW HOME LAUNCH COMPANIES (10)
// Housebuilders, property developers & property marketing agencies that host
// show home launches, development openings, investor events & cocktail receptions.
// ═══════════════════════════════════════════════════════════════════════════════

export const PROPERTY_DEVELOPER_LEADS = [
  { venue_name: "Berkeley Group", location: "Berkeley House, Cobham", city: "Cobham", county: "Surrey", category: "Property Developer", capacity: 500, distance_from_london_miles: 20, website: "berkeleygroup.co.uk", trigger_event: "UK's premier luxury housebuilder — six brands (Berkeley, St George, St James, St Edward, St Joseph, St William). 45+ active developments across London, Surrey, Herts, Kent, Berks. Major show home launches, investor events, VIP cocktail receptions for new developments. Founded 1976", contact_email: "", phone: "" },
  { venue_name: "Crest Nicholson", location: "Bourne Business Park, Addlestone", city: "Addlestone", county: "Surrey", category: "Property Developer", capacity: 300, distance_from_london_miles: 22, website: "crestnicholson.com", trigger_event: "Leading mid-premium housebuilder — HQ in Surrey, five regional divisions across South of England & Midlands. Developments in Essex, Hampshire, Herts, Kent, Oxfordshire, Suffolk, Surrey. Show home launches, development openings, investor evenings. Longcross Garden Village flagship", contact_email: "", phone: "" },
  { venue_name: "Barratt Redrow (Barratt Homes & David Wilson Homes)", location: "Barratt House, Coalville", city: "Coalville", county: "Leicestershire", category: "Property Developer", capacity: 500, distance_from_london_miles: 110, website: "barratthomes.co.uk", trigger_event: "UK's largest housebuilder — Barratt Homes, Barratt London, David Wilson Homes, Redrow brands. £39.6m community contributions from North Thames alone. Show home launches with celebrity appearances, seasonal launch events across SE. Chaulden Meadows (1,100 homes) recently launched", contact_email: "", phone: "" },
  { venue_name: "Taylor Wimpey", location: "Gate House, Turnpike Road, High Wycombe", city: "High Wycombe", county: "Buckinghamshire", category: "Property Developer", capacity: 400, distance_from_london_miles: 29, website: "taylorwimpey.co.uk", trigger_event: "Major UK housebuilder — South Thames, Southern Counties & South Midlands divisions. Show home launch events with VIP openings (e.g. Salden Place East MK — 1,795 homes). Festive events series across developments. New sustainable zero-carbon prototype homes", contact_email: "", phone: "" },
  { venue_name: "Persimmon Homes (inc. Charles Church)", location: "Persimmon House, York", city: "York", county: "North Yorkshire", category: "Property Developer", capacity: 400, distance_from_london_miles: 148, website: "persimmonhomes.com", trigger_event: "91 active developments across 87 UK locations. South East division covers Bucks, Hampshire, Kent, Surrey. Persimmon Homes, Charles Church (premium) & Westbury Partnerships brands. Regular show home openings, community launch events, VIP buyer evenings", contact_email: "", phone: "" },
  { venue_name: "Bellway Homes", location: "Woolsington, Newcastle", city: "Newcastle upon Tyne", county: "Tyne and Wear", category: "Property Developer", capacity: 400, distance_from_london_miles: 150, website: "bellway.co.uk", trigger_event: "HBF 5-star builder — 20 operating divisions across England, Scotland & Wales. SE developments in Berkshire, Essex, Hampshire, Oxfordshire, West Sussex. Development launch events, show home openings, VIP buyer evenings. Strong mid-premium market positioning", contact_email: "", phone: "" },
  { venue_name: "Octagon Developments", location: "Riverside Office, Hampton Court", city: "East Molesey", county: "Surrey", category: "Property Developer", capacity: 200, distance_from_london_miles: 12, website: "octagon.co.uk", trigger_event: "Pioneer of luxury housebuilding — 40+ years creating prestigious homes in Greater London & Home Counties (Surrey, Berks, Hants, Herts). Broadoaks Park (126 homes, WhatHouse Gold Award). Chancery Homes upper mid-market brand. VIP launch events, investor cocktail receptions", contact_email: "", phone: "" },
  { venue_name: "Shanly Homes", location: "Sorbon Estate, Beaconsfield", city: "Beaconsfield", county: "Buckinghamshire", category: "Property Developer", capacity: 200, distance_from_london_miles: 24, website: "shanlyhomes.com", trigger_event: "Award-winning regional housebuilder since 1969 — high-specification, sustainable, architecturally innovative homes across South East. Part of wider Shanly Group (300+ commercial properties via Sorbon Estates). Show home launches, community events, VIP openings", contact_email: "", phone: "" },
  { venue_name: "ANTLER Agency (Property Marketing)", location: "Witney, Oxfordshire", city: "Witney", county: "Oxfordshire", category: "Property Marketing Agency", capacity: 300, distance_from_london_miles: 65, website: "antleragency.co.uk", trigger_event: "Specialist property marketing, PR & comms agency — works with Crest Nicholson, Thakeham and other major housebuilders. Organises development launches, show home opening events, buyer evenings. Fresh approach to property marketing & launch event coordination", contact_email: "", phone: "" },
  { venue_name: "Anderson Advertising & Property Marketing (AAPM)", location: "Hampshire", city: "Hampshire", county: "Hampshire", category: "Property Marketing Agency", capacity: 300, distance_from_london_miles: 60, website: "aapm.co.uk", trigger_event: "Specialist property marketing agency with 40+ years experience. Organises property launch events on behalf of developers. Expertise across all sectors of property marketing — residential, commercial, mixed-use. Launch event planning & coordination", contact_email: "", phone: "" },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CATEGORY 4: AWARD CEREMONY & GALA PRODUCTION COMPANIES (10)
// Specialist companies that produce and manage award ceremonies, gala dinners
// and black-tie events — they regularly book cocktail reception services.
// ═══════════════════════════════════════════════════════════════════════════════

export const AWARD_CEREMONY_PRODUCTION_LEADS = [
  { venue_name: "Purple Patch Group", location: "Marylebone Road, London", city: "London", county: "Greater London", category: "Award Ceremony & Gala Production", capacity: 1000, distance_from_london_miles: 0, website: "purplepatchgroup.co.uk", trigger_event: "20+ years producing awards ceremonies — from small gala lunches to large ceremonies with international live linkup. Clients: Paramount, Universal, Warner Bros, Arla Foods, British Council. Full production: venue, catering, entertainment, photography. Company No. 05313561", contact_email: "", phone: "" },
  { venue_name: "Bigabox Productions", location: "Eldon Way, Biggleswade", city: "Biggleswade", county: "Bedfordshire", category: "Award Ceremony & Gala Production", capacity: 2000, distance_from_london_miles: 45, website: "bigaboxproductions.co.uk", trigger_event: "Leading independent full event production company — A-list & red carpet awards, charity galas. Venues: The Dorchester, O2 Arena, Royal Ascot, Tobacco Dock. Audio, lighting, LED screens, laser, live streaming. Warehouse in Hertfordshire. Tel: 0330 120 1424", contact_email: "info@bigaboxproductions.co.uk", phone: "0330 120 1424" },
  { venue_name: "Just Smile Events & Production", location: "Aldenham Road, Bushey", city: "Bushey", county: "Hertfordshire", category: "Award Ceremony & Gala Production", capacity: 500, distance_from_london_miles: 15, website: "justsmile.co.uk", trigger_event: "Founded 2009 in St Albans — 10,000+ events delivered. Awards ceremonies, galas, festivals. Expert sound, lighting, staging & video production. Works at The Savoy, The Dorchester, The Grove, The Landmark. Gold Sponsor SME Hertfordshire Business Awards", contact_email: "", phone: "" },
  { venue_name: "Academy Productions", location: "Wessex Road, Bourne End", city: "Bourne End", county: "Buckinghamshire", category: "Award Ceremony & Gala Production", capacity: 300, distance_from_london_miles: 28, website: "academy-productions.co.uk", trigger_event: "Est. 2012, 25+ years team experience — sound, lighting, staging, AV for awards ceremonies, gala dinners, corporate events across Bucks, Berks & Oxfordshire. Lectern hire & full stage set for award presentations. Address: Unit 4, Wessex Road, Bourne End SL8 5DT", contact_email: "", phone: "01628 617730" },
  { venue_name: "Designed Event Production", location: "Winchester, Hampshire", city: "Winchester", county: "Hampshire", category: "Award Ceremony & Gala Production", capacity: 1000, distance_from_london_miles: 65, website: "designedeventproduction.co.uk", trigger_event: "One of UK's most experienced AV teams for award dinners & ceremonies — bespoke solutions from 10 to 1,000 guests. Creative AV, lighting design, stage & set build. Part of Whitwam Group. Venues from historic town halls to modern atriums. Tel: 01962 870408", contact_email: "", phone: "01962 870408" },
  { venue_name: "EMS Events", location: "Tower Bridge, London", city: "London", county: "Greater London", category: "Award Ceremony & Gala Production", capacity: 2000, distance_from_london_miles: 0, website: "ems-events.co.uk", trigger_event: "Central London AV & production company — 25+ years, 20,000+ corporate events. 18,000 sq ft warehouse near Tower Bridge. Award ceremonies, AGMs, conferences, galas. Vitesse Media Women in IT Awards production. Full project management. Tel: 0207 820 9000", contact_email: "", phone: "0207 820 9000" },
  { venue_name: "The Events Company", location: "Thornhill Road, Redditch", city: "Redditch", county: "Worcestershire", category: "Award Ceremony & Gala Production", capacity: 1000, distance_from_london_miles: 110, website: "theeventscompany.co.uk", trigger_event: "Est. 2002 — 20+ years producing corporate awards, industry awards, charity galas, academic ceremonies. Full turnkey: stage set design, lighting, AV, content creation, live show direction. Specialist event management software for guest registration & comms", contact_email: "", phone: "" },
  { venue_name: "Red Event Production", location: "Wootton, Bedford", city: "Bedford", county: "Bedfordshire", category: "Award Ceremony & Gala Production", capacity: 500, distance_from_london_miles: 50, website: "redeventproduction.co.uk", trigger_event: "Creative event production — custom staging, set design, sound, lighting & video for awards ceremonies of all sizes. A-grade solar-powered warehouse. Gold Sustainability Award (SME Bedfordshire 2025). PLASA & PSA member. Serves MK, Bedford, Cambridge & beyond. Tel: 01234 430368", contact_email: "", phone: "01234 430368" },
  { venue_name: "Stage Connections", location: "Solomon Park, Ilkeston", city: "Ilkeston", county: "Derbyshire", category: "Award Ceremony & Gala Production", capacity: 1000, distance_from_london_miles: 130, website: "stageconnections.co.uk", trigger_event: "Fully-integrated technical event production specialist — awards ceremonies, conferences, exhibitions, fashion shows. HQ in East Midlands with London office. Hybrid & virtual awards capability. Sound, lighting, staging, video, special effects. Tel: 0115 944 5220 / 0207 041 9311", contact_email: "hello@stageconnections.co.uk", phone: "0115 944 5220" },
  { venue_name: "AV Xpert", location: "London & South East", city: "London", county: "Greater London", category: "Award Ceremony & Gala Production", capacity: 1000, distance_from_london_miles: 0, website: "avxpert.co.uk", trigger_event: "Specialist awards night production — custom stage sets with printed media & AV content, rear projection screens, LED displays. From low-key awards evenings to extravagant gala dinners. Technical knowledge for bespoke ceremony production. Full equipment supply & operation", contact_email: "", phone: "" },
];
