// HH&T Real Venue Database — 120+ Event & Wedding Venues within 100 miles of London
// NO bars, restaurants, or pubs. Only dedicated event/wedding venues, halls, estates, and spaces.
// Categories: Wedding Venue, Country Estate, Historic Hall, Event Space, Barn Venue, Livery Hall, Museum/Gallery, Castle, Conference Centre

export const VENUE_DATABASE = [
  // ═══════════════════════════════════════════════════════
  // LONDON — Central, South, East, West, North
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "The Brewery",
    location: "Chiswell Street, City of London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 900,
    distance_from_london_miles: 0,
    website: "thebrewery.co.uk",
    trigger_event: "Major corporate event space in the City — ideal for brand activations and gala dinners",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Banqueting House",
    location: "Whitehall, Westminster",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 450,
    distance_from_london_miles: 0,
    website: "hrp.org.uk/banqueting-house",
    trigger_event: "Historic Royal Palace venue beneath the Rubens ceiling — conferences, brand activations, immersive events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Guildhall",
    location: "Gresham Street, City of London",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 500,
    distance_from_london_miles: 0,
    website: "guildhall.cityoflondon.gov.uk",
    trigger_event: "800-year-old Gothic Great Hall — hosts the Lord Mayor's Banquet. Seven flexible function spaces",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Goldsmiths' Hall",
    location: "Foster Lane, City of London",
    city: "London",
    county: "Greater London",
    category: "Livery Hall",
    capacity: 300,
    distance_from_london_miles: 0,
    website: "thegoldsmiths.co.uk/venue-hire",
    trigger_event: "Grade I listed livery hall since 1339. Adaptable spaces for weddings, galas, and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Painters' Hall",
    location: "Little Trinity Lane, City of London",
    city: "London",
    county: "Greater London",
    category: "Livery Hall",
    capacity: 320,
    distance_from_london_miles: 0,
    website: "paintershall.co.uk",
    trigger_event: "Elegant livery hall for conferences, banquets, and wedding receptions up to 320 guests",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Plaisterers' Hall",
    location: "One London Wall, City of London",
    city: "London",
    county: "Greater London",
    category: "Livery Hall",
    capacity: 180,
    distance_from_london_miles: 0,
    website: "plaisterershall.co.uk",
    trigger_event: "Timeless elegance in the City. 130 dinner or 180 theatre style — weddings and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Mansion House",
    location: "Walbrook, City of London",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 350,
    distance_from_london_miles: 0,
    website: "cityoflondon.gov.uk",
    trigger_event: "Grade I listed home of the Lord Mayor, built 1739. Spectacular setting for conferences and dinners",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Natural History Museum",
    location: "Cromwell Road, South Kensington",
    city: "London",
    county: "Greater London",
    category: "Museum/Gallery",
    capacity: 910,
    distance_from_london_miles: 0,
    website: "nhm.ac.uk/venue-hire",
    trigger_event: "Iconic Hintze Hall for grand dinners up to 910. One of London's most remarkable event venues",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Wallace Collection",
    location: "Manchester Square, Marylebone",
    city: "London",
    county: "Greater London",
    category: "Museum/Gallery",
    capacity: 200,
    distance_from_london_miles: 0,
    website: "wallacecollection.org/venue-hire",
    trigger_event: "Beautiful courtyard and galleries for weddings and private events surrounded by fine art",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Design Museum",
    location: "Kensington High Street",
    city: "London",
    county: "Greater London",
    category: "Museum/Gallery",
    capacity: 400,
    distance_from_london_miles: 0,
    website: "designmuseum.org/venue-hire",
    trigger_event: "Iconic contemporary spaces for corporate and private events. Perfect for design-forward brands",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Southbank Centre",
    location: "Belvedere Road, South Bank",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 600,
    distance_from_london_miles: 0,
    website: "southbankcentre.co.uk/venue-hire",
    trigger_event: "Riverfront venue near London Eye — brand activations and corporate events with Thames views",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "National Gallery",
    location: "Trafalgar Square",
    city: "London",
    county: "Greater London",
    category: "Museum/Gallery",
    capacity: 500,
    distance_from_london_miles: 0,
    website: "nationalgallery.org.uk/venue-hire",
    trigger_event: "World-renowned art museum — spectacular setting for dinners surrounded by 2,300+ paintings",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Outernet",
    location: "Denmark Street, Tottenham Court Road",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 500,
    distance_from_london_miles: 0,
    website: "outernet.com",
    trigger_event: "Immersive Ultra HD screens and advanced tech for brand moments, product launches, and events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "10-11 Carlton House Terrace",
    location: "The Mall, St James's",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 350,
    distance_from_london_miles: 0,
    website: "10-11cht.com",
    trigger_event: "Grade I listed Nash terrace overlooking The Mall — weddings, conferences, and private dining",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Kensington Palace Orangery",
    location: "Kensington Gardens",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 250,
    distance_from_london_miles: 0,
    website: "hrp.org.uk/kensington-palace",
    trigger_event: "Royal palace setting for elegant wedding receptions and corporate entertaining",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The May Fair Hotel",
    location: "Stratton Street, Mayfair",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 400,
    distance_from_london_miles: 0,
    website: "themayfairhotel.co.uk",
    trigger_event: "Five-star Mayfair hotel with grand ballroom and stylish cocktail spaces. Min spend from £5,500",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Toynbee Hall",
    location: "Commercial Street, Whitechapel",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 200,
    distance_from_london_miles: 0,
    website: "toynbeehall.org.uk",
    trigger_event: "Grade II listed halls with 140+ years of heritage — flexible event spaces in East London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Chancery Rosewood",
    location: "Mayfair",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 250,
    distance_from_london_miles: 0,
    website: "rosewoodhotels.com",
    trigger_event: "Opened August 2025 — opulent interiors for executive dinners, galas, and weddings in Mayfair",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Town Hall Spaces",
    location: "Covent Garden",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 300,
    distance_from_london_miles: 0,
    website: "townhallspaces.com",
    trigger_event: "Opened July 2025 — historic charm meets contemporary flexibility for weddings and cultural events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "83 Rivington Street",
    location: "Shoreditch",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 750,
    distance_from_london_miles: 0,
    website: "83rivingtonstreet.co.uk",
    trigger_event: "13,000 sq ft across three railway arches — exclusive brand activations and immersive events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Chelsea Old Town Hall",
    location: "King's Road, Chelsea",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 670,
    distance_from_london_miles: 0,
    website: "rbkc.gov.uk",
    trigger_event: "Iconic Chelsea ceremony and reception venue — 670 standing capacity, weddings and civic events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Kensington Conference & Events Centre",
    location: "Kensington",
    city: "London",
    county: "Greater London",
    category: "Conference Centre",
    capacity: 812,
    distance_from_london_miles: 0,
    website: "kenvenue.co.uk",
    trigger_event: "812 seated or 1,000 standing — large-scale conferences, exhibitions, and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Pembroke Lodge",
    location: "Richmond Park",
    city: "London",
    county: "Greater London",
    category: "Wedding Venue",
    capacity: 160,
    distance_from_london_miles: 8,
    website: "pembroke-lodge.co.uk",
    trigger_event: "UK's #1 wedding venue 2025 with 1120+ five-star reviews. Grade II listed in Richmond Park",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Hampton Court Palace",
    location: "East Molesey, Surrey",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 600,
    distance_from_london_miles: 12,
    website: "hrp.org.uk/hampton-court-palace",
    trigger_event: "Tudor royal palace — grand halls and gardens for spectacular wedding receptions and galas",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Eltham Palace",
    location: "Court Yard, Eltham",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 200,
    distance_from_london_miles: 9,
    website: "english-heritage.org.uk/eltham-palace",
    trigger_event: "Art Deco masterpiece meets medieval royal palace — unique wedding and events venue",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // HERTFORDSHIRE (15-30 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Ashridge House",
    location: "Berkhamsted, Hertfordshire",
    city: "Berkhamsted",
    county: "Hertfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 30,
    website: "ashridgehouse.org.uk",
    trigger_event: "Award-winning venue surrounded by 190 acres of gorgeous gardens. Nine event spaces plus accommodation",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Micklefield Hall",
    location: "Rickmansworth, Hertfordshire",
    city: "Rickmansworth",
    county: "Hertfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 25,
    website: "micklefieldhall.com",
    trigger_event: "Grade II listed 16th-century tithe barn, 25 miles from London — weddings, corporate events, parties",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Hatfield House",
    location: "Hatfield, Hertfordshire",
    city: "Hatfield",
    county: "Hertfordshire",
    category: "Country Estate",
    capacity: 350,
    distance_from_london_miles: 21,
    website: "hatfield-house.co.uk",
    trigger_event: "Jacobean stately home with stunning grounds — exclusive wedding and corporate event hire",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "St. Michael's Manor",
    location: "St Albans, Hertfordshire",
    city: "St Albans",
    county: "Hertfordshire",
    category: "Country Estate",
    capacity: 120,
    distance_from_london_miles: 22,
    website: "stmichaelsmanor.com",
    trigger_event: "Five acres of private English gardens with a one-acre lake near St Albans city centre",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Brocket Hall",
    location: "Welwyn, Hertfordshire",
    city: "Welwyn",
    county: "Hertfordshire",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 25,
    website: "brocket-hall.co.uk",
    trigger_event: "18th-century stately home in 543 acres — exclusive weddings and high-end corporate entertaining",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Moor Park Mansion",
    location: "Rickmansworth, Hertfordshire",
    city: "Rickmansworth",
    county: "Hertfordshire",
    category: "Historic Hall",
    capacity: 300,
    distance_from_london_miles: 24,
    website: "moorparkmansion.co.uk",
    trigger_event: "Grade I listed Palladian mansion with ornate painted ceilings — weddings and events",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // BUCKINGHAMSHIRE (25-45 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Hedsor House",
    location: "Taplow, Buckinghamshire",
    city: "Taplow",
    county: "Buckinghamshire",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 28,
    website: "hedsor.com",
    trigger_event: "Stunning Georgian country house in 100 acres overlooking the Thames — exclusive use luxury weddings",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Denham Mount",
    location: "Denham, Buckinghamshire",
    city: "Denham",
    county: "Buckinghamshire",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 18,
    website: "denhammount.co.uk",
    trigger_event: "Exclusive Georgian villa in 40 acres of parkland and formal gardens — weddings and retreats",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Notley Abbey",
    location: "Long Crendon, Buckinghamshire",
    city: "Long Crendon",
    county: "Buckinghamshire",
    category: "Historic Hall",
    capacity: 200,
    distance_from_london_miles: 42,
    website: "notleyabbey.co.uk",
    trigger_event: "13th-century Augustinian abbey — exclusive use wedding venue, once owned by Laurence Olivier",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Waddesdon Manor",
    location: "Waddesdon, Buckinghamshire",
    city: "Waddesdon",
    county: "Buckinghamshire",
    category: "Country Estate",
    capacity: 300,
    distance_from_london_miles: 45,
    website: "waddesdon.org.uk",
    trigger_event: "Rothschild Renaissance-style chateau — National Trust property with event spaces and grounds",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Stoke Park",
    location: "Stoke Poges, Buckinghamshire",
    city: "Stoke Poges",
    county: "Buckinghamshire",
    category: "Country Estate",
    capacity: 400,
    distance_from_london_miles: 23,
    website: "stokepark.com",
    trigger_event: "Iconic Palladian mansion set in 300 acres — weddings, conferences, and luxury events",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // BERKSHIRE (25-50 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Monkey Island Estate",
    location: "Bray, Berkshire",
    city: "Bray",
    county: "Berkshire",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 28,
    website: "monkeyislandestate.co.uk",
    trigger_event: "Centuries-old Thames island retreat near Windsor — elegant gardens, event spaces, and accommodation",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Lillibrooke Manor",
    location: "Maidenhead, Berkshire",
    city: "Maidenhead",
    county: "Berkshire",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 30,
    website: "lillibrookemanor.co.uk",
    trigger_event: "15 acres of meadows in the Thames Valley — barn-style wedding venue with flexible event spaces",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Stanlake Park",
    location: "Twyford, Berkshire",
    city: "Twyford",
    county: "Berkshire",
    category: "Country Estate",
    capacity: 180,
    distance_from_london_miles: 38,
    website: "stanlakepark.com",
    trigger_event: "16th-century estate with award-winning vineyard — romantic setting just 40 minutes from London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Wasing Park",
    location: "Aldermaston, Berkshire",
    city: "Aldermaston",
    county: "Berkshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 50,
    website: "wasingpark.com",
    trigger_event: "Beautiful countryside estate with barns, church, and walled garden — exclusive wedding venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Amber Lodge at Amber Lakes",
    location: "Wokingham, Berkshire",
    city: "Wokingham",
    county: "Berkshire",
    category: "Wedding Venue",
    capacity: 120,
    distance_from_london_miles: 35,
    website: "amberlakes.co.uk",
    trigger_event: "Rated 5/5 — lakeside wedding venue set in stunning Berkshire countryside",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // SURREY (15-40 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "The Barn at Botley Hill",
    location: "Limpsfield, Surrey",
    city: "Limpsfield",
    county: "Surrey",
    category: "Barn Venue",
    capacity: 150,
    distance_from_london_miles: 20,
    website: "botleyhillbarn.co.uk",
    trigger_event: "Rustic elegance meets modern light, perched atop the Surrey Hills — stone's throw from London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Coltsford Mill",
    location: "Oxted, Surrey",
    city: "Oxted",
    county: "Surrey",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 22,
    website: "coltsfordmill-weddings.co.uk",
    trigger_event: "Country barn with elegant contemporary finish, 12 acres of Surrey countryside with 2 stunning lakes",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Gildings Barns",
    location: "Newdigate, Surrey",
    city: "Newdigate",
    county: "Surrey",
    category: "Barn Venue",
    capacity: 180,
    distance_from_london_miles: 28,
    website: "gildingsbarns.co.uk",
    trigger_event: "Secluded countryside wedding venue with oak-beamed architecture — easily reachable from London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Gatton Manor",
    location: "Ockley, Surrey",
    city: "Ockley",
    county: "Surrey",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 30,
    website: "gattonmanor.co.uk",
    trigger_event: "Set in 200 acres of tranquil Surrey countryside — weddings and private events with parkland views",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Loseley Park",
    location: "Guildford, Surrey",
    city: "Guildford",
    county: "Surrey",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 32,
    website: "loseley-park.co.uk",
    trigger_event: "Elizabethan manor house in 1,400 acres — walled garden tithe barn for weddings and corporate days",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Farnham Castle",
    location: "Farnham, Surrey",
    city: "Farnham",
    county: "Surrey",
    category: "Castle",
    capacity: 200,
    distance_from_london_miles: 40,
    website: "farnhamcastle.com",
    trigger_event: "900-year-old castle and historic Bishop's Palace — spectacular wedding and conference venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Clandon Park",
    location: "West Clandon, Surrey",
    city: "West Clandon",
    county: "Surrey",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 28,
    website: "nationaltrust.org.uk/clandon-park",
    trigger_event: "National Trust Palladian mansion currently being restored — event spaces in the grounds",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Nonsuch Mansion",
    location: "Cheam, Surrey",
    city: "Cheam",
    county: "Surrey",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 13,
    website: "nonsuchmansion.com",
    trigger_event: "Exclusive Georgian mansion set within Nonsuch Park — weddings, parties, and corporate events",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // KENT (20-60 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "The Oak Barn, Frame Farm",
    location: "Benenden, Kent",
    city: "Benenden",
    county: "Kent",
    category: "Barn Venue",
    capacity: 150,
    distance_from_london_miles: 48,
    website: "the-oak-barn.co.uk",
    trigger_event: "Award-winning eco-friendly farm from 1607 in High Weald AONB — one hour from London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Old Kent Barn",
    location: "Swingfield, Kent",
    city: "Swingfield",
    county: "Kent",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 65,
    website: "theoldkentbarn.co.uk",
    trigger_event: "Award-winning 250-year-old barn between Folkestone and Canterbury — weddings and celebrations",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Falconhurst",
    location: "Markbeech, Kent",
    city: "Markbeech",
    county: "Kent",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 30,
    website: "falconhurst.co.uk",
    trigger_event: "Enchanting venue with walled gardens and views of Ashdown Forest — exclusive weddings",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Lost Village of Dode",
    location: "Luddesdown, Kent",
    city: "Luddesdown",
    county: "Kent",
    category: "Historic Hall",
    capacity: 80,
    distance_from_london_miles: 28,
    website: "dode.co.uk",
    trigger_event: "12th-century church in a deserted medieval village — one of the most unique wedding venues in England",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Hever Castle",
    location: "Hever, Kent",
    city: "Hever",
    county: "Kent",
    category: "Castle",
    capacity: 200,
    distance_from_london_miles: 30,
    website: "hevercastle.co.uk",
    trigger_event: "13th-century moated castle — childhood home of Anne Boleyn. Weddings and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Leeds Castle",
    location: "Maidstone, Kent",
    city: "Maidstone",
    county: "Kent",
    category: "Castle",
    capacity: 300,
    distance_from_london_miles: 40,
    website: "leeds-castle.com",
    trigger_event: "900-year-old castle on two islands — one of the most romantic wedding venues in England",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Penshurst Place",
    location: "Penshurst, Kent",
    city: "Penshurst",
    county: "Kent",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 32,
    website: "penshurstplace.com",
    trigger_event: "Medieval manor house with Baron's Hall dating from 1341 — weddings and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Port Lympne Hotel & Reserve",
    location: "Hythe, Kent",
    city: "Hythe",
    county: "Kent",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 60,
    website: "aspinallfoundation.org/port-lympne",
    trigger_event: "Mansion overlooking the Channel with 600-acre wildlife reserve — unique wedding backdrop",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // ESSEX (15-50 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Gosfield Hall",
    location: "Halstead, Essex",
    city: "Halstead",
    county: "Essex",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 48,
    website: "gosfieldhall.co.uk",
    trigger_event: "Georgian country house with stunning Tudor Gallery — exclusive wedding venue in North Essex",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Parklands Quendon Hall",
    location: "Quendon, Essex",
    city: "Quendon",
    county: "Essex",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 38,
    website: "parklandsquendonhall.co.uk",
    trigger_event: "Exclusive use Georgian manor with sweeping lawns and orangery — weddings and private events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Hylands House",
    location: "Chelmsford, Essex",
    city: "Chelmsford",
    county: "Essex",
    category: "Country Estate",
    capacity: 300,
    distance_from_london_miles: 32,
    website: "hylandsestate.co.uk",
    trigger_event: "Grade II* listed neo-classical villa in 574 acres of parkland — weddings and major events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Blake Hall",
    location: "Ongar, Essex",
    city: "Ongar",
    county: "Essex",
    category: "Barn Venue",
    capacity: 250,
    distance_from_london_miles: 22,
    website: "blakehall.co.uk",
    trigger_event: "Exclusive barn wedding venue set in picturesque Essex countryside — close to London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Gaynes Park",
    location: "Epping, Essex",
    city: "Epping",
    county: "Essex",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 18,
    website: "gaynespark.co.uk",
    trigger_event: "Beautiful barns and gardens on the edge of Epping Forest — exclusive use wedding venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Apton Hall",
    location: "Rochford, Essex",
    city: "Rochford",
    county: "Essex",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 38,
    website: "aptonhall.co.uk",
    trigger_event: "Elegant Essex wedding venue with landscaped gardens, lake, and orangery",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // SUSSEX (35-65 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Goodwood Estate",
    location: "Chichester, West Sussex",
    city: "Chichester",
    county: "West Sussex",
    category: "Country Estate",
    capacity: 245,
    distance_from_london_miles: 60,
    website: "goodwood.com",
    trigger_event: "Historic 11,000-acre estate with Regency-era interiors — elegant weddings up to 245 guests",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Briar House Barns",
    location: "Rotherfield, East Sussex",
    city: "Rotherfield",
    county: "East Sussex",
    category: "Barn Venue",
    capacity: 150,
    distance_from_london_miles: 40,
    website: "briarhousebarns.co.uk",
    trigger_event: "Rolling hills of East Sussex — rustic wedding venue accessible from Sussex, Kent, and London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Yoghurt Rooms",
    location: "Sharpthorne, West Sussex",
    city: "Sharpthorne",
    county: "West Sussex",
    category: "Barn Venue",
    capacity: 150,
    distance_from_london_miles: 38,
    website: "yoghurtrooms.com",
    trigger_event: "DIY whole-farm weekend venue — boho, rustic, festival-style with hay bales, fire pits, and woodland",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Hendall Manor Barns",
    location: "Uckfield, East Sussex",
    city: "Uckfield",
    county: "East Sussex",
    category: "Barn Venue",
    capacity: 120,
    distance_from_london_miles: 42,
    website: "hendallmanorbarns.co.uk",
    trigger_event: "Stunning barn conversion in the Sussex Weald — romantic and rustic exclusive wedding venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Buxted Park Hotel",
    location: "Buxted, East Sussex",
    city: "Buxted",
    county: "East Sussex",
    category: "Country Estate",
    capacity: 180,
    distance_from_london_miles: 44,
    website: "handpickedhotels.co.uk/buxtedpark",
    trigger_event: "Georgian country house hotel in 312 acres of Ashdown Forest — elegant weddings and events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Firle Place",
    location: "Firle, East Sussex",
    city: "Firle",
    county: "East Sussex",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 55,
    website: "firleplace.co.uk",
    trigger_event: "Tudor manor beneath the South Downs — exclusive weddings and corporate events in beautiful grounds",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Arundel Castle",
    location: "Arundel, West Sussex",
    city: "Arundel",
    county: "West Sussex",
    category: "Castle",
    capacity: 300,
    distance_from_london_miles: 56,
    website: "arundelcastle.org",
    trigger_event: "1000-year-old castle with breathtaking gardens — wedding ceremonies and grand receptions",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // OXFORDSHIRE / COTSWOLDS (45-80 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Caswell House",
    location: "Brize Norton, Oxfordshire",
    city: "Brize Norton",
    county: "Oxfordshire",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 65,
    website: "caswellhouse.co.uk",
    trigger_event: "15th-century Cotswold stone barns in the Oxfordshire countryside — 140 ceremony, 200 evening",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Cornwell Manor",
    location: "Chipping Norton, Oxfordshire",
    city: "Chipping Norton",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 72,
    website: "cornwellmanor.co.uk",
    trigger_event: "One of the prettiest houses in England — 2,000-acre estate near Chipping Norton with unparalleled privacy",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Stonor Park",
    location: "Henley-on-Thames, Oxfordshire",
    city: "Henley-on-Thames",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 40,
    website: "stonor.com",
    trigger_event: "Historic house with private deer park in the Chilterns — 13th-century chapel and exclusive use",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Kingston Bagpuize House",
    location: "Abingdon, Oxfordshire",
    city: "Abingdon",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 60,
    website: "kingstonbagpuizehouse.com",
    trigger_event: "Stunning Georgian stately home with gardens, lake, and 10 acres of parkland outside Oxford",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Merriscourt",
    location: "Sarsden, Oxfordshire",
    city: "Sarsden",
    county: "Oxfordshire",
    category: "Barn Venue",
    capacity: 250,
    distance_from_london_miles: 70,
    website: "merriscourt.com",
    trigger_event: "Three interlinked Cotswolds barns on 500 acres — Oxfordshire/Gloucestershire border",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Worton Hall",
    location: "Cassington, Oxfordshire",
    city: "Cassington",
    county: "Oxfordshire",
    category: "Barn Venue",
    capacity: 180,
    distance_from_london_miles: 60,
    website: "wortonhall.co.uk",
    trigger_event: "Rebuilt yellow-stone grain barn on the edge of the Cotswolds near Oxford — wedding venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Soho Farmhouse",
    location: "Great Tew, Oxfordshire",
    city: "Great Tew",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 120,
    distance_from_london_miles: 70,
    website: "sohofarmhouse.com",
    trigger_event: "Members-only countryside retreat on 100 acres — rustic-luxe Barwell Barn seats 120",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Bodleian Libraries",
    location: "Oxford",
    city: "Oxford",
    county: "Oxfordshire",
    category: "Historic Hall",
    capacity: 250,
    distance_from_london_miles: 56,
    website: "bodleian.ox.ac.uk/venue-hire",
    trigger_event: "Historic Oxford venue — Divinity School and Convocation House licensed for weddings and events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Aynhoe Park",
    location: "Aynho, Oxfordshire",
    city: "Aynho",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 65,
    website: "aynhoepark.co.uk",
    trigger_event: "Extraordinary private stately home filled with art and curiosities — exclusive weddings and events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Dovecote Events",
    location: "Adderbury, Oxfordshire",
    city: "Adderbury",
    county: "Oxfordshire",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 68,
    website: "dovecoteevents.co.uk",
    trigger_event: "Wedding barn, giant two-hat tipi, and classic marquee on the edge of the Cotswolds",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Kirtlington Park",
    location: "Kirtlington, Oxfordshire",
    city: "Kirtlington",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 60,
    website: "kirtlingtonpark.co.uk",
    trigger_event: "Palladian house with Capability Brown parkland — one of the finest country house wedding venues",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Rackley's at Bury Court Farm",
    location: "Lane End, Buckinghamshire",
    city: "Lane End",
    county: "Buckinghamshire",
    category: "Barn Venue",
    capacity: 200,
    distance_from_london_miles: 35,
    website: "rackleys.co.uk",
    trigger_event: "Rolling Chiltern Hills, 25 miles from Heathrow — beautiful rural wedding venue near Marlow and Henley",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // HAMPSHIRE (50-75 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Highclere Castle",
    location: "Newbury, Hampshire",
    city: "Newbury",
    county: "Hampshire",
    category: "Castle",
    capacity: 200,
    distance_from_london_miles: 58,
    website: "highclerecastle.co.uk",
    trigger_event: "The real Downton Abbey — exclusive private events in one of England's most iconic country houses",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Elvetham Hotel",
    location: "Hartley Wintney, Hampshire",
    city: "Hartley Wintney",
    county: "Hampshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 42,
    website: "elvethamhotel.co.uk",
    trigger_event: "19th-century mansion in 35 acres — exclusive weddings and corporate events near the M3",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Northbrook Park",
    location: "Farnham, Hampshire",
    city: "Farnham",
    county: "Hampshire",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 42,
    website: "northbrookpark.co.uk",
    trigger_event: "Grade II listed Georgian country house with vine-covered orangery — exclusive wedding venue",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Tylney Hall Hotel",
    location: "Hook, Hampshire",
    city: "Hook",
    county: "Hampshire",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 45,
    website: "tylneyhall.co.uk",
    trigger_event: "Victorian country house hotel in 66 acres of Hampshire parkland — weddings and corporate retreats",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // CAMBRIDGESHIRE (50-65 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Westminster College Cambridge",
    location: "Cambridge",
    city: "Cambridge",
    county: "Cambridgeshire",
    category: "Historic Hall",
    capacity: 300,
    distance_from_london_miles: 55,
    website: "westminster.cam.ac.uk",
    trigger_event: "Exclusive use event spaces in central Cambridge — 120 dinner, 300 reception capacity",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Ely Cathedral",
    location: "Ely, Cambridgeshire",
    city: "Ely",
    county: "Cambridgeshire",
    category: "Historic Hall",
    capacity: 500,
    distance_from_london_miles: 70,
    website: "elycathedral.org",
    trigger_event: "1300 years of history — spectacular wedding ceremonies and events in an awe-inspiring setting",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Childerley Estate",
    location: "Dry Drayton, Cambridgeshire",
    city: "Dry Drayton",
    county: "Cambridgeshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 58,
    website: "childerley.com",
    trigger_event: "Exclusive 800-acre estate with Tudor long barn — weddings and events near Cambridge",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // NORFOLK / SUFFOLK (75-100 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Hockwold Hall",
    location: "Hockwold, Norfolk",
    city: "Hockwold",
    county: "Norfolk",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 80,
    website: "hockwoldhallnorfolk.com",
    trigger_event: "16th-century Grade II listed Tudor Hall in 50 acres — exclusive use wedding venue on Norfolk/Suffolk border",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Holkham Hall",
    location: "Wells-next-the-Sea, Norfolk",
    city: "Wells-next-the-Sea",
    county: "Norfolk",
    category: "Country Estate",
    capacity: 300,
    distance_from_london_miles: 100,
    website: "holkham.co.uk",
    trigger_event: "Majestic Palladian house on the North Norfolk coast — grand events and exclusive weddings",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Seckford Hall",
    location: "Woodbridge, Suffolk",
    city: "Woodbridge",
    county: "Suffolk",
    category: "Country Estate",
    capacity: 180,
    distance_from_london_miles: 85,
    website: "seckford.co.uk",
    trigger_event: "Tudor Manor in 34 acres of Suffolk gardens — weddings and events in a magnificent setting",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Glemham Hall",
    location: "Little Glemham, Suffolk",
    city: "Little Glemham",
    county: "Suffolk",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 90,
    website: "glemhamhall.co.uk",
    trigger_event: "Country House Party venue with stunning gardens and luxurious marquee — parties and weddings",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Bressingham Hall",
    location: "Bressingham, Norfolk",
    city: "Bressingham",
    county: "Norfolk",
    category: "Barn Venue",
    capacity: 150,
    distance_from_london_miles: 95,
    website: "bressinghamhall.co.uk",
    trigger_event: "Traditional Norfolk barn with timber framing — elegant wedding venue with overnight accommodation",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // BATH / WILTSHIRE / SOMERSET (80-100 miles from London)
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Euridge Manor",
    location: "Colerne, Wiltshire",
    city: "Colerne",
    county: "Wiltshire",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 95,
    website: "euridgemanor.co.uk",
    trigger_event: "Georgian-style architecture in the Cotswolds hills near Bath — celebrations and corporate retreats",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Bowood Hotel & Spa",
    location: "Calne, Wiltshire",
    city: "Calne",
    county: "Wiltshire",
    category: "Country Estate",
    capacity: 250,
    distance_from_london_miles: 90,
    website: "bowood.org",
    trigger_event: "Grand Wiltshire estate with Capability Brown gardens — luxury weddings and corporate events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Babington House",
    location: "Babington, Somerset",
    city: "Babington",
    county: "Somerset",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 100,
    website: "babingtonhouse.co.uk",
    trigger_event: "Soho House's country estate — exclusive wedding venue with chapel, walled garden, and lakeside",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // ADDITIONAL LONDON VENUES — Warehouses & Creative Spaces
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Bermondsey Social Club",
    location: "Bermondsey, South London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 200,
    distance_from_london_miles: 0,
    website: "bermondseysocialclub.co.uk",
    trigger_event: "Southwark railway arch turned event space — intimate parties and creative brand activations",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Truman Brewery",
    location: "Brick Lane, Shoreditch",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 1000,
    distance_from_london_miles: 0,
    website: "trumanbrewery.com",
    trigger_event: "Massive multi-space creative hub in Shoreditch — product launches, exhibitions, brand activations",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Printworks",
    location: "Surrey Quays, South London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 3000,
    distance_from_london_miles: 0,
    website: "printworkslondon.co.uk",
    trigger_event: "Iconic warehouse venue — immersive events, exhibitions, brand experiences at massive scale",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Tobacco Dock",
    location: "Wapping, East London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 2500,
    distance_from_london_miles: 0,
    website: "tobaccodocklondon.com",
    trigger_event: "Grade I listed warehouse — major exhibitions, conferences, immersive brand activations",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "One Marylebone",
    location: "Marylebone, London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 600,
    distance_from_london_miles: 0,
    website: "onemarylebone.com",
    trigger_event: "Deconsecrated church by John Soane — dramatic event space for weddings and fashion shows",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Roundhouse",
    location: "Chalk Farm, Camden",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 1700,
    distance_from_london_miles: 0,
    website: "roundhouse.org.uk",
    trigger_event: "Iconic Grade II listed former railway engine shed — concerts, galas, and immersive events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Alexandra Palace",
    location: "Muswell Hill, North London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 10000,
    distance_from_london_miles: 6,
    website: "alexandrapalace.com",
    trigger_event: "The People's Palace — Great Hall, West Hall, and panoramic terrace for major events and exhibitions",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Barbican Centre",
    location: "Silk Street, City of London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 800,
    distance_from_london_miles: 0,
    website: "barbican.org.uk/hire",
    trigger_event: "Brutalist arts centre — conferences, receptions, and corporate events in the Conservatory and halls",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Victoria House",
    location: "Bloomsbury Square",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 2000,
    distance_from_london_miles: 0,
    website: "victoriahouse.co.uk",
    trigger_event: "Art Deco former Bloomsbury warehouse — fashion shows, galas, and luxury product launches",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Old Billingsgate",
    location: "Lower Thames Street, City of London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 2000,
    distance_from_london_miles: 0,
    website: "oldbillingsgate.co.uk",
    trigger_event: "Victorian fish market turned premier event venue — conferences, awards ceremonies, brand events",
    contact_email: "",
    phone: ""
  },

  // ═══════════════════════════════════════════════════════
  // MORE HOME COUNTIES — Additional venues to reach 120+
  // ═══════════════════════════════════════════════════════
  {
    venue_name: "Ditton Manor",
    location: "Datchet, Berkshire",
    city: "Datchet",
    county: "Berkshire",
    capacity: 350,
    category: "Country Estate",
    distance_from_london_miles: 22,
    website: "dittonmanor.co.uk",
    trigger_event: "Grade II listed manor house near Windsor — versatile wedding and event venue with grand rooms",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Elgin",
    location: "Maida Vale, London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 200,
    distance_from_london_miles: 0,
    website: "theelgin.com",
    trigger_event: "Rated 4.9/5 — highly recommended London venue for private events and celebrations",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Addington Palace",
    location: "Croydon, Surrey",
    city: "Croydon",
    county: "Surrey",
    category: "Country Estate",
    capacity: 300,
    distance_from_london_miles: 12,
    website: "addingtonpalace.co.uk",
    trigger_event: "Former Archbishop's residence in 160 acres — grand wedding venue minutes from Central London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Little Dower House",
    location: "Old Windsor, Berkshire",
    city: "Old Windsor",
    county: "Berkshire",
    category: "Country Estate",
    capacity: 100,
    distance_from_london_miles: 24,
    website: "littledowerhouse.co.uk",
    trigger_event: "Romantic venue with sweeping views of Windsor Castle and 12 acres of private gardens",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Sudbury House Hotel",
    location: "Faringdon, Oxfordshire",
    city: "Faringdon",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 150,
    distance_from_london_miles: 70,
    website: "sudburyhouse.co.uk",
    trigger_event: "Nine acres of manicured gardens in the Cotswolds — intimate wedding venue near Faringdon",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Syon Park",
    location: "Brentford, West London",
    city: "London",
    county: "Greater London",
    category: "Country Estate",
    capacity: 400,
    distance_from_london_miles: 9,
    website: "syonpark.co.uk",
    trigger_event: "200 acres of parkland with The Great Conservatory — weddings and events by the Thames in West London",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Kew Gardens",
    location: "Richmond, London",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 300,
    distance_from_london_miles: 8,
    website: "kew.org/venue-hire",
    trigger_event: "UNESCO World Heritage Site — Temperate House and Nash Conservatory for stunning events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Spencer House",
    location: "St James's Place, London",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 250,
    distance_from_london_miles: 0,
    website: "spencerhouse.co.uk",
    trigger_event: "18th-century aristocratic palace — one of London's finest surviving townhouses for private events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Fulham Palace",
    location: "Fulham, London",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 200,
    distance_from_london_miles: 4,
    website: "fulhampalace.org",
    trigger_event: "Historic Bishop's residence with Tudor courtyard and botanical gardens — weddings and events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Two Temple Place",
    location: "Victoria Embankment, London",
    city: "London",
    county: "Greater London",
    category: "Historic Hall",
    capacity: 150,
    distance_from_london_miles: 0,
    website: "twotempleplace.org",
    trigger_event: "Neo-Gothic mansion on the Embankment — lavish interior with stained glass for exclusive events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "IET London: Savoy Place",
    location: "Savoy Place, London",
    city: "London",
    county: "Greater London",
    category: "Conference Centre",
    capacity: 400,
    distance_from_london_miles: 0,
    website: "savoyplace.london",
    trigger_event: "Thames-side conference and events venue with river terrace — corporate events and award ceremonies",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "The Hurlingham Club",
    location: "Ranelagh Gardens, Fulham",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 500,
    distance_from_london_miles: 4,
    website: "hurlinghamclub.org.uk",
    trigger_event: "Prestigious private members club in 42 acres — weddings, receptions, and corporate hospitality",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Blenheim Palace",
    location: "Woodstock, Oxfordshire",
    city: "Woodstock",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 500,
    distance_from_london_miles: 63,
    website: "blenheimpalace.com",
    trigger_event: "UNESCO World Heritage Site — birthplace of Churchill. Grand events in one of England's finest palaces",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Ardington House",
    location: "Ardington, Oxfordshire",
    city: "Ardington",
    county: "Oxfordshire",
    category: "Country Estate",
    capacity: 120,
    distance_from_london_miles: 55,
    website: "ardingtonhouse.com",
    trigger_event: "Georgian country house with Imperial Staircase — exclusive use for weddings and private events",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Wotton House",
    location: "Dorking, Surrey",
    city: "Dorking",
    county: "Surrey",
    category: "Country Estate",
    capacity: 200,
    distance_from_london_miles: 25,
    website: "wottonhousesurrey.co.uk",
    trigger_event: "17th-century Italian-style country house with 13 acres — weddings, conferences, and events in Surrey",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Dulwich Picture Gallery",
    location: "Dulwich, South London",
    city: "London",
    county: "Greater London",
    category: "Museum/Gallery",
    capacity: 200,
    distance_from_london_miles: 5,
    website: "dulwichpicturegallery.org.uk",
    trigger_event: "England's first purpose-built public art gallery — intimate events surrounded by Old Masters",
    contact_email: "",
    phone: ""
  },
  {
    venue_name: "Royal Horticultural Halls",
    location: "Vincent Square, Westminster",
    city: "London",
    county: "Greater London",
    category: "Event Space",
    capacity: 1200,
    distance_from_london_miles: 0,
    website: "rhsvenuehire.co.uk",
    trigger_event: "Art Deco Lindley Hall — conferences, exhibitions, gala dinners, and fashion shows in Westminster",
    contact_email: "",
    phone: ""
  }
];

export default VENUE_DATABASE;
