// HH&T Real Venue Database — 345+ Event & Wedding Venues across Southern England
// Within ~4 hours' drive of London (~150 miles radius)
// NO bars, restaurants, or pubs. Only dedicated event/wedding venues, halls, estates, and spaces.
// Categories: Wedding Venue, Country Estate, Historic Hall, Event Space, Barn Venue, Livery Hall, Museum/Gallery, Castle, Conference Centre

export const VENUE_DATABASE = [
  // ═══════════════════════════════════════════════════════
  // GREATER LONDON
  // ═══════════════════════════════════════════════════════
  { venue_name: "The Brewery", location: "Chiswell Street, City of London", city: "London", county: "Greater London", category: "Event Space", capacity: 900, distance_from_london_miles: 0, website: "thebrewery.co.uk", trigger_event: "Major corporate event space in the City — brand activations and gala dinners", contact_email: "", phone: "" },
  { venue_name: "Banqueting House", location: "Whitehall, Westminster", city: "London", county: "Greater London", category: "Historic Hall", capacity: 450, distance_from_london_miles: 0, website: "hrp.org.uk/banqueting-house", trigger_event: "Historic Royal Palace beneath the Rubens ceiling — conferences and immersive events", contact_email: "", phone: "" },
  { venue_name: "Guildhall", location: "Gresham Street, City of London", city: "London", county: "Greater London", category: "Historic Hall", capacity: 500, distance_from_london_miles: 0, website: "guildhall.cityoflondon.gov.uk", trigger_event: "800-year-old Gothic Great Hall — hosts the Lord Mayor's Banquet", contact_email: "", phone: "" },
  { venue_name: "Goldsmiths' Hall", location: "Foster Lane, City of London", city: "London", county: "Greater London", category: "Livery Hall", capacity: 300, distance_from_london_miles: 0, website: "thegoldsmiths.co.uk", trigger_event: "One of London's finest Livery Halls — opulent gilded interiors for gala dinners", contact_email: "", phone: "" },
  { venue_name: "Merchant Taylors' Hall", location: "Threadneedle Street, City of London", city: "London", county: "Greater London", category: "Livery Hall", capacity: 350, distance_from_london_miles: 0, website: "merchanttaylors.co.uk", trigger_event: "Medieval origins, recently restored Great Hall — top-tier corporate entertaining", contact_email: "", phone: "" },
  { venue_name: "Drapers' Hall", location: "Throgmorton Avenue, City of London", city: "London", county: "Greater London", category: "Livery Hall", capacity: 260, distance_from_london_miles: 0, website: "thedrapers.co.uk", trigger_event: "Stunning Renaissance interiors — exclusive private dining and receptions", contact_email: "", phone: "" },
  { venue_name: "Stationers' Hall", location: "Ave Maria Lane, City of London", city: "London", county: "Greater London", category: "Livery Hall", capacity: 200, distance_from_london_miles: 0, website: "stationers.org", trigger_event: "Beautiful oak-panelled hall near St Paul's — weddings and private events", contact_email: "", phone: "" },
  { venue_name: "Ironmongers' Hall", location: "Shaftesbury Place, City of London", city: "London", county: "Greater London", category: "Livery Hall", capacity: 180, distance_from_london_miles: 0, website: "ironmongers.org", trigger_event: "Elegant City livery hall — corporate dinners and receptions", contact_email: "", phone: "" },
  { venue_name: "Natural History Museum", location: "Cromwell Road, South Kensington", city: "London", county: "Greater London", category: "Museum/Gallery", capacity: 400, distance_from_london_miles: 0, website: "nhm.ac.uk", trigger_event: "Iconic Hintze Hall beneath the blue whale — spectacular galas and brand launches", contact_email: "", phone: "" },
  { venue_name: "Victoria and Albert Museum", location: "Cromwell Road, South Kensington", city: "London", county: "Greater London", category: "Museum/Gallery", capacity: 350, distance_from_london_miles: 0, website: "vam.ac.uk", trigger_event: "Nine venue spaces within world-famous museum — receptions surrounded by art", contact_email: "", phone: "" },
  { venue_name: "Science Museum", location: "Exhibition Road, South Kensington", city: "London", county: "Greater London", category: "Museum/Gallery", capacity: 500, distance_from_london_miles: 0, website: "sciencemuseum.org.uk", trigger_event: "Futuristic event spaces among iconic exhibits — corporate and brand events", contact_email: "", phone: "" },
  { venue_name: "Tower of London", location: "Tower Hill, City of London", city: "London", county: "Greater London", category: "Castle", capacity: 350, distance_from_london_miles: 0, website: "hrp.org.uk/tower-of-london", trigger_event: "Iconic fortress on the Thames — exclusive hire for prestige events", contact_email: "", phone: "" },
  { venue_name: "Kensington Palace", location: "Kensington Gardens", city: "London", county: "Greater London", category: "Historic Hall", capacity: 300, distance_from_london_miles: 0, website: "hrp.org.uk/kensington-palace", trigger_event: "Royal residence with Orangery — weddings, galas, and private dinners", contact_email: "", phone: "" },
  { venue_name: "Eltham Palace", location: "Court Yard, Eltham", city: "London", county: "Greater London", category: "Historic Hall", capacity: 200, distance_from_london_miles: 8, website: "english-heritage.org.uk/visit/places/eltham-palace-and-gardens", trigger_event: "Art Deco masterpiece with medieval Great Hall — weddings in 19 acres of gardens", contact_email: "", phone: "" },
  { venue_name: "Hampton Court Palace", location: "East Molesey", city: "London", county: "Greater London", category: "Historic Hall", capacity: 300, distance_from_london_miles: 12, website: "hrp.org.uk/hampton-court-palace", trigger_event: "Tudor royal palace — Great Hall, garden room, and riverside celebrations", contact_email: "", phone: "" },
  { venue_name: "The Roundhouse", location: "Chalk Farm Road, Camden", city: "London", county: "Greater London", category: "Event Space", capacity: 1800, distance_from_london_miles: 3, website: "roundhouse.org.uk", trigger_event: "Grade II listed former railway shed — major concerts, brand experiences, award shows", contact_email: "", phone: "" },
  { venue_name: "Alexandra Palace", location: "Alexandra Palace Way, Wood Green", city: "London", county: "Greater London", category: "Event Space", capacity: 10000, distance_from_london_miles: 7, website: "alexandrapalace.com", trigger_event: "Victorian 'People's Palace' — massive events, exhibitions, and conferencing", contact_email: "", phone: "" },
  { venue_name: "One Marylebone", location: "Marylebone Road", city: "London", county: "Greater London", category: "Event Space", capacity: 550, distance_from_london_miles: 0, website: "onemarylebone.com", trigger_event: "Deconsecrated church by Regent's Park — striking venue for galas and launches", contact_email: "", phone: "" },
  { venue_name: "Banking Hall", location: "Cornhill, City of London", city: "London", county: "Greater London", category: "Event Space", capacity: 450, distance_from_london_miles: 0, website: "bankinghall.co.uk", trigger_event: "Former bank HQ with grand neoclassical interiors — exclusive events", contact_email: "", phone: "" },
  { venue_name: "Old Billingsgate", location: "Lower Thames Street, City of London", city: "London", county: "Greater London", category: "Event Space", capacity: 2000, distance_from_london_miles: 0, website: "oldbillingsgate.co.uk", trigger_event: "Former fish market with Thames views — large-scale exhibitions and galas", contact_email: "", phone: "" },
  { venue_name: "Tobacco Dock", location: "Wapping Lane, Wapping", city: "London", county: "Greater London", category: "Event Space", capacity: 3000, distance_from_london_miles: 3, website: "tobaccodocklondon.com", trigger_event: "Grade I listed warehouse — immersive brand experiences and large events", contact_email: "", phone: "" },
  { venue_name: "Gunnersbury Park", location: "Gunnersbury Park, Ealing", city: "London", county: "Greater London", category: "Historic Hall", capacity: 100, distance_from_london_miles: 7, website: "visitgunnersbury.org", trigger_event: "Grade II listed mansion in 72 hectares of parkland — weddings and receptions", contact_email: "", phone: "" },
  { venue_name: "Syon Park", location: "Brentford, Hounslow", city: "London", county: "Greater London", category: "Country Estate", capacity: 350, distance_from_london_miles: 9, website: "syonpark.co.uk", trigger_event: "Duke of Northumberland's London estate — Great Conservatory and State Apartments", contact_email: "", phone: "" },
  { venue_name: "Pitzhanger Manor & Gallery", location: "Walpole Park, Ealing", city: "London", county: "Greater London", category: "Museum/Gallery", capacity: 150, distance_from_london_miles: 8, website: "pitzhanger.org.uk", trigger_event: "Countryside feel in central London — Sir John Soane's country house", contact_email: "", phone: "" },
  { venue_name: "Ham House", location: "Ham Street, Richmond", city: "London", county: "Greater London", category: "Historic Hall", capacity: 120, distance_from_london_miles: 10, website: "nationaltrust.org.uk/ham-house-and-garden", trigger_event: "17th-century Stuart mansion on the Thames — intimate exclusive events", contact_email: "", phone: "" },
  { venue_name: "The Ministry", location: "Borough, Southwark", city: "London", county: "Greater London", category: "Event Space", capacity: 400, distance_from_london_miles: 1, website: "theministry.london", trigger_event: "Industrial charm — copper bar, exposed brick, exclusive hire", contact_email: "", phone: "" },
  { venue_name: "Village Underground", location: "Great Eastern Street, Shoreditch", city: "London", county: "Greater London", category: "Event Space", capacity: 600, distance_from_london_miles: 2, website: "villageunderground.co.uk", trigger_event: "Victorian coal warehouse converted to 5,000 sq ft creative space", contact_email: "", phone: "" },
  { venue_name: "Trinity Buoy Wharf", location: "Orchard Place, Tower Hamlets", city: "London", county: "Greater London", category: "Event Space", capacity: 350, distance_from_london_miles: 4, website: "trinitybuoywharf.com", trigger_event: "Grade II listed 1854 building by London's only lighthouse — riverside terrace", contact_email: "", phone: "" },
  { venue_name: "Tanner Warehouse", location: "Bermondsey", city: "London", county: "Greater London", category: "Event Space", capacity: 250, distance_from_london_miles: 2, website: "tannerwarehouse.co.uk", trigger_event: "Converted factory with retro industrial elements — exclusive-use weddings", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // SURREY
  // ═══════════════════════════════════════════════════════
  { venue_name: "Farnham Castle", location: "Castle Street, Farnham", city: "Farnham", county: "Surrey", category: "Castle", capacity: 350, distance_from_london_miles: 40, website: "farnhamcastle.com", trigger_event: "Award-winning historic castle — Great Hall seats 230+, exclusive weddings", contact_email: "", phone: "" },
  { venue_name: "Loseley Park", location: "Guildford", city: "Guildford", county: "Surrey", category: "Country Estate", capacity: 200, distance_from_london_miles: 33, website: "loseleypark.co.uk", trigger_event: "Elizabethan mansion in 1,400 acres — Tithe Barn and walled gardens", contact_email: "", phone: "" },
  { venue_name: "Nonsuch Mansion", location: "Nonsuch Park, Cheam", city: "Cheam", county: "Surrey", category: "Historic Hall", capacity: 120, distance_from_london_miles: 13, website: "nonsuchmansion.com", trigger_event: "Tudor-era grounds with Georgian mansion — weddings and corporate events", contact_email: "", phone: "" },
  { venue_name: "Botleys Mansion", location: "Chertsey", city: "Chertsey", county: "Surrey", category: "Country Estate", capacity: 220, distance_from_london_miles: 22, website: "botleysmansion.co.uk", trigger_event: "Exclusive-use Georgian mansion near Virginia Water — up to 220 guests", contact_email: "", phone: "" },
  { venue_name: "Gate Street Barn", location: "Bramley, Guildford", city: "Bramley", county: "Surrey", category: "Barn Venue", capacity: 150, distance_from_london_miles: 35, website: "gatestreetbarn.co.uk", trigger_event: "Exclusive-use oak-framed barn in Surrey Hills AONB", contact_email: "", phone: "" },
  { venue_name: "Millbridge Court", location: "Frensham, Farnham", city: "Farnham", county: "Surrey", category: "Barn Venue", capacity: 150, distance_from_london_miles: 42, website: "millbridgecourt.co.uk", trigger_event: "Modern luxury barn near Farnham — exclusive-use wedding venue", contact_email: "", phone: "" },
  { venue_name: "Greyfriars House", location: "The Friary, Guildford", city: "Guildford", county: "Surrey", category: "Wedding Venue", capacity: 80, distance_from_london_miles: 33, website: "greyfriarshouse.co.uk", trigger_event: "Boutique exclusive venue — only 30 events per year, personal attention", contact_email: "", phone: "" },
  { venue_name: "Clandon Park", location: "West Clandon, Guildford", city: "Guildford", county: "Surrey", category: "Country Estate", capacity: 200, distance_from_london_miles: 28, website: "nationaltrust.org.uk/clandon-park", trigger_event: "National Trust Palladian mansion — currently under restoration, spectacular grounds", contact_email: "", phone: "" },
  { venue_name: "Painshill Park", location: "Cobham", city: "Cobham", county: "Surrey", category: "Country Estate", capacity: 200, distance_from_london_miles: 20, website: "painshill.co.uk", trigger_event: "Award-winning 18th century landscape garden — marquee weddings by the lake", contact_email: "", phone: "" },
  { venue_name: "Russets Country House", location: "Chiddingfold", city: "Chiddingfold", county: "Surrey", category: "Country Estate", capacity: 150, distance_from_london_miles: 40, website: "russetscountryhouse.co.uk", trigger_event: "Exclusive-use Edwardian country house in 7 acres — intimate weddings", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // KENT
  // ═══════════════════════════════════════════════════════
  { venue_name: "Leeds Castle", location: "Broomfield, Maidstone", city: "Maidstone", county: "Kent", category: "Castle", capacity: 300, distance_from_london_miles: 40, website: "leeds-castle.com", trigger_event: "The 'loveliest castle in the world' — 500 acres, exclusive events", contact_email: "", phone: "" },
  { venue_name: "Hever Castle", location: "Hever, Edenbridge", city: "Edenbridge", county: "Kent", category: "Castle", capacity: 200, distance_from_london_miles: 30, website: "hevercastle.co.uk", trigger_event: "Anne Boleyn's childhood home — Tudor splendour with moat and gardens", contact_email: "", phone: "" },
  { venue_name: "Penshurst Place", location: "Penshurst, Tonbridge", city: "Tonbridge", county: "Kent", category: "Historic Hall", capacity: 200, distance_from_london_miles: 32, website: "penshurstplace.com", trigger_event: "Medieval Baron's Hall — 14th century with 48 acres of formal gardens", contact_email: "", phone: "" },
  { venue_name: "Bradbourne House", location: "East Malling", city: "East Malling", county: "Kent", category: "Country Estate", capacity: 200, distance_from_london_miles: 35, website: "bradbournehouse.co.uk", trigger_event: "Queen Anne manor house — exclusive hire for weddings and events", contact_email: "", phone: "" },
  { venue_name: "Winters Barns", location: "Canterbury", city: "Canterbury", county: "Kent", category: "Barn Venue", capacity: 200, distance_from_london_miles: 60, website: "wintersbarns.co.uk", trigger_event: "Charming rural barn with 1750 ceremony room — up to 200 guests", contact_email: "", phone: "" },
  { venue_name: "The Spa Hotel", location: "Mount Ephraim, Tunbridge Wells", city: "Tunbridge Wells", county: "Kent", category: "Country Estate", capacity: 200, distance_from_london_miles: 35, website: "spahotel.co.uk", trigger_event: "18th century mansion in 14 acres — civil ceremonies and outdoor options", contact_email: "", phone: "" },
  { venue_name: "Wadhurst Castle", location: "Wadhurst", city: "Wadhurst", county: "Kent", category: "Castle", capacity: 200, distance_from_london_miles: 42, website: "wadhurscastle.co.uk", trigger_event: "140-acre private estate with castle and barn — exclusive hire, no corkage", contact_email: "", phone: "" },
  { venue_name: "Canterbury Cathedral Lodge", location: "Canterbury", city: "Canterbury", county: "Kent", category: "Historic Hall", capacity: 160, distance_from_london_miles: 60, website: "canterburycathedrallodge.org", trigger_event: "Elegant lodge beside Canterbury Cathedral — receptions with cathedral views", contact_email: "", phone: "" },
  { venue_name: "Knowlton Court", location: "Canterbury", city: "Canterbury", county: "Kent", category: "Country Estate", capacity: 150, distance_from_london_miles: 62, website: "knowltoncourt.co.uk", trigger_event: "Georgian manor house — exclusive-use weddings in rural Kent", contact_email: "", phone: "" },
  { venue_name: "Chilston Park", location: "Lenham, Maidstone", city: "Maidstone", county: "Kent", category: "Country Estate", capacity: 150, distance_from_london_miles: 45, website: "handpickedhotels.co.uk/chilstonpark", trigger_event: "Grade I listed country house in 22 acres of parkland — elegant events", contact_email: "", phone: "" },
  { venue_name: "Lympne Castle", location: "Hythe", city: "Hythe", county: "Kent", category: "Castle", capacity: 120, distance_from_london_miles: 65, website: "lympnecastle.co.uk", trigger_event: "Medieval castle overlooking Romney Marsh — exclusive-use weddings", contact_email: "", phone: "" },
  { venue_name: "Hedingham Castle", location: "Castle Hedingham", city: "Halstead", county: "Kent", category: "Castle", capacity: 250, distance_from_london_miles: 55, website: "hedinghamcastle.co.uk", trigger_event: "Norman keep with stunning countryside views — weddings and corporate retreats", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // ESSEX
  // ═══════════════════════════════════════════════════════
  { venue_name: "Gosfield Hall", location: "Gosfield, Halstead", city: "Halstead", county: "Essex", category: "Historic Hall", capacity: 200, distance_from_london_miles: 50, website: "gosfieldhall.co.uk", trigger_event: "Grade I listed Tudor mansion — 500 years of history, royal connections", contact_email: "", phone: "" },
  { venue_name: "Hylands House", location: "Hylands Park, Chelmsford", city: "Chelmsford", county: "Essex", category: "Country Estate", capacity: 200, distance_from_london_miles: 32, website: "chelmsford.gov.uk/hylands", trigger_event: "Grade II* listed villa in 574 acres — weddings and major events", contact_email: "", phone: "" },
  { venue_name: "Leez Priory", location: "Great Leighs, Chelmsford", city: "Chelmsford", county: "Essex", category: "Historic Hall", capacity: 150, distance_from_london_miles: 38, website: "leezpriory.co.uk", trigger_event: "Tudor mansion — one of Essex's most prestigious exclusive-use venues", contact_email: "", phone: "" },
  { venue_name: "High House", location: "Althorne, Burnham-on-Crouch", city: "Burnham-on-Crouch", county: "Essex", category: "Barn Venue", capacity: 200, distance_from_london_miles: 45, website: "highhouseweddings.com", trigger_event: "Grade II listed barn with orangery — exclusive luxury weddings", contact_email: "", phone: "" },
  { venue_name: "Colville Hall", location: "Chelmsford Road, White Roding", city: "Chelmsford", county: "Essex", category: "Barn Venue", capacity: 200, distance_from_london_miles: 35, website: "colvillehallwedding.co.uk", trigger_event: "Converted barn on a farm — woodland, formal gardens, and farmland", contact_email: "", phone: "" },
  { venue_name: "Old Brook Barn", location: "Navestock", city: "Brentwood", county: "Essex", category: "Barn Venue", capacity: 150, distance_from_london_miles: 20, website: "oldbrookbarn.co.uk", trigger_event: "Rustic barn near London — intimate and charming Essex weddings", contact_email: "", phone: "" },
  { venue_name: "Channels Estate", location: "Pratts Farm Lane, Chelmsford", city: "Chelmsford", county: "Essex", category: "Country Estate", capacity: 200, distance_from_london_miles: 32, website: "channelsestate.co.uk", trigger_event: "Stunning lodge, barn, and gardens — versatile Essex wedding venue", contact_email: "", phone: "" },
  { venue_name: "Wivenhoe House", location: "University of Essex, Colchester", city: "Colchester", county: "Essex", category: "Country Estate", capacity: 120, distance_from_london_miles: 62, website: "wivenhoehouse.co.uk", trigger_event: "Georgian house on university parkland — elegant weddings near Colchester", contact_email: "", phone: "" },
  { venue_name: "The Heron", location: "Herongate, Brentwood", city: "Brentwood", county: "Essex", category: "Country Estate", capacity: 250, distance_from_london_miles: 22, website: "theheroncountryclub.co.uk", trigger_event: "Country club with lakeside setting — large capacity weddings and events", contact_email: "", phone: "" },
  { venue_name: "Battleswick Farm", location: "Rowhedge, Colchester", city: "Colchester", county: "Essex", category: "Barn Venue", capacity: 120, distance_from_london_miles: 60, website: "battleswickfarm.co.uk", trigger_event: "Converted farm venue near Colchester — rustic exclusive-use weddings", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // HERTFORDSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Hatfield House", location: "Hatfield", city: "Hatfield", county: "Hertfordshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 20, website: "hatfield-house.co.uk", trigger_event: "Jacobean masterpiece — Old Palace, The Riding School, and 42 acres of gardens", contact_email: "", phone: "" },
  { venue_name: "Ashridge House", location: "Berkhamsted", city: "Berkhamsted", county: "Hertfordshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 30, website: "ashridgehouse.org.uk", trigger_event: "Stunning Gothic Revival mansion in 190 acres of Chilterns countryside", contact_email: "", phone: "" },
  { venue_name: "Hanbury Manor", location: "Ware", city: "Ware", county: "Hertfordshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 25, website: "marriott.co.uk/hanbury-manor", trigger_event: "Jacobean-style country house with championship golf course — luxury events", contact_email: "", phone: "" },
  { venue_name: "Sopwell House", location: "Cottonmill Lane, St Albans", city: "St Albans", county: "Hertfordshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 22, website: "sopwellhouse.co.uk", trigger_event: "Georgian country house in 12 acres — elegant weddings near St Albans", contact_email: "", phone: "" },
  { venue_name: "St Michael's Manor", location: "Fishpool Street, St Albans", city: "St Albans", county: "Hertfordshire", category: "Country Estate", capacity: 120, distance_from_london_miles: 22, website: "stmichaelsmanor.com", trigger_event: "Historic hotel near Abbey Cathedral — 5 acres of gardens with lake", contact_email: "", phone: "" },
  { venue_name: "Micklefield Hall", location: "Sarratt", city: "Rickmansworth", county: "Hertfordshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 23, website: "micklefieldhall.com", trigger_event: "Exclusive-use country estate with barn — rustic luxury weddings", contact_email: "", phone: "" },
  { venue_name: "The Barn at Alswick", location: "Buntingford", city: "Buntingford", county: "Hertfordshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 35, website: "alswick.co.uk", trigger_event: "Beautiful barn in rural Hertfordshire — exclusive-use with accommodation", contact_email: "", phone: "" },
  { venue_name: "Old Tudor Hall", location: "Hitchin", city: "Hitchin", county: "Hertfordshire", category: "Historic Hall", capacity: 100, distance_from_london_miles: 35, website: "hitchintudorhall.co.uk", trigger_event: "Grade II listed 15th century hall — intimate weddings with in-house catering", contact_email: "", phone: "" },
  { venue_name: "Offley Place", location: "Great Offley, Hitchin", city: "Hitchin", county: "Hertfordshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 36, website: "offleyplace.com", trigger_event: "Romantic all-inclusive hotel venue on the outskirts of Hitchin", contact_email: "", phone: "" },
  { venue_name: "The Priory Barn", location: "Hitchin", city: "Hitchin", county: "Hertfordshire", category: "Barn Venue", capacity: 100, distance_from_london_miles: 35, website: "thepriory-barn.co.uk", trigger_event: "Tucked away barn near Hitchin — civil ceremonies and full day venue", contact_email: "", phone: "" },
  { venue_name: "Knebworth House", location: "Knebworth", city: "Knebworth", county: "Hertfordshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 28, website: "knebworthhouse.com", trigger_event: "Gothic stately home in 250 acres — historic Barns and grand state rooms", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // BUCKINGHAMSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Hedsor House", location: "Hedsor Park, Taplow", city: "Taplow", county: "Buckinghamshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 25, website: "hedsor.com", trigger_event: "Georgian country home in 100 acres — one of UK's most desirable wedding venues", contact_email: "", phone: "" },
  { venue_name: "Cliveden House", location: "Taplow", city: "Taplow", county: "Buckinghamshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 25, website: "clivedenhouse.co.uk", trigger_event: "Iconic Thames-side mansion — 376 acres, National Trust, luxury events", contact_email: "", phone: "" },
  { venue_name: "Waddesdon Manor", location: "Waddesdon, Aylesbury", city: "Aylesbury", county: "Buckinghamshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 45, website: "waddesdon.org.uk", trigger_event: "Rothschild Renaissance château — spectacular exclusive events in 160 acres", contact_email: "", phone: "" },
  { venue_name: "Stoke Park", location: "Park Road, Stoke Poges", city: "Stoke Poges", county: "Buckinghamshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 22, website: "stokepark.com", trigger_event: "Palladian mansion on 300 acres — spa, championship golf, luxury weddings", contact_email: "", phone: "" },
  { venue_name: "Hartwell House", location: "Oxford Road, Aylesbury", city: "Aylesbury", county: "Buckinghamshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 45, website: "hartwell-house.com", trigger_event: "National Trust stately home in the Vale of Aylesbury — 90 acres of parkland", contact_email: "", phone: "" },
  { venue_name: "Rackleys", location: "Cadmore End, High Wycombe", city: "High Wycombe", county: "Buckinghamshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 35, website: "rackleys.co.uk", trigger_event: "Beautiful rural venue in the Chiltern Hills — exclusive wedding barn", contact_email: "", phone: "" },
  { venue_name: "Huntsmill Farm", location: "Buckingham", city: "Buckingham", county: "Buckinghamshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 60, website: "huntsmillfarm.co.uk", trigger_event: "Relaxed stone barn on the Oxfordshire border — on-site accommodation", contact_email: "", phone: "" },
  { venue_name: "Winters Tale Country Barn", location: "Great Missenden", city: "Great Missenden", county: "Buckinghamshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 32, website: "winterstalecountrybarn.co.uk", trigger_event: "17th century farmhouse grounds — seats 120, plus 80 evening guests", contact_email: "", phone: "" },
  { venue_name: "Lillibrooke Manor", location: "Cox Green, Maidenhead", city: "Maidenhead", county: "Buckinghamshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 28, website: "lillibrookemanor.co.uk", trigger_event: "15th century estate in 15 acres — exclusively yours for the day", contact_email: "", phone: "" },
  { venue_name: "Crowne Plaza Marlow", location: "Marlow", city: "Marlow", county: "Buckinghamshire", category: "Wedding Venue", capacity: 200, distance_from_london_miles: 33, website: "cpmarlow.co.uk", trigger_event: "Lakeside views — 5 licensed ceremony spaces near Marlow and High Wycombe", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // BERKSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Windsor Castle", location: "Windsor", city: "Windsor", county: "Berkshire", category: "Castle", capacity: 200, distance_from_london_miles: 22, website: "rct.uk/visit/windsor-castle", trigger_event: "The King's residence — St George's Hall for state banquets", contact_email: "", phone: "" },
  { venue_name: "The Vineyard", location: "Stockcross, Newbury", city: "Newbury", county: "Berkshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 65, website: "the-vineyard.co.uk", trigger_event: "5-star luxury hotel and spa near Newbury — exclusive-use weddings", contact_email: "", phone: "" },
  { venue_name: "Wasing Park", location: "Aldermaston", city: "Reading", county: "Berkshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 55, website: "wasingpark.com", trigger_event: "Exclusive-use estate with orangery, barn, and woodland — flexible spaces", contact_email: "", phone: "" },
  { venue_name: "Sheepdrove", location: "Lambourn, Hungerford", city: "Hungerford", county: "Berkshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 70, website: "sheepdrove.com", trigger_event: "Contemporary barn as blank canvas — exclusive-use, choose own suppliers", contact_email: "", phone: "" },
  { venue_name: "The Mill House Hotel", location: "Swallowfield, Reading", city: "Reading", county: "Berkshire", category: "Country Estate", capacity: 120, distance_from_london_miles: 42, website: "millhousehotel.co.uk", trigger_event: "Georgian mansion beside the River Loddon — exclusive weddings", contact_email: "", phone: "" },
  { venue_name: "Benham Park", location: "Marsh Benham, Newbury", city: "Newbury", county: "Berkshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 65, website: "benhampark.co.uk", trigger_event: "Luxury wedding venue opening Spring 2026 — exclusive hire", contact_email: "", phone: "" },
  { venue_name: "The Post at Burghfield", location: "Burghfield, Reading", city: "Reading", county: "Berkshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 50, website: "thepostatburghfield.co.uk", trigger_event: "120 acres of Berkshire countryside near Newbury — exclusive use", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // HAMPSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Avington Park", location: "Winchester", city: "Winchester", county: "Hampshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 65, website: "avingtonpark.co.uk", trigger_event: "150 acres of historic parkland along the River Itchen — steeped in history", contact_email: "", phone: "" },
  { venue_name: "Froyle Park", location: "Lower Froyle, Alton", city: "Alton", county: "Hampshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 45, website: "froylepark.com", trigger_event: "2025 Best Historic Wedding Venue South Central — 32 guest bedrooms", contact_email: "", phone: "" },
  { venue_name: "Rhinefield House", location: "Brockenhurst", city: "Brockenhurst", county: "Hampshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 90, website: "handpickedhotels.co.uk/rhinefield-house", trigger_event: "19th century Tudor-Gothic mansion in New Forest — 40 acres exclusive hire", contact_email: "", phone: "" },
  { venue_name: "Pylewell Park", location: "Lymington", city: "Lymington", county: "Hampshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 95, website: "pylewellpark.com", trigger_event: "Country house estate near Lymington — quirky bars and cosy bedrooms", contact_email: "", phone: "" },
  { venue_name: "Wintershill Hall", location: "Durley, Southampton", city: "Southampton", county: "Hampshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 75, website: "wintershillhall.com", trigger_event: "Breathtaking views, classic English gardens — serene setting near Southampton", contact_email: "", phone: "" },
  { venue_name: "Norton Park", location: "Sutton Scotney, Winchester", city: "Winchester", county: "Hampshire", category: "Wedding Venue", capacity: 250, distance_from_london_miles: 60, website: "nortonparkhotel.com", trigger_event: "Award-winning venue near Winchester — recommended by couples two years running", contact_email: "", phone: "" },
  { venue_name: "Balmer Lawn", location: "Lyndhurst Road, Brockenhurst", city: "Brockenhurst", county: "Hampshire", category: "Country Estate", capacity: 180, distance_from_london_miles: 90, website: "balmerlawnhotel.com", trigger_event: "Iconic New Forest hotel — spa and wedding celebrations in national park", contact_email: "", phone: "" },
  { venue_name: "Elmers Court", location: "Lymington", city: "Lymington", county: "Hampshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 95, website: "macdonaldhotels.co.uk/elmers-court", trigger_event: "19th century manor in 23 acres — indoor and outdoor ceremonies", contact_email: "", phone: "" },
  { venue_name: "Careys Manor", location: "Brockenhurst", city: "Brockenhurst", county: "Hampshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 90, website: "careysmanor.com", trigger_event: "Traditional charm meets contemporary elegance in the New Forest", contact_email: "", phone: "" },
  { venue_name: "Rotherwick", location: "Tylney Hall, Hook", city: "Hook", county: "Hampshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 42, website: "tylneyhall.co.uk", trigger_event: "Grade II listed Victorian country house in 66 acres of Hampshire gardens", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // WEST SUSSEX
  // ═══════════════════════════════════════════════════════
  { venue_name: "Goodwood House", location: "Chichester", city: "Chichester", county: "West Sussex", category: "Country Estate", capacity: 300, distance_from_london_miles: 60, website: "goodwood.com", trigger_event: "Stunning Regency house on 12,000-acre estate — Ballroom and State Apartments", contact_email: "", phone: "" },
  { venue_name: "Amberley Castle", location: "Amberley, Arundel", city: "Arundel", county: "West Sussex", category: "Castle", capacity: 60, distance_from_london_miles: 55, website: "amberleycastle.co.uk", trigger_event: "Exclusive-use castle in the South Downs — 19 luxury bedrooms", contact_email: "", phone: "" },
  { venue_name: "Arundel Castle", location: "Arundel", city: "Arundel", county: "West Sussex", category: "Castle", capacity: 300, distance_from_london_miles: 56, website: "arundelcastle.org", trigger_event: "Spectacular medieval castle and gardens — grand events and celebrations", contact_email: "", phone: "" },
  { venue_name: "Upwaltham Barns", location: "Upwaltham, Chichester", city: "Chichester", county: "West Sussex", category: "Barn Venue", capacity: 200, distance_from_london_miles: 58, website: "upwalthambarns.co.uk", trigger_event: "Family run venue with two large barns — courtyard and countryside surroundings", contact_email: "", phone: "" },
  { venue_name: "Selden Barns", location: "Patching, Worthing", city: "Worthing", county: "West Sussex", category: "Barn Venue", capacity: 150, distance_from_london_miles: 55, website: "seldenbarns.co.uk", trigger_event: "South Downs National Park — restored barns with panoramic views", contact_email: "", phone: "" },
  { venue_name: "South Stoke Barn", location: "South Stoke, Arundel", city: "Arundel", county: "West Sussex", category: "Barn Venue", capacity: 120, distance_from_london_miles: 55, website: "southstokebarn.co.uk", trigger_event: "Charming granary barn two miles from Arundel — countryside setting", contact_email: "", phone: "" },
  { venue_name: "Weald & Downland Museum", location: "Singleton, Chichester", city: "Chichester", county: "West Sussex", category: "Museum/Gallery", capacity: 180, distance_from_london_miles: 60, website: "wealddown.co.uk", trigger_event: "Unique Downland Gridshell architectural venue surrounded by woodland", contact_email: "", phone: "" },
  { venue_name: "Arundel Town Hall", location: "Maltravers Street, Arundel", city: "Arundel", county: "West Sussex", category: "Historic Hall", capacity: 120, distance_from_london_miles: 56, website: "arundeltownhall.com", trigger_event: "Georgian ballroom with vaulted foyer and grand stone staircase", contact_email: "", phone: "" },
  { venue_name: "Wiston House", location: "Steyning", city: "Steyning", county: "West Sussex", category: "Country Estate", capacity: 150, distance_from_london_miles: 50, website: "wistonhouse.co.uk", trigger_event: "Elizabethan manor in the South Downs — conference centre and events", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // EAST SUSSEX
  // ═══════════════════════════════════════════════════════
  { venue_name: "Firle Place", location: "Firle, Lewes", city: "Lewes", county: "East Sussex", category: "Country Estate", capacity: 250, distance_from_london_miles: 55, website: "firle.com", trigger_event: "Tudor house at the foot of the South Downs — Great Hall and gardens", contact_email: "", phone: "" },
  { venue_name: "Glynde Place", location: "Glynde, Lewes", city: "Lewes", county: "East Sussex", category: "Country Estate", capacity: 200, distance_from_london_miles: 55, website: "glyndeplace.co.uk", trigger_event: "Elizabethan country house with gallery — exclusive-use for weddings", contact_email: "", phone: "" },
  { venue_name: "Buxted Park", location: "Buxted, Uckfield", city: "Uckfield", county: "East Sussex", category: "Country Estate", capacity: 150, distance_from_london_miles: 42, website: "handpickedhotels.co.uk/buxted-park", trigger_event: "Georgian country house in 312 acres of parkland — spa and weddings", contact_email: "", phone: "" },
  { venue_name: "The Seahorse", location: "Brighton seafront", city: "Brighton", county: "East Sussex", category: "Event Space", capacity: 200, distance_from_london_miles: 53, website: "seahorsebrighton.co.uk", trigger_event: "Floor to ceiling windows on Brighton seafront — natural light", contact_email: "", phone: "" },
  { venue_name: "Fabrica", location: "Duke Street, Brighton", city: "Brighton", county: "East Sussex", category: "Museum/Gallery", capacity: 120, distance_from_london_miles: 53, website: "fabrica.org.uk", trigger_event: "Art gallery in the heart of The Lanes — photography dream venue", contact_email: "", phone: "" },
  { venue_name: "Pangdean Barn", location: "Pyecombe, Brighton", city: "Brighton", county: "East Sussex", category: "Barn Venue", capacity: 200, distance_from_london_miles: 50, website: "pangdeanbarn.com", trigger_event: "Flint barn in the South Downs — exclusive-use with courtyard", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // OXFORDSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Blenheim Palace", location: "Woodstock", city: "Woodstock", county: "Oxfordshire", category: "Country Estate", capacity: 400, distance_from_london_miles: 62, website: "blenheimpalace.com", trigger_event: "UNESCO World Heritage Site — grand palace events in 2,000 acres", contact_email: "", phone: "" },
  { venue_name: "Bodleian Libraries", location: "Broad Street, Oxford", city: "Oxford", county: "Oxfordshire", category: "Historic Hall", capacity: 200, distance_from_london_miles: 57, website: "bodleian.ox.ac.uk", trigger_event: "Heart of the University — ornate Gothic architecture, Divinity School", contact_email: "", phone: "" },
  { venue_name: "Caswell House", location: "Brize Norton", city: "Witney", county: "Oxfordshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 70, website: "caswellhouse.co.uk", trigger_event: "15th century restored barns — up to 140 dining, 200 evening guests", contact_email: "", phone: "" },
  { venue_name: "Cogges Manor Farm", location: "Church Lane, Witney", city: "Witney", county: "Oxfordshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 70, website: "cogges.org.uk", trigger_event: "18th century barns, manor house, and old milking parlour", contact_email: "", phone: "" },
  { venue_name: "Merriscourt", location: "Sarsden, Chipping Norton", city: "Chipping Norton", county: "Oxfordshire", category: "Barn Venue", capacity: 250, distance_from_london_miles: 75, website: "merriscourt.com", trigger_event: "500-acre Cotswold estate — three interlinked barns with panoramic views", contact_email: "", phone: "" },
  { venue_name: "Worton Hall", location: "Worton, Witney", city: "Witney", county: "Oxfordshire", category: "Historic Hall", capacity: 400, distance_from_london_miles: 70, website: "wortonhall.co.uk", trigger_event: "Large capacity ceremony venue — up to 400 guests in Witney", contact_email: "", phone: "" },
  { venue_name: "Hawkwell House", location: "Iffley Turn, Oxford", city: "Oxford", county: "Oxfordshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 57, website: "hawkwellhouse.co.uk", trigger_event: "Timeless Oxford manor house — beautiful grounds for weddings", contact_email: "", phone: "" },
  { venue_name: "Primrose Hill Farm", location: "Chipping Norton", city: "Chipping Norton", county: "Oxfordshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 75, website: "primrose-hill-farm.com", trigger_event: "Three modern barns with epic Cotswold views — farmhouse chic", contact_email: "", phone: "" },
  { venue_name: "Stratton Court Barn", location: "Stratton Audley, Bicester", city: "Bicester", county: "Oxfordshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 55, website: "strattoncourtbarn.co.uk", trigger_event: "1870s barn with oak beams and vaulted ceilings — Oxfordshire countryside", contact_email: "", phone: "" },
  { venue_name: "Lains Barn", location: "Grove, Wantage", city: "Wantage", county: "Oxfordshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 65, website: "lainsbarn.co.uk", trigger_event: "Restored family-run barn — quintessentially rural heart of Oxfordshire", contact_email: "", phone: "" },
  { venue_name: "Dovecote Events", location: "Adderbury, Banbury", city: "Banbury", county: "Oxfordshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 72, website: "dovecoteevents.co.uk", trigger_event: "Barn and tipi venue near Banbury — vaulted ceilings and light spaces", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // GLOUCESTERSHIRE / COTSWOLDS
  // ═══════════════════════════════════════════════════════
  { venue_name: "Sudeley Castle", location: "Winchcombe, Cheltenham", city: "Cheltenham", county: "Gloucestershire", category: "Castle", capacity: 200, distance_from_london_miles: 90, website: "sudeleycastle.co.uk", trigger_event: "1,000-year-old Cotswold castle — exclusive bespoke celebrations", contact_email: "", phone: "" },
  { venue_name: "Berkeley Castle", location: "Berkeley", city: "Berkeley", county: "Gloucestershire", category: "Castle", capacity: 200, distance_from_london_miles: 110, website: "berkeley-castle.com", trigger_event: "Medieval castle in spectacular grounds — magical wedding venue", contact_email: "", phone: "" },
  { venue_name: "Thornbury Castle", location: "Thornbury", city: "Thornbury", county: "Gloucestershire", category: "Castle", capacity: 120, distance_from_london_miles: 115, website: "thornburycastle.co.uk", trigger_event: "Only Tudor castle hotel — 27 bedchambers, 15-acre grounds, exclusive hire", contact_email: "", phone: "" },
  { venue_name: "Elmore Court", location: "Elmore, Gloucester", city: "Gloucester", county: "Gloucestershire", category: "Country Estate", capacity: 200, distance_from_london_miles: 105, website: "elmorecourt.com", trigger_event: "Exclusive-use grand house — Gillyflower celebration space, handsome gardens", contact_email: "", phone: "" },
  { venue_name: "Manor by the Lake", location: "Hatherley Lane, Cheltenham", city: "Cheltenham", county: "Gloucestershire", category: "Country Estate", capacity: 180, distance_from_london_miles: 90, website: "manorbythelake.co.uk", trigger_event: "Premier Cotswold venue — Ballroom, Italianate Gardens, exclusive use", contact_email: "", phone: "" },
  { venue_name: "Kingscote Barn", location: "Kingscote, Tetbury", city: "Tetbury", county: "Gloucestershire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 100, website: "kingscotebarn.co.uk", trigger_event: "Exclusive-use 17th century Cotswold stone barn — indoor/outdoor ceremonies", contact_email: "", phone: "" },
  { venue_name: "Stone Barn", location: "near Cheltenham", city: "Cheltenham", county: "Gloucestershire", category: "Barn Venue", capacity: 180, distance_from_london_miles: 88, website: "crippsandco.com/stone-barn", trigger_event: "Cripps & Co Cotswold barn between Burford and Northleach — rustic charm", contact_email: "", phone: "" },
  { venue_name: "The Great Tythe Barn", location: "Tetbury", city: "Tetbury", county: "Gloucestershire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 100, website: "gtb.co.uk", trigger_event: "16th century Grade II listed barn — Best Barn in the South West", contact_email: "", phone: "" },
  { venue_name: "Hyde House", location: "near Stow-on-the-Wold", city: "Stow-on-the-Wold", county: "Gloucestershire", category: "Country Estate", capacity: 150, distance_from_london_miles: 80, website: "hyde-house.uk", trigger_event: "Victorian house + barn in the Cotswolds — 12 bedrooms exclusive use", contact_email: "", phone: "" },
  { venue_name: "Owlpen Manor", location: "Uley, Dursley", city: "Dursley", county: "Gloucestershire", category: "Country Estate", capacity: 150, distance_from_london_miles: 108, website: "owlpen.com", trigger_event: "Exclusive Cotswold estate — barn venue with historic landscaped gardens", contact_email: "", phone: "" },
  { venue_name: "Bredon Manor", location: "Bredon, Tewkesbury", city: "Tewkesbury", county: "Gloucestershire", category: "Country Estate", capacity: 150, distance_from_london_miles: 100, website: "bredonmanor.com", trigger_event: "Splendid venue in magnificent grounds — exclusive use Gloucestershire", contact_email: "", phone: "" },
  { venue_name: "Barn at Upcote", location: "Withington, Cheltenham", city: "Cheltenham", county: "Gloucestershire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 88, website: "barnatupcote.co.uk", trigger_event: "Family-run restored Cotswold barns — rustic charm with modern amenities", contact_email: "", phone: "" },
  { venue_name: "Lapstone Barn", location: "near Chipping Campden", city: "Chipping Campden", county: "Gloucestershire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 85, website: "lapstonebarn.co.uk", trigger_event: "Exclusive-use Cotswold barn with on-site accommodation", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // WILTSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Longleat", location: "Warminster", city: "Warminster", county: "Wiltshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 100, website: "longleat.co.uk", trigger_event: "Elizabethan stately home in 900 acres — grand events and celebrations", contact_email: "", phone: "" },
  { venue_name: "Syrencot", location: "Sandy Lane, Chippenham", city: "Chippenham", county: "Wiltshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 92, website: "syrencot.com", trigger_event: "Enchanting exclusive-use — Georgian house, barn, and glasshouse in 5 acres", contact_email: "", phone: "" },
  { venue_name: "Henge Estate", location: "Amesbury", city: "Amesbury", county: "Wiltshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 80, website: "hengeestate.co.uk", trigger_event: "Country manor in 25 acres — exclusive hire for elegant weddings", contact_email: "", phone: "" },
  { venue_name: "Cleeve House", location: "Seend, Melksham", city: "Melksham", county: "Wiltshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 95, website: "cleeve-house.com", trigger_event: "Historic manor house — exclusive use for unforgettable weddings", contact_email: "", phone: "" },
  { venue_name: "Larmer Tree", location: "Tollard Royal, Salisbury", city: "Salisbury", county: "Wiltshire", category: "Wedding Venue", capacity: 200, distance_from_london_miles: 95, website: "larmertree.co.uk", trigger_event: "Exquisite garden and luxury venue on Wiltshire/Dorset border", contact_email: "", phone: "" },
  { venue_name: "Bowood Hotel & Spa", location: "Derry Hill, Calne", city: "Calne", county: "Wiltshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 90, website: "bowood.org", trigger_event: "Capability Brown parkland — luxury estate weddings in Wiltshire", contact_email: "", phone: "" },
  { venue_name: "Trafalgar Park", location: "Downton, Salisbury", city: "Salisbury", county: "Wiltshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 85, website: "trafalgarpark.co.uk", trigger_event: "Gift from a grateful nation to the Nelson family — Palladian grandeur", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // DORSET
  // ═══════════════════════════════════════════════════════
  { venue_name: "Mapperton House", location: "Beaminster", city: "Beaminster", county: "Dorset", category: "Country Estate", capacity: 200, distance_from_london_miles: 130, website: "mapperton.com", trigger_event: "Dorset's finest country wedding venue — rolling hills near Beaminster", contact_email: "", phone: "" },
  { venue_name: "Lulworth Castle", location: "East Lulworth, Wareham", city: "Wareham", county: "Dorset", category: "Castle", capacity: 200, distance_from_london_miles: 120, website: "lulworth.com", trigger_event: "17th century castle near the Jurassic Coast — exclusive events", contact_email: "", phone: "" },
  { venue_name: "Came House", location: "Dorchester", city: "Dorchester", county: "Dorset", category: "Country Estate", capacity: 150, distance_from_london_miles: 125, website: "camehouse.co.uk", trigger_event: "Palladian country house built in 1754 — Thomas Hardy's Dorset", contact_email: "", phone: "" },
  { venue_name: "Warmwell House", location: "Crossways, Dorchester", city: "Dorchester", county: "Dorset", category: "Country Estate", capacity: 150, distance_from_london_miles: 120, website: "warmwellhouse.co.uk", trigger_event: "Jacobean manor in the heart of Hardy's Dorset — weddings and events", contact_email: "", phone: "" },
  { venue_name: "Canford School", location: "Wimborne", city: "Wimborne", county: "Dorset", category: "Historic Hall", capacity: 180, distance_from_london_miles: 105, website: "canford.com", trigger_event: "Grade I listed Great Hall — Gothic splendour for up to 180 guests", contact_email: "", phone: "" },
  { venue_name: "Italian Villa", location: "Compton Acres, Poole", city: "Poole", county: "Dorset", category: "Wedding Venue", capacity: 150, distance_from_london_miles: 110, website: "theitalianvilla.co.uk", trigger_event: "Grade II listed gardens at Compton Acres — Mediterranean elegance", contact_email: "", phone: "" },
  { venue_name: "Moonacre", location: "Near Dorchester", city: "Dorchester", county: "Dorset", category: "Wedding Venue", capacity: 120, distance_from_london_miles: 125, website: "moonacreweddings.co.uk", trigger_event: "5 acres of private woodland — enchanting unique backdrop", contact_email: "", phone: "" },
  { venue_name: "The Orangery Suite", location: "Wimborne", city: "Wimborne", county: "Dorset", category: "Wedding Venue", capacity: 150, distance_from_london_miles: 105, website: "theorangerysuite.co.uk", trigger_event: "18th century walled garden — secluded countryside location", contact_email: "", phone: "" },
  { venue_name: "Abbots Court", location: "Near Dorchester", city: "Dorchester", county: "Dorset", category: "Country Estate", capacity: 150, distance_from_london_miles: 125, website: "abbots-court.co.uk", trigger_event: "Secluded estate blending rustic charm with timeless elegance", contact_email: "", phone: "" },
  { venue_name: "Sopley Mill", location: "Sopley, Christchurch", city: "Christchurch", county: "Dorset", category: "Historic Hall", capacity: 120, distance_from_london_miles: 100, website: "sopleymill.co.uk", trigger_event: "1066-dated mill — oak beams, exposed brick, stunning river views", contact_email: "", phone: "" },
  { venue_name: "Minterne House", location: "Minterne Magna, Dorchester", city: "Dorchester", county: "Dorset", category: "Country Estate", capacity: 120, distance_from_london_miles: 125, website: "minterne.co.uk", trigger_event: "Grandeur and intimacy in picturesque Dorset countryside", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // SOMERSET
  // ═══════════════════════════════════════════════════════
  { venue_name: "Orchardleigh", location: "Frome", city: "Frome", county: "Somerset", category: "Country Estate", capacity: 160, distance_from_london_miles: 105, website: "orchardleigh.net", trigger_event: "Private 500-acre estate — Victorian stately home, 10 miles from Bath", contact_email: "", phone: "" },
  { venue_name: "Quantock Lakes", location: "Inwood Farm, Bridgwater", city: "Bridgwater", county: "Somerset", category: "Barn Venue", capacity: 250, distance_from_london_miles: 140, website: "quantocklakes.com", trigger_event: "Award-winning exclusive-use barn on 200 acres — up to 250 guests", contact_email: "", phone: "" },
  { venue_name: "Almonry Barn", location: "Muchelney, Langport", city: "Langport", county: "Somerset", category: "Barn Venue", capacity: 150, distance_from_london_miles: 130, website: "almonrybarn.co.uk", trigger_event: "Believed to be England's oldest wedding barn — historic charm", contact_email: "", phone: "" },
  { venue_name: "Crowcombe Court", location: "Crowcombe, Taunton", city: "Taunton", county: "Somerset", category: "Country Estate", capacity: 200, distance_from_london_miles: 145, website: "crowcombecourt.co.uk", trigger_event: "Grade I listed Baroque country house on the Quantock Hills", contact_email: "", phone: "" },
  { venue_name: "Priston Mill", location: "Priston, Bath", city: "Bath", county: "Somerset", category: "Barn Venue", capacity: 200, distance_from_london_miles: 110, website: "pristonmill.co.uk", trigger_event: "Stunning rural surroundings close to Bath and Bristol — two venues", contact_email: "", phone: "" },
  { venue_name: "Bath Guildhall", location: "High Street, Bath", city: "Bath", county: "Somerset", category: "Historic Hall", capacity: 300, distance_from_london_miles: 115, website: "bathguildhall.co.uk", trigger_event: "Grade I listed — Georgian interiors, grand staircases, near the Abbey", contact_email: "", phone: "" },
  { venue_name: "Waterside Country Barn", location: "Wellington", city: "Wellington", county: "Somerset", category: "Barn Venue", capacity: 200, distance_from_london_miles: 145, website: "watersidecountrybarn.com", trigger_event: "Between Bristol and Exeter — stunning barn wedding venue", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // DEVON
  // ═══════════════════════════════════════════════════════
  { venue_name: "Rockbeare Manor", location: "Rockbeare, Exeter", city: "Exeter", county: "Devon", category: "Country Estate", capacity: 160, distance_from_london_miles: 165, website: "rockbearemanor.co.uk", trigger_event: "Grade I listed Regency house in 100+ acres — exclusive weddings near Exeter", contact_email: "", phone: "" },
  { venue_name: "Pynes House", location: "Upton Pyne, Exeter", city: "Exeter", county: "Devon", category: "Country Estate", capacity: 150, distance_from_london_miles: 165, website: "pyneshouse.co.uk", trigger_event: "Exclusive-use elegant country house — packages from £2,800", contact_email: "", phone: "" },
  { venue_name: "Brickhouse Vineyard", location: "Silverton, Exeter", city: "Exeter", county: "Devon", category: "Barn Venue", capacity: 120, distance_from_london_miles: 165, website: "brickhousevineyard.co.uk", trigger_event: "Own vineyard with 18th century Round House — rustic charm", contact_email: "", phone: "" },
  { venue_name: "Upton Barn", location: "Cullompton", city: "Cullompton", county: "Devon", category: "Barn Venue", capacity: 200, distance_from_london_miles: 155, website: "uptonbarn.com", trigger_event: "Award-winning exclusive-use barn in Devon countryside", contact_email: "", phone: "" },
  { venue_name: "The Great Barn Devon", location: "Ashburton", city: "Ashburton", county: "Devon", category: "Barn Venue", capacity: 120, distance_from_london_miles: 175, website: "thegreatbarndevon.co.uk", trigger_event: "Thatched cathedral — 45ft vaulted oak ceiling with medieval courtyard", contact_email: "", phone: "" },
  { venue_name: "The Oak Barn", location: "Hittisleigh, Exeter", city: "Exeter", county: "Devon", category: "Barn Venue", capacity: 125, distance_from_london_miles: 170, website: "oakbarndevon.co.uk", trigger_event: "Three restored historic barns — ancient cob farmhouse, 90 seated", contact_email: "", phone: "" },
  { venue_name: "Powderham Castle", location: "Kenton, Exeter", city: "Exeter", county: "Devon", category: "Castle", capacity: 200, distance_from_london_miles: 170, website: "powderham.co.uk", trigger_event: "Medieval castle on the Exe Estuary — 600 years of history", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // CORNWALL
  // ═══════════════════════════════════════════════════════
  { venue_name: "Treseren", location: "Near Newquay", city: "Newquay", county: "Cornwall", category: "Country Estate", capacity: 80, distance_from_london_miles: 250, website: "treseren.co.uk", trigger_event: "Award-winning exclusive-use — historic charm meets modern elegance", contact_email: "", phone: "" },
  { venue_name: "The Alverton", location: "Tregolls Road, Truro", city: "Truro", county: "Cornwall", category: "Wedding Venue", capacity: 200, distance_from_london_miles: 260, website: "thealverton.co.uk", trigger_event: "Grade II Victorian hotel in Truro — gothic domed hall for receptions", contact_email: "", phone: "" },
  { venue_name: "Nancarrow Farm", location: "Near Truro", city: "Truro", county: "Cornwall", category: "Barn Venue", capacity: 130, distance_from_london_miles: 260, website: "nancarrowfarm.co.uk", trigger_event: "Hidden valley on outskirts of Truro — exclusive barns for weddings", contact_email: "", phone: "" },
  { venue_name: "Boconnoc", location: "Near Lostwithiel", city: "Lostwithiel", county: "Cornwall", category: "Country Estate", capacity: 200, distance_from_london_miles: 240, website: "boconnoc.com", trigger_event: "Exclusive estate in 150 acres — rolling hills and ancient oak woodland", contact_email: "", phone: "" },
  { venue_name: "Fowey Hall", location: "Fowey", city: "Fowey", county: "Cornwall", category: "Country Estate", capacity: 80, distance_from_london_miles: 245, website: "foweyhallhotel.co.uk", trigger_event: "Exclusive country house for the weekend — elopements and intimate weddings", contact_email: "", phone: "" },
  { venue_name: "Fir Hill Estate", location: "Near Newquay", city: "Newquay", county: "Cornwall", category: "Wedding Venue", capacity: 150, distance_from_london_miles: 250, website: "firhillestate.co.uk", trigger_event: "Hidden gem — woodland venue with panoramic views", contact_email: "", phone: "" },
  { venue_name: "St Michaels Resort", location: "Falmouth", city: "Falmouth", county: "Cornwall", category: "Wedding Venue", capacity: 150, distance_from_london_miles: 265, website: "stmichaelsresort.com", trigger_event: "Chic coastal wedding — subtropical gardens and seaside vows", contact_email: "", phone: "" },
  { venue_name: "Tredudwell Manor", location: "Near Fowey", city: "Fowey", county: "Cornwall", category: "Country Estate", capacity: 100, distance_from_london_miles: 245, website: "tredudwell.co.uk", trigger_event: "Cornwall wedding venue with luxury B&B — intimate exclusive events", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // NORFOLK
  // ═══════════════════════════════════════════════════════
  { venue_name: "Holkham Hall", location: "Wells-next-the-Sea", city: "Wells-next-the-Sea", county: "Norfolk", category: "Country Estate", capacity: 300, distance_from_london_miles: 120, website: "holkham.co.uk", trigger_event: "Palladian mansion in 25,000 acres — spectacular north Norfolk estate", contact_email: "", phone: "" },
  { venue_name: "Blickling Hall", location: "Aylsham", city: "Aylsham", county: "Norfolk", category: "Country Estate", capacity: 200, distance_from_london_miles: 115, website: "nationaltrust.org.uk/blickling-estate", trigger_event: "National Trust Jacobean mansion — moated house and gardens", contact_email: "", phone: "" },
  { venue_name: "Godwick Hall", location: "Tittleshall", city: "Fakenham", county: "Norfolk", category: "Barn Venue", capacity: 200, distance_from_london_miles: 110, website: "godwickhall.co.uk", trigger_event: "16th century hall in the heart of Norfolk — Great Barn and countryside", contact_email: "", phone: "" },
  { venue_name: "Manor Mews", location: "Tattersett, King's Lynn", city: "King's Lynn", county: "Norfolk", category: "Barn Venue", capacity: 150, distance_from_london_miles: 115, website: "manormewsweddings.co.uk", trigger_event: "Restored 19th century — Great Barn with 10 luxury cottages for 80 guests", contact_email: "", phone: "" },
  { venue_name: "West Lexham Manor", location: "King's Lynn", city: "King's Lynn", county: "Norfolk", category: "Country Estate", capacity: 150, distance_from_london_miles: 110, website: "westlexham.org", trigger_event: "Unique barn venue — marquee/tipi, treehouses, bell tents, up to 150 guests", contact_email: "", phone: "" },
  { venue_name: "Pentney Abbey", location: "Pentney, King's Lynn", city: "King's Lynn", county: "Norfolk", category: "Barn Venue", capacity: 150, distance_from_london_miles: 105, website: "pentneyabbey.com", trigger_event: "Historic barn wedding venue in north Norfolk — unique and unusual", contact_email: "", phone: "" },
  { venue_name: "Chaucer Barn", location: "Itteringham, Norwich", city: "Norwich", county: "Norfolk", category: "Barn Venue", capacity: 120, distance_from_london_miles: 120, website: "chaucerbarn.com", trigger_event: "Luxury barn venue near Norwich — exclusive-use with accommodation", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // SUFFOLK
  // ═══════════════════════════════════════════════════════
  { venue_name: "Hengrave Hall", location: "Hengrave, Bury St Edmunds", city: "Bury St Edmunds", county: "Suffolk", category: "Country Estate", capacity: 200, distance_from_london_miles: 75, website: "hengravehall.com", trigger_event: "Tudor mansion on 350-acre private estate — exclusive weddings", contact_email: "", phone: "" },
  { venue_name: "Blackthorpe Barn", location: "Rougham, Bury St Edmunds", city: "Bury St Edmunds", county: "Suffolk", category: "Barn Venue", capacity: 250, distance_from_london_miles: 75, website: "weddingsatblackthorpebarn.co.uk", trigger_event: "Large barn near Bury St Edmunds — up to 250 guests with Blackthorpe House", contact_email: "", phone: "" },
  { venue_name: "Suffolk Barn at Hawstead Place", location: "Hawstead, Bury St Edmunds", city: "Bury St Edmunds", county: "Suffolk", category: "Barn Venue", capacity: 150, distance_from_london_miles: 75, website: "suffolkbarn.co.uk", trigger_event: "9 acres of private grounds — choose own suppliers, 24 guest accommodation", contact_email: "", phone: "" },
  { venue_name: "Haughley Park", location: "Stowmarket", city: "Stowmarket", county: "Suffolk", category: "Country Estate", capacity: 200, distance_from_london_miles: 80, website: "haughleypark.co.uk", trigger_event: "Jacobean manor in 250 acres — Grade II barn with original oak beams", contact_email: "", phone: "" },
  { venue_name: "Wilderness Reserve", location: "Near Southwold", city: "Southwold", county: "Suffolk", category: "Country Estate", capacity: 200, distance_from_london_miles: 110, website: "wildernessreserve.com", trigger_event: "8,000 acres — 15th century Chapel Barn + Georgian Sibton Park, 86 bedrooms", contact_email: "", phone: "" },
  { venue_name: "Bury St Edmunds Guildhall", location: "Guildhall Street, Bury St Edmunds", city: "Bury St Edmunds", county: "Suffolk", category: "Historic Hall", capacity: 100, distance_from_london_miles: 75, website: "burystedmundsguildhall.org.uk", trigger_event: "Historic guildhall — intimate weddings in medieval setting", contact_email: "", phone: "" },
  { venue_name: "Bruisyard Hall", location: "Bruisyard, Saxmundham", city: "Saxmundham", county: "Suffolk", category: "Country Estate", capacity: 150, distance_from_london_miles: 100, website: "bruisyard.co.uk", trigger_event: "Medieval hall with walled garden — exclusive-use Suffolk estate", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // CAMBRIDGESHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Chippenham Park", location: "Chippenham, Newmarket", city: "Newmarket", county: "Cambridgeshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 65, website: "chippenhampark.com", trigger_event: "Grade 2 listed house in 300 acres — within reach of Cambridge and London", contact_email: "", phone: "" },
  { venue_name: "The Old Hall Ely", location: "Stuntney, Ely", city: "Ely", county: "Cambridgeshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 70, website: "theoldhallely.co.uk", trigger_event: "Jacobean manor with lake views to Ely Cathedral — exclusive use", contact_email: "", phone: "" },
  { venue_name: "Swynford Manor", location: "Six Mile Bottom, Newmarket", city: "Newmarket", county: "Cambridgeshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 60, website: "swynfordmanor.co.uk", trigger_event: "Exclusive-use 18th century manor in 7 acres of grounds and gardens", contact_email: "", phone: "" },
  { venue_name: "Childerley Long Barn", location: "Childerley, Cambridge", city: "Cambridge", county: "Cambridgeshire", category: "Barn Venue", capacity: 180, distance_from_london_miles: 58, website: "childerley.co.uk", trigger_event: "Stunning Long Barn with manicured gardens — near Cambridge", contact_email: "", phone: "" },
  { venue_name: "Spinney Abbey", location: "Wicken, Ely", city: "Ely", county: "Cambridgeshire", category: "Barn Venue", capacity: 175, distance_from_london_miles: 70, website: "spinneyabbey.com", trigger_event: "Historic barn + courtyard on working farm — 30 mins from Cambridge", contact_email: "", phone: "" },
  { venue_name: "Sissons Barn", location: "Peterborough", city: "Peterborough", county: "Cambridgeshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 85, website: "sissonsbarn.co.uk", trigger_event: "Tranquil Cambridgeshire countryside — classic charm and exclusivity", contact_email: "", phone: "" },
  { venue_name: "Willow Grange Farm", location: "Near Ely", city: "Ely", county: "Cambridgeshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 72, website: "willowgrangefarm.co.uk", trigger_event: "Wedding venue near Ely — barn celebrations in farmland setting", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // WARWICKSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Warwick Castle", location: "Warwick", city: "Warwick", county: "Warwickshire", category: "Castle", capacity: 300, distance_from_london_miles: 90, website: "warwick-castle.com", trigger_event: "Spectacular medieval castle on the Avon — immersive events", contact_email: "", phone: "" },
  { venue_name: "Compton Verney", location: "Compton Verney, Warwick", city: "Warwick", county: "Warwickshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 85, website: "comptonverney.org.uk", trigger_event: "Capability Brown grounds with art gallery — 120 acres of parkland", contact_email: "", phone: "" },
  { venue_name: "Swallows Nest Barn", location: "Sherbourne, Warwick", city: "Warwick", county: "Warwickshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 88, website: "swallowsnestbarn.co.uk", trigger_event: "Cotswold edge barn — near Stratford-upon-Avon and Leamington Spa", contact_email: "", phone: "" },
  { venue_name: "Wethele Manor", location: "Near Leamington Spa", city: "Leamington Spa", county: "Warwickshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 90, website: "wethelemanor.co.uk", trigger_event: "250-acre estate — rustic charm and modern elegance near Leamington Spa", contact_email: "", phone: "" },
  { venue_name: "Wootton Park", location: "Near Warwick", city: "Warwick", county: "Warwickshire", category: "Country Estate", capacity: 300, distance_from_london_miles: 90, website: "woottonpark.co.uk", trigger_event: "360-acre valley — exclusive-use, one wedding per day guarantee", contact_email: "", phone: "" },
  { venue_name: "Longbourn Estate Barn", location: "Compton Verney", city: "Warwick", county: "Warwickshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 85, website: "longbournestatebarn.co.uk", trigger_event: "Hidden gem in 100 acres — stone floors, vaulted roof, historic estate", contact_email: "", phone: "" },
  { venue_name: "Meadow Barn at Stratford Park", location: "Stratford-upon-Avon", city: "Stratford-upon-Avon", county: "Warwickshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 92, website: "meadowbarn.co.uk", trigger_event: "Shortlisted Best Barn Venue — Shakespeare Country countryside", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // WORCESTERSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Birtsmorton Court", location: "Birtsmorton, Malvern", city: "Malvern", county: "Worcestershire", category: "Country Estate", capacity: 200, distance_from_london_miles: 110, website: "birtsmortoncourt.com", trigger_event: "Moated medieval manor at the foot of the Malvern Hills", contact_email: "", phone: "" },
  { venue_name: "Barns and Yards", location: "Near Malvern", city: "Malvern", county: "Worcestershire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 110, website: "barnsandyards.co.uk", trigger_event: "Tudor barn with Malvern Hills backdrop — luxuriously restored", contact_email: "", phone: "" },
  { venue_name: "Rhyse Farm", location: "Worcestershire", city: "Worcester", county: "Worcestershire", category: "Barn Venue", capacity: 120, distance_from_london_miles: 110, website: "rhysefarm.co.uk", trigger_event: "Family-run countryside venue — exclusive use day before and after", contact_email: "", phone: "" },
  { venue_name: "Stanbrook Abbey", location: "Callow End, Worcester", city: "Worcester", county: "Worcestershire", category: "Country Estate", capacity: 250, distance_from_london_miles: 115, website: "stanbrookabbey.com", trigger_event: "Neo-Gothic former Benedictine monastery — 26 acres of grounds", contact_email: "", phone: "" },
  { venue_name: "The Wood Norton", location: "Evesham", city: "Evesham", county: "Worcestershire", category: "Country Estate", capacity: 200, distance_from_london_miles: 100, website: "thewoodnorton.com", trigger_event: "Luxury Victorian hotel in 170 acres — former BBC broadcasting centre", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // HEREFORDSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Eastnor Castle", location: "Ledbury", city: "Ledbury", county: "Herefordshire", category: "Castle", capacity: 250, distance_from_london_miles: 120, website: "eastnorcastle.com", trigger_event: "Dramatic Norman Revival castle — exclusive hire in deer park", contact_email: "", phone: "" },
  { venue_name: "Brinsop Court", location: "Brinsop, Hereford", city: "Hereford", county: "Herefordshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 130, website: "brinsopcourt.com", trigger_event: "800-acre exclusive estate — 14th century moated manor with barn", contact_email: "", phone: "" },
  { venue_name: "Dewsall Court", location: "Dewsall, Hereford", city: "Hereford", county: "Herefordshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 130, website: "dewsall.com", trigger_event: "Exclusive hire — 12 acres with Black Mountain views, Duchy of Cornwall land", contact_email: "", phone: "" },
  { venue_name: "Hellens Manor", location: "Much Marcle, Ledbury", city: "Ledbury", county: "Herefordshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 120, website: "hellensmanor.com", trigger_event: "16th century tithe barn seats 150 — beautiful historic manor house", contact_email: "", phone: "" },
  { venue_name: "Bredenbury Court Barns", location: "Bromyard", city: "Bromyard", county: "Herefordshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 125, website: "bredenburycourt.co.uk", trigger_event: "Exclusive-use barn in the West Midlands — luxury B&B rooms", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // BEDFORDSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Turvey House", location: "Turvey", city: "Bedford", county: "Bedfordshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 55, website: "turveyhouse.co.uk", trigger_event: "Grade I listed in 150 acres along the Great Ouse — exclusive hire", contact_email: "", phone: "" },
  { venue_name: "Woburn Abbey", location: "Woburn", city: "Woburn", county: "Bedfordshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 45, website: "woburn.co.uk", trigger_event: "Ancestral home of the Dukes of Bedford — 3,000-acre deer park", contact_email: "", phone: "" },
  { venue_name: "Southill Park", location: "Southill, Biggleswade", city: "Biggleswade", county: "Bedfordshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 45, website: "southillpark.co.uk", trigger_event: "Georgian house in Capability Brown landscape — exclusive weddings", contact_email: "", phone: "" },
  { venue_name: "The Woburn Coffee House", location: "Woburn", city: "Woburn", county: "Bedfordshire", category: "Wedding Venue", capacity: 80, distance_from_london_miles: 45, website: "thewoburncoffeehouse.co.uk", trigger_event: "Boutique venue with Orangery and private walled garden", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // NORTHAMPTONSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Althorp", location: "Althorp, Northampton", city: "Northampton", county: "Northamptonshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 70, website: "spencerofalthorp.com", trigger_event: "Spencer family estate — exclusive events in stately grandeur", contact_email: "", phone: "" },
  { venue_name: "Dodford Manor", location: "Dodford, Northampton", city: "Northampton", county: "Northamptonshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 68, website: "dodfordmanor-venue.co.uk", trigger_event: "Award-winning family-run barn — exclusive-use country estate", contact_email: "", phone: "" },
  { venue_name: "Dodmoor House", location: "Weedon, Daventry", city: "Daventry", county: "Northamptonshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 72, website: "dodmoorhouse.co.uk", trigger_event: "Exclusive-use award-winning barn — 100 to micro weddings", contact_email: "", phone: "" },
  { venue_name: "Wood Farm Everdon", location: "Everdon, Daventry", city: "Daventry", county: "Northamptonshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 74, website: "woodfarmeverdon.co.uk", trigger_event: "80 acres of Northamptonshire countryside — serene exclusive-use barn", contact_email: "", phone: "" },
  { venue_name: "The Great Barn Aynho", location: "Aynho, Banbury", city: "Banbury", county: "Northamptonshire", category: "Barn Venue", capacity: 150, distance_from_london_miles: 68, website: "thegreatbarn.net", trigger_event: "18th century barn with exposed timbers — Oxfordshire/Northants border", contact_email: "", phone: "" },
  { venue_name: "Plum Park Manor", location: "Towcester", city: "Towcester", county: "Northamptonshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 65, website: "plumparkmanor.co.uk", trigger_event: "Victorian country house in manicured parkland and formal gardens", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // ISLE OF WIGHT
  // ═══════════════════════════════════════════════════════
  { venue_name: "Northwood House", location: "Ward Avenue, Cowes", city: "Cowes", county: "Isle of Wight", category: "Country Estate", capacity: 200, distance_from_london_miles: 85, website: "northwoodhouse.org", trigger_event: "Grade II listed country house — exclusive events on the island", contact_email: "", phone: "" },
  { venue_name: "Appuldurcombe House", location: "Wroxall, Ventnor", city: "Ventnor", county: "Isle of Wight", category: "Country Estate", capacity: 150, distance_from_london_miles: 90, website: "appuldurcombe.co.uk", trigger_event: "English Heritage ruins — atmospheric exclusive weddings", contact_email: "", phone: "" },

  // ═══════════════════════════════════════════════════════
  // ADDITIONAL VENUES — Various counties
  // ═══════════════════════════════════════════════════════
  { venue_name: "Farnborough International", location: "Farnborough", city: "Farnborough", county: "Hampshire", category: "Conference Centre", capacity: 5000, distance_from_london_miles: 35, website: "farnboroughinternational.org", trigger_event: "Massive exhibition centre — 20,000 sqm flexible interiors", contact_email: "", phone: "" },
  { venue_name: "Bristol Museum & Art Gallery", location: "Queens Road, Bristol", city: "Bristol", county: "Somerset", category: "Museum/Gallery", capacity: 200, distance_from_london_miles: 120, website: "bristolmuseums.org.uk", trigger_event: "Glass vaulted ceilings, romantic balconies — ceremonies in grand halls", contact_email: "", phone: "" },
  { venue_name: "National Motor Museum", location: "Beaulieu", city: "Brockenhurst", county: "Hampshire", category: "Museum/Gallery", capacity: 200, distance_from_london_miles: 90, website: "beaulieu.co.uk", trigger_event: "Unique venue — Palace House and classic car museum", contact_email: "", phone: "" },
  { venue_name: "Littlecote House", location: "Hungerford", city: "Hungerford", county: "Berkshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 70, website: "warnerleisurehotels.co.uk/littlecote-house", trigger_event: "Tudor manor in 100 acres — Henry VIII connections", contact_email: "", phone: "" },
  { venue_name: "Highclere Castle", location: "Highclere, Newbury", city: "Newbury", county: "Hampshire", category: "Castle", capacity: 150, distance_from_london_miles: 60, website: "highclerecastle.co.uk", trigger_event: "The real Downton Abbey — exclusive events in iconic setting", contact_email: "", phone: "" },
  { venue_name: "Chilford Hall", location: "Linton, Cambridge", city: "Cambridge", county: "Cambridgeshire", category: "Barn Venue", capacity: 200, distance_from_london_miles: 55, website: "chilfordhall.co.uk", trigger_event: "Vineyard and estate near Cambridge — barn and terrace events", contact_email: "", phone: "" },
  { venue_name: "Denbies Wine Estate", location: "London Road, Dorking", city: "Dorking", county: "Surrey", category: "Wedding Venue", capacity: 200, distance_from_london_miles: 25, website: "denbies.co.uk", trigger_event: "England's largest vineyard — Gallery Restaurant and outdoor terraces", contact_email: "", phone: "" },
  { venue_name: "Knepp Castle Estate", location: "West Grinstead", city: "Horsham", county: "West Sussex", category: "Country Estate", capacity: 150, distance_from_london_miles: 42, website: "kneppestate.co.uk", trigger_event: "Rewilding estate — unique eco-conscious wedding venue", contact_email: "", phone: "" },
  { venue_name: "Hastoe Hall", location: "Tring", city: "Tring", county: "Hertfordshire", category: "Country Estate", capacity: 100, distance_from_london_miles: 32, website: "hastoehall.co.uk", trigger_event: "Arts & Crafts house in the Chilterns — intimate exclusive events", contact_email: "", phone: "" },
  { venue_name: "Coworth Park", location: "Ascot", city: "Ascot", county: "Berkshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 25, website: "dorchestercollection.com/ascot/coworth-park", trigger_event: "Dorchester Collection country house — 240 acres near Ascot", contact_email: "", phone: "" },
  { venue_name: "Stowe House", location: "Buckingham", city: "Buckingham", county: "Buckinghamshire", category: "Country Estate", capacity: 250, distance_from_london_miles: 60, website: "stowe.co.uk", trigger_event: "Magnificent country house with Capability Brown landscape gardens", contact_email: "", phone: "" },
  { venue_name: "Woburn Safari Lodge", location: "Woburn", city: "Woburn", county: "Bedfordshire", category: "Event Space", capacity: 200, distance_from_london_miles: 45, website: "woburnsafari.co.uk", trigger_event: "Unique venue within the safari park — memorable events", contact_email: "", phone: "" },
  { venue_name: "Layer Marney Tower", location: "Near Colchester", city: "Colchester", county: "Essex", category: "Historic Hall", capacity: 200, distance_from_london_miles: 60, website: "layermarneytower.co.uk", trigger_event: "Tallest Tudor gatehouse in Britain — medieval events", contact_email: "", phone: "" },
  { venue_name: "Marks Hall", location: "Coggeshall, Colchester", city: "Colchester", county: "Essex", category: "Country Estate", capacity: 200, distance_from_london_miles: 55, website: "markshall.org.uk", trigger_event: "Arboretum and walled garden — 200 acres of woodland estate", contact_email: "", phone: "" },
  { venue_name: "Parley Manor", location: "Christchurch", city: "Christchurch", county: "Dorset", category: "Country Estate", capacity: 200, distance_from_london_miles: 100, website: "parleymanor.co.uk", trigger_event: "Beautiful private estate — weddings and events near Bournemouth", contact_email: "", phone: "" },
  { venue_name: "Port Lympne", location: "Hythe", city: "Hythe", county: "Kent", category: "Country Estate", capacity: 200, distance_from_london_miles: 65, website: "aspinallfoundation.org/port-lympne", trigger_event: "Aspinall Foundation reserve — unique weddings with safari setting", contact_email: "", phone: "" },
  { venue_name: "Kirtlington Park", location: "Kirtlington, Oxfordshire", city: "Kidlington", county: "Oxfordshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 60, website: "kirtlingtonpark.co.uk", trigger_event: "Palladian manor — opulent interiors with parkland gardens", contact_email: "", phone: "" },
  { venue_name: "Aynhoe Park", location: "Aynho, Banbury", city: "Banbury", county: "Oxfordshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 70, website: "aynhoepark.co.uk", trigger_event: "Eclectic art-filled country house — one of England's most Instagrammed venues", contact_email: "", phone: "" },
  { venue_name: "Euridge Manor", location: "Castle Combe, Chippenham", city: "Chippenham", county: "Wiltshire", category: "Country Estate", capacity: 150, distance_from_london_miles: 100, website: "euridgemanor.co.uk", trigger_event: "Private manor in the Cotswolds — exclusive-use with stone barns", contact_email: "", phone: "" },
  { venue_name: "Ston Easton Park", location: "Ston Easton, Bath", city: "Bath", county: "Somerset", category: "Country Estate", capacity: 120, distance_from_london_miles: 115, website: "stoneaston.co.uk", trigger_event: "Palladian mansion in 36 acres — boutique luxury near Bath", contact_email: "", phone: "" },
  { venue_name: "The Matara Centre", location: "Kingscote, Tetbury", city: "Tetbury", county: "Gloucestershire", category: "Wedding Venue", capacity: 180, distance_from_london_miles: 100, website: "matara.co.uk", trigger_event: "Japanese-inspired gardens with contemporary barn — Cotswolds retreat", contact_email: "", phone: "" },
  { venue_name: "Iscoyd Park", location: "Whitchurch", city: "Whitchurch", county: "Shropshire", category: "Country Estate", capacity: 200, distance_from_london_miles: 150, website: "iscoydpark.com", trigger_event: "Georgian country house — exclusive-use with 12 luxury bedrooms", contact_email: "", phone: "" },
];

export default VENUE_DATABASE;
