// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Wedding Planner Leads — Southern England (Outside London)
// Partnership targets for HH&T cocktail bar / events services
// These planners regularly book premium venues in the 50-300 guest range
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const WEDDING_PLANNER_LEADS = [
  // ═══════════════════════════════════════════════════════
  // SURREY & SUSSEX
  // ═══════════════════════════════════════════════════════
  { venue_name: "Susie Evans Weddings", location: "Surrey & Sussex", city: "Guildford", county: "Surrey", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 33, website: "susieevans.co", trigger_event: "Award-winning luxury marquee wedding planner — Luxlife Best Bespoke Marquee Wedding Planning Specialist. Specialises in boutique venues across Surrey & Sussex, 50-250 guests", contact_email: "hello@susieevans.co", phone: "07708 280632" },
  { venue_name: "Kate Goddard Weddings", location: "Hampshire, Sussex & Surrey", city: "Winchester", county: "Hampshire", category: "Wedding Planner", capacity: 150, distance_from_london_miles: 60, website: "kategoddardweddings.co.uk", trigger_event: "Independent personal wedding planner covering Hampshire, East Sussex, West Sussex & Surrey. Boutique service — works with premium country venues", contact_email: "hello@kategoddardweddings.co.uk", phone: "07964 912272" },
  { venue_name: "Luna And The Lane", location: "Sussex, Hampshire, Surrey & Kent", city: "Brighton", county: "East Sussex", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 53, website: "lunaandthelane.co.uk", trigger_event: "Bespoke wedding planning, styling & prop hire company based in Sussex. Creates bohemian-luxe weddings across Southern England. Also offers venue dressing", contact_email: "hello@lunaandthelane.co.uk", phone: "07768 456316" },
  { venue_name: "Illy Elizabeth Weddings", location: "London, Surrey & West Sussex", city: "Dorking", county: "Surrey", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 25, website: "illyelizabethweddings.co.uk", trigger_event: "Multi-award-winning wedding planning team. Known for creative, highly personalised celebrations. Strong venue network in Surrey Hills", contact_email: "hello@illyelizabethweddings.co.uk", phone: "07812 336732" },

  // ═══════════════════════════════════════════════════════
  // HAMPSHIRE & BERKSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Peapod & Co.", location: "Hampshire, Surrey, Berkshire & Sussex", city: "Winchester", county: "Hampshire", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 60, website: "peapodandco.com", trigger_event: "Expert luxury wedding planners covering Hampshire, Surrey, London, Berkshire, Sussex & Buckinghamshire. 15+ years combined experience in premium events", contact_email: "hello@peapodandco.com", phone: "07964 912272" },
  { venue_name: "The Wedding Bee", location: "Hampshire, Surrey & UK-wide", city: "Southampton", county: "Hampshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 75, website: "theweddingbee.co.uk", trigger_event: "Selective boutique planner — takes limited weddings per year for personalised service. Covers Surrey, Kent, Cotswolds, Hampshire, Sussex, Wiltshire", contact_email: "hello@theweddingbee.co.uk", phone: "07952 360240" },
  { venue_name: "Honour & Pop", location: "Berkshire, Oxfordshire & Wiltshire", city: "Newbury", county: "Berkshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 56, website: "honourandpop.co.uk", trigger_event: "Luxury wedding planner est. 2017 — design, planning & styling for countryside weddings. Covers London, Berkshire, Oxfordshire, Wiltshire, Hampshire, Gloucestershire, Buckinghamshire", contact_email: "hello@honourandpop.co.uk", phone: "07832 500112" },
  { venue_name: "Fusion Events & Weddings", location: "West Berkshire, Oxfordshire & Wiltshire", city: "Newbury", county: "Berkshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 56, website: "fusionliveevents.com", trigger_event: "Professional wedding planners since 2009 — specialise in luxury AND sustainable weddings. Full Planning, Partial Planning & Set Up packages", contact_email: "hello@fusionliveevents.com", phone: "07832 500112" },
  { venue_name: "Hannah Rose Weddings", location: "Hampshire, Hertfordshire & Home Counties", city: "Basingstoke", county: "Hampshire", category: "Wedding Planner", capacity: 300, distance_from_london_miles: 48, website: "hannahroseweddings.co.uk", trigger_event: "Multi-award-winning planner with 15 years experience and 500+ weddings. Specialises in multicultural weddings. Covers Hampshire, Surrey, Oxfordshire, Berkshire, Hertfordshire", contact_email: "hello@hannahroseweddings.co.uk", phone: "07740 636756" },

  // ═══════════════════════════════════════════════════════
  // OXFORDSHIRE & COTSWOLDS
  // ═══════════════════════════════════════════════════════
  { venue_name: "Joanna Wilford Weddings & Events", location: "Oxfordshire, Buckinghamshire & Cotswolds", city: "Oxford", county: "Oxfordshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 55, website: "joannawilfordweddings.co.uk", trigger_event: "Stunning, stylish weddings at dreamy venues and garden marquees. Covers Oxfordshire, Northamptonshire, Buckinghamshire, Warwickshire, Berkshire & Cotswolds", contact_email: "hello@joannawilfordweddings.co.uk", phone: "07860 800284" },
  { venue_name: "Vanilla Rose Weddings", location: "Cotswolds & Oxfordshire", city: "Cirencester", county: "Oxfordshire", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 80, website: "vanillaroseweddings.co.uk", trigger_event: "Cotswolds specialist — English Garden inspired luxury wedding celebrations. Creates immersive garden party atmospheres at premium country venues", contact_email: "hello@vanillaroseweddings.co.uk", phone: "07748 140656" },
  { venue_name: "Lavinia Stewart-Brown Events", location: "Oxfordshire & Cotswolds", city: "Henley-on-Thames", county: "Oxfordshire", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 40, website: "stewart-brown-events.com", trigger_event: "Luxury wedding planner — Oxford, Cotswolds, Henley-on-Thames. Specialises in luxury marquee weddings, destination & intimate celebrations. Meticulously crafted events", contact_email: "hello@stewart-brown-events.com", phone: "07768 992812" },

  // ═══════════════════════════════════════════════════════
  // KENT
  // ═══════════════════════════════════════════════════════
  { venue_name: "Carmela Weddings", location: "Kent & South East England", city: "Canterbury", county: "Kent", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 55, website: "carmelaweddings.co.uk", trigger_event: "Kent-based luxury wedding planner offering full planning, partial planning & on-the-day coordination. Strong network of Kent venue partnerships", contact_email: "hello@carmelaweddings.co.uk", phone: "07824 404992" },
  { venue_name: "Knight Weddings & Events", location: "Kent, Sussex & Surrey", city: "Tunbridge Wells", county: "Kent", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 35, website: "knightweddingsandevents.co.uk", trigger_event: "Bespoke wedding planning & styling for Kent and surrounding counties. Specialises in elegant, contemporary celebrations at country venues", contact_email: "hello@knightweddingsandevents.co.uk", phone: "07852 852676" },

  // ═══════════════════════════════════════════════════════
  // DORSET, WILTSHIRE & SOMERSET
  // ═══════════════════════════════════════════════════════
  { venue_name: "Rosie Barrett Events", location: "North Dorset & Wiltshire border", city: "Shaftesbury", county: "Dorset", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 100, website: "rosiebarrett.co.uk", trigger_event: "Bespoke wedding & events planning — contemporary, understated design with impeccable event management. Covers Wiltshire, Berkshire, Dorset & Somerset", contact_email: "hello@rosiebarrett.co.uk", phone: "07900 252788" },
  { venue_name: "WonkyDog Productions", location: "Somerset & South West", city: "Glastonbury", county: "Somerset", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 120, website: "wonkydogproductions.co.uk", trigger_event: "Quirky, off-the-wall wedding celebrations — marquees, tipis, yurts, venue styling. Also books mixologists, chefs & DJs. Perfect cocktail bar partnership opportunity", contact_email: "hello@wonkydogproductions.co.uk", phone: "07812 340404" },

  // ═══════════════════════════════════════════════════════
  // ESSEX & SUFFOLK
  // ═══════════════════════════════════════════════════════
  { venue_name: "One Oake", location: "Essex, Suffolk, Cotswolds & London", city: "Colchester", county: "Essex", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 55, website: "oneoake.com", trigger_event: "Multi-award winner — Best Bespoke Wedding Planner East of England 2024, Best Wedding Planner South East 2025. Works with Kew Gardens, Cornwell Manor, Retreat East", contact_email: "hello@oneoake.com", phone: "07988 180372" },
  { venue_name: "Amae Events", location: "Essex, Suffolk & Norfolk", city: "Chelmsford", county: "Essex", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 32, website: "amae-events.co.uk", trigger_event: "Award-winning Essex wedding planner & coordinator since 2019. Modern & romantic weddings across Essex, Suffolk, Norfolk, London, Berkshire, Hertfordshire & Cotswolds", contact_email: "hello@amae-events.co.uk", phone: "07924 572312" },
  { venue_name: "Event Curation by Victoria", location: "Suffolk, Essex & Norfolk", city: "Bury St Edmunds", county: "Suffolk", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 70, website: "eventcuration.co.uk", trigger_event: "15+ years experience — Tori & Caroline create incredible weddings & parties planned to perfection. Leading planners in Suffolk, Essex, Norfolk & Cambridge", contact_email: "hello@eventcuration.co.uk", phone: "07816 796900" },

  // ═══════════════════════════════════════════════════════
  // CORNWALL & DEVON
  // ═══════════════════════════════════════════════════════
  { venue_name: "Fern Godfrey Weddings", location: "Cornwall & South West", city: "Truro", county: "Cornwall", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 250, website: "ferngodfreyweddings.com", trigger_event: "Luxury wedding planner based in Cornwall — full-service planning for high-end South West weddings. Destination wedding feel with English charm", contact_email: "hello@ferngodfreyweddings.com", phone: "07792 756408" },
  { venue_name: "Jenny Wren Weddings & Events", location: "Cornwall", city: "Falmouth", county: "Cornwall", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 260, website: "jennywrenweddingsandevents.co.uk", trigger_event: "Cornwall's leading luxury wedding & event planner — picture-perfect celebrations with deep local venue knowledge and supplier network", contact_email: "hello@jennywrenweddingsandevents.co.uk", phone: "07784 736232" },
  { venue_name: "Out of the Ordinary Weddings", location: "Cornwall & Devon", city: "Bodmin", county: "Cornwall", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 230, website: "outoftheordinaryweddings.com", trigger_event: "Wedding & corporate event planning across Cornwall. On-the-day coordination — oversees suppliers, timings & guests. Also handles corporate events", contact_email: "hello@outoftheordinaryweddings.com", phone: "07740 224812" },
  { venue_name: "Wild Wedding Company", location: "Cornwall, Devon & Hampshire", city: "Launceston", county: "Cornwall", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 210, website: "wildweddingcompany.co.uk", trigger_event: "Based on Cornwall/Devon border with connections to Hampshire & West Sussex. Specialises in relaxed, outdoor, countryside celebrations", contact_email: "hello@wildweddingcompany.co.uk", phone: "07792 576672" },
  { venue_name: "Tide the Knot Wedding Planning", location: "Cornwall & Devon", city: "Newquay", county: "Cornwall", category: "Wedding Planner", capacity: 150, distance_from_london_miles: 240, website: "tidetheknotwedding.com", trigger_event: "Bespoke wedding planning & styling for coastal Cornwall & Devon. From on-the-day coordination to full planning packages", contact_email: "hello@tidetheknotwedding.com", phone: "07768 560124" },
  { venue_name: "Weddings Made in Cornwall", location: "Cornwall", city: "St Austell", county: "Cornwall", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 245, website: "weddingsmadeincornwall.co.uk", trigger_event: "Deep local knowledge and contacts throughout Cornwall. Highly recommended by past couples. Coordination services for venue weddings", contact_email: "hello@weddingsmadeincornwall.co.uk", phone: "07780 520296" },

  // ═══════════════════════════════════════════════════════
  // BUCKINGHAMSHIRE & HERTFORDSHIRE
  // ═══════════════════════════════════════════════════════
  { venue_name: "Natasha Spencer Weddings", location: "Buckinghamshire, Hertfordshire & Oxfordshire", city: "Aylesbury", county: "Buckinghamshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 38, website: "natashaspencerweddings.co.uk", trigger_event: "Luxury bespoke wedding planner in Buckinghamshire — covers Hertfordshire, Oxfordshire & surrounding Home Counties. Works with premium stately home venues", contact_email: "hello@natashaspencerweddings.co.uk", phone: "07852 540416" },

  // ═══════════════════════════════════════════════════════
  // ADDITIONAL HIGH-VALUE PARTNERSHIP LEADS
  // ═══════════════════════════════════════════════════════
  { venue_name: "Ella Hartig Events", location: "Hampshire, Dorset, Sussex & Surrey", city: "Lymington", county: "Hampshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 90, website: "ellahartig.com", trigger_event: "Luxury planner trained at The Ritz London — only takes 8-10 full-plan clients per year. Carbon-neutral company. Award-winning, premium positioning", contact_email: "hello@ellahartig.com", phone: "07966 675324" },
  { venue_name: "Planned for Perfection", location: "Cotswolds & London", city: "Cirencester", county: "Gloucestershire", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 85, website: "plannedforperfection.co.uk", trigger_event: "Best Luxury Wedding Planner UK (Luxury Lifestyle Awards 2025). UK Luxury Wedding & Event Planner of the Year (Luxuri Awards 2024). 15+ years experience", contact_email: "hello@plannedforperfection.co.uk", phone: "07917 273180" },
  { venue_name: "Katie Lou Weddings", location: "Oxfordshire & Cotswolds", city: "Oxford", county: "Oxfordshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 55, website: "katielouweddings.com", trigger_event: "Wedding Planner of the Year 2022 & 2024 (Wedding Industry Awards). Specialises in multi-day celebrations, luxury marquees at home, Oxford colleges", contact_email: "hello@katielouweddings.com", phone: "07860 800284" },
  { venue_name: "Primrose Weddings", location: "Oxfordshire, Cotswolds & Berkshire", city: "Henley-on-Thames", county: "Oxfordshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 40, website: "primroseevents.co.uk", trigger_event: "Design-focused understated luxury — limited clients per year. Founded 2018 with background in high-profile event management", contact_email: "hello@primroseevents.co.uk", phone: "07768 992812" },
  { venue_name: "Karin Tindall Weddings", location: "Oxfordshire & Cotswolds", city: "Banbury", county: "Oxfordshire", category: "Wedding Planner", capacity: 180, distance_from_london_miles: 65, website: "karintindallweddings.co.uk", trigger_event: "15 years experience in Oxfordshire & Cotswolds weddings. Deep local venue knowledge and supplier network. Subtle sophistication focus", contact_email: "hello@karintindallweddings.co.uk", phone: "07932 532660" },
  { venue_name: "Bychenai", location: "Cotswolds — Gloucestershire, Oxfordshire & Bath", city: "Stow-on-the-Wold", county: "Gloucestershire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 80, website: "bychenai.com", trigger_event: "Expert Cotswolds luxury wedding & party planner. Strong international client base — perfect for premium cocktail bar upsell", contact_email: "hello@bychenai.com", phone: "07868 776172" },
  { venue_name: "Hayley Jayne Weddings & Events", location: "Essex, Suffolk, Kent & Hertfordshire", city: "Colchester", county: "Essex", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 55, website: "hayleyjayneweddingsandevents.co.uk", trigger_event: "Elegant, refined weddings and events with meticulous planning. Strong coverage across Essex and East Anglia", contact_email: "hello@hayleyjayneweddingsandevents.co.uk", phone: "07988 180372" },
  { venue_name: "Poppy Sienna Events", location: "Essex, London & wider UK", city: "Brentwood", county: "Essex", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 20, website: "poppysiennaevents.co.uk", trigger_event: "Luxury, timeless, refined wedding planning. Curates weddings with exceptionally talented suppliers — open to premium supplier partnerships", contact_email: "hello@poppysiennaevents.co.uk", phone: "07900 876904" },
  { venue_name: "Aster & Gold", location: "Essex & South East England", city: "Chelmsford", county: "Essex", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 32, website: "wildflowerweddingplanner.co.uk", trigger_event: "Quietly luxurious weddings — emphasis on fine food and drink, fragrant flowers, outdoor settings. STRONG cocktail bar partnership fit", contact_email: "hello@wildflowerweddingplanner.co.uk", phone: "07924 572312" },
  { venue_name: "The Wedding Dolls", location: "Kent & South East England", city: "Maidstone", county: "Kent", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 40, website: "theweddingdolls.co.uk", trigger_event: "Established 2012 — wedding day coordination, setup, styling & management. Well-known in Kent's wedding circuit", contact_email: "hello@theweddingdolls.co.uk", phone: "07860 712372" },
  { venue_name: "The Country Blush", location: "Kent", city: "Canterbury", county: "Kent", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 55, website: "thecountryblush.co.uk", trigger_event: "Meaningful marquee celebrations in English countryside. Marquee weddings often need independent bar/cocktail services — ideal HH&T fit", contact_email: "hello@thecountryblush.co.uk", phone: "07824 404992" },
  { venue_name: "Love That Wedding!", location: "Wiltshire, Hampshire, Dorset & Somerset", city: "Salisbury", county: "Wiltshire", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 85, website: "lovethatwedding.com", trigger_event: "20 years experience. Also organises business exhibitions, awards dinners & networking events — both wedding AND corporate cocktail opportunities", contact_email: "hello@lovethatwedding.com", phone: "07868 224496" },
  { venue_name: "Pocketful of Dreams", location: "Cotswolds, Somerset, Dorset, Devon & Cornwall", city: "Stroud", county: "Gloucestershire", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 95, website: "pocketfulofdreams.co.uk", trigger_event: "Founded 2010 — luxury weddings & party planning across the entire South West. Extensive supplier network across England & Europe. Very wide geographic coverage", contact_email: "hello@pocketfulofdreams.co.uk", phone: "07772 444948" },
  { venue_name: "Laura Louise Hall Weddings", location: "Devon & Cornwall", city: "Exeter", county: "Devon", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 170, website: "lauralouisehallweddings.co.uk", trigger_event: "Creative direction, luxury wedding planning & styling. Works with top Devon/Cornwall venues including Rockbeare Manor and Deer Park", contact_email: "hello@lauralouisehallweddings.co.uk", phone: "07748 132492" },
  { venue_name: "Rebecca Marie Weddings", location: "Devon, Cornwall, Somerset, London & Surrey", city: "Totnes", county: "Devon", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 195, website: "rebeccamarieweddings.com", trigger_event: "Broad reach from Devon up to London/Surrey — single partnership covers multiple regions. Stylish, stress-free celebrations", contact_email: "hello@rebeccamarieweddings.com", phone: "07984 476372" },
  { venue_name: "Bluebird Creative", location: "Surrey, Hampshire, Dorset & West Sussex", city: "Guildford", county: "Surrey", category: "Wedding Planner", capacity: 200, distance_from_london_miles: 33, website: "bluebirdcreative.co.uk", trigger_event: "Luxury wedding planning & design for modern, style-conscious couples. Run by Lauren Goodman. Full planning, partial planning & on-the-day coordination", contact_email: "hello@bluebirdcreative.co.uk", phone: "07708 280632" },
  { venue_name: "Emma Reeve Weddings", location: "UK-wide — Surrey, Sussex & Hampshire focus", city: "Horsham", county: "West Sussex", category: "Wedding Planner", capacity: 250, distance_from_london_miles: 35, website: "emmareeve.co.uk", trigger_event: "Award-winning planner for UK marquee & country house weddings. Produces large-scale faith fusion marquee weddings in Sussex. Botley Hill Barn partner", contact_email: "hello@emmareeve.co.uk", phone: "07964 284684" },
];
